bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CAPI.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptImpl.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoExplicitEncryptOptions.java
bindings/java/mongocrypt/src/test/java/com/mongodb/crypt/capi/MongoCryptTest.java
bindings/java/mongocrypt/src/test/resources/collection-info.json
bindings/java/mongocrypt/src/test/resources/encrypted-command-reply.json
bindings/java/mongocrypt/src/test/resources/encrypted-command.json
bindings/java/mongocrypt/src/test/resources/encrypted-value.json
bindings/java/mongocrypt/src/test/resources/json-schema.json
bindings/java/mongocrypt/src/test/resources/key-document.json
bindings/java/mongocrypt/src/test/resources/key-filter.json
bindings/java/mongocrypt/src/test/resources/kms-reply.txt
bindings/java/mongocrypt/src/test/resources/mongocryptd-reply.json

Remove IV per API changes, and update the test data for the new larger 96 byte key.
Fixes the build-and-test-java task in Evergreen:
https://evergreen.mongodb.com/version/5ce61a7157e85a2ac530ab4c

update Java bindings for new crypto changes

---

bindings/java/mongocrypt/build.gradle.kts
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CAPI.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptImpl.java

@markbenvenuto reported an error while running YCSB tests using the Java bindings:
`
JNA: callback object has been garbage collected. 
`
I suspected it had to do with the LogCallback instance not having a strong reference to it, and it turned out to be the case.  Running YCSB with this fix shows that the error messages are gone.
Also fixed a few other issues I found while testing the fix.

Strong reference to callback

---

bindings/node/lib/stateMachine.js
bindings/node/test/stateMachine.test.js

We were incorrectly calculating how many bytes we needed
to read, resulting in cryptic TLS errors. Now we
will rely solely on request.bytesNeeded.

NODE: rely on request.bytesNeeded for ending kms requests

---

bindings/node/README.md
bindings/node/etc/README.hbs
bindings/node/package.json

Ignore `README.md`, it is autogenerated from `etc/README.hbs`

NODE: Add tools to generate documentation in README

---

bindings/node/lib/autoEncrypter.js
bindings/node/lib/clientEncryption.js
bindings/node/lib/cryptoCallbacks.js
bindings/node/src/mongocrypt.cc
bindings/node/src/mongocrypt.h
bindings/node/test/clientEncryption.test.js

This implements crypto callbacks so that the node bindings can be implemented without having to link to OpenSSL. The required methods are passed in via options passed into `MongoCrypt`. Ideally, this will be refactored to set the crypto hooks one time on the top-level module, but that can be follow-on work.

NODE-2071: implement crypto hooks for the node bindings

---

.evergreen/config.yml
bindings/python/.evergreen/test.sh
bindings/python/README.rst
bindings/python/pymongocrypt/binding.py
bindings/python/pymongocrypt/mongocrypt.py
bindings/python/setup.py
bindings/python/test/__init__.py
bindings/python/test/test_binding.py
bindings/python/test/test_mongocrypt.py

Patch: https://evergreen.mongodb.com/version/5d3b778457e85a2fe4c2d023
This change adds evergreen tests for the python binding. Right now it only tests on RHEL 6.2 with the following interpreters:
```
PYTHONS=("/opt/python/2.7/bin/python" \
"/opt/python/3.4/bin/python3" \
"/opt/python/3.5/bin/python3" \
"/opt/python/3.6/bin/python3" \
"/opt/python/pypy/bin/pypy" \
"/opt/python/pypy3.6/bin/pypy3")
```
This change required me to introduce a `init()` method to allow overriding the libmongocrypt library path. Without an `init()` method we would need to use `LD_LIBRARY_PATH` or other platform specific environment variables. Also note that we can remove `init()` once we bind and distribute the nocrypto build.

PYTHON-1888 Add evergreen testing for Python binding

---

bindings/node/.gitignore
bindings/node/binding.gyp
bindings/node/etc/build-static.sh
bindings/node/lib/mongocryptdManager.js
bindings/node/package.json
bindings/node/test/clientEncryption.test.js

This change set includes all the pieces required to build the addon statically on a given host:
- `binding.gyp` has been updated to accept a build variant: `dynamic` or `static`
- A script, `etc/build-static.sh` automates the process of downloading and building libbson, and libmongocrypt (currently from source for libbson, and from the current working tree for libmongocrypt)

NODE-2072: provide infrastructure for statically linking the addon

---

bindings/python/pymongocrypt/auto_encrypter.py
bindings/python/pymongocrypt/compat.py
bindings/python/pymongocrypt/state_machine.py
bindings/python/test/test_mongocrypt.py

Patch: https://evergreen.mongodb.com/version/5d436d763066150e7cbd0e28
This is the branch that https://jira.mongodb.org/browse/PYTHON-1884 is using.

PYTHON-1928 Add state machine/callback/auto encryption API

---

bindings/node/binding.gyp

On OSX, node 4 and node 6 do not compile with C++11 by default.
Needed to add xcode_settings to force C++11 compilation to allow
for smart pointers

NODE: fix node build on osx for node 4 & 6

---

bindings/python/pymongocrypt/compat.py
bindings/python/pymongocrypt/explicit_encrypter.py
bindings/python/pymongocrypt/mongocrypt.py
bindings/python/pymongocrypt/state_machine.py
bindings/python/test/data/encrypted-value.json
bindings/python/test/data/key-document.json
bindings/python/test/data/kms-encrypt-reply.txt
bindings/python/test/test_mongocrypt.py

Still todo: 
Jira: https://jira.mongodb.org/browse/PYTHON-1937
Patch: https://evergreen.mongodb.com/version/5d48d9c657e85a23e31c596f

PYTHON-1937 Add explicit encryption API

---

bindings/node/lib/cryptoCallbacks.js
bindings/node/lib/stateMachine.js
bindings/node/src/mongocrypt.cc
bindings/node/test/cryptoCallbacks.test.js

Passes crypto errors that occur on the js side back to
libmongocrypt. Requires every cryptoCallback to return a number
on success, or an error on failure.
Also required an update to the state machine logic to account for
an error occurring during mongocrypt_ctx_finalize.
~Note: errors in cryptoCallbacks sha256 and hmacSha256 will
cause a segfault until CDRIVER-3282 is fixed~ This is fixed
Fixes NODE-2082

NODE: feat(cryptoCallbacks): pass crypto errors to libmongocrypt

---

.evergreen/config.yml
bindings/node/.evergreen/find_cmake.sh
bindings/node/.evergreen/setup_environment.sh
bindings/node/.evergreen/test.sh
bindings/node/etc/build-static.sh
bindings/node/test/autoEncrypter.test.js
bindings/node/test/clientEncryption.test.js

Have done the following:
1. Updated the unit tests so that all tests that require a `mongod` or `mongocryptd` can be skipped with the environment variable `NODE_SKIP_LIVE_TESTS`
1. Refactored `etc/build-static.sh` to properly keep track of directories and to copy over files installed in the "wrong" folder (`lib64` instead of `lib`).
1. Added a test task to libmongocrypt to build and test node.
- Most tests are disabled in CI b/c they depend on a running `mongod` and/or `mongocryptd`. However, this at least gets a test that the library can be built and loaded

NODE: Adding node tests to evergreen

---

bindings/python/.evergreen/test.sh
bindings/python/README.rst
bindings/python/pymongocrypt/binding.py
bindings/python/test/__init__.py

Patch: https://evergreen.mongodb.com/version/5d4c7d9c7742ae7cdbbcc850
This change makes pymongocrypt load the library at import time and removes the clunky `init` method. I've also renamed MONGOCRYPT_LIB to PYMONGOCRYPT_LIB.

Remove clunky init method from python binding

---

.evergreen/config.yml
bindings/node/.evergreen/prebuild.sh
bindings/node/.evergreen/test.sh
bindings/node/binding.gyp
bindings/node/etc/build-static.sh
bindings/node/package.json

this is an extension of #39, and will be rebased once #39 is merged.
This adds support for using `prebuild` to publish prebuilt node bindings that can be auto-downloaded. This allows users to avoid having to install `libbson` or `libmongocrypt` locally.

Node use prebuild

---

bindings/python/.evergreen/test.sh

Passing patch: https://evergreen.mongodb.com/version/5d4ef3480305b95ae4b3a568
The PyPy 2 segfault was resolved by  [PYTHON-1925](https://jira.mongodb.org/browse/PYTHON-1925).

PYTHON-1924 Enable testing with PyPy 2

---

bindings/node/lib/clientEncryption.js
bindings/node/src/mongocrypt.cc
bindings/node/test/clientEncryption.test.js
bindings/node/test/cryptoCallbacks.test.js
bindings/node/test/requirements.helper.js

Adds support for keyAltNames when defining data keys and during explicit encryption.

Node 2069/support key alt names

---

.evergreen/config.yml
bindings/node/.evergreen/prebuild.sh

Fixing node evergreen:
- fixing a typo in the prebuild script
- disabling the force-publish task

NODE: fix node evergreen config

---

bindings/python/build-manylinux-wheel.sh
bindings/python/pymongocrypt/binding.py
bindings/python/release.sh
bindings/python/setup.py

I've manually tested that the manylinux2010 wheel can be installed and used on RHEL 6.2, ubuntu 14.04, and amazon linux.

PYTHON-1963 Make pymongocrypt compatible with manylinux2010 releases

---

bindings/node/lib/cryptoCallbacks.js
bindings/node/package.json
bindings/node/src/mongocrypt.cc
bindings/node/test/cryptoCallbacks.test.js

Node 4 does not support crypto.randomFill, so we fall back to
crypto.randomBytes.
Fixes NODE-2117
Currently working on a test to ensure that an error throw of `randomBytes` will be properly caught.

NODE: fix(crypyoHooks): make crypto hooks work in Node 4

---

bindings/node/lib/autoEncrypter.js
bindings/node/lib/stateMachine.js

Adds a field where we can pass in user BSON serialization
options like promoteValues. We need to respect these options
when it comes to user data.
Fixes NODE-2278
~TODO: Find a way to test this.~ Tests in https://github.com/mongodb/node-mongodb-native/pull/2194

fix(bson): respect user bson options when using autoEncryption

---

src/mongocrypt.h.in

Randomized --> Random
Let me know if there are any other places where I should fix this

Fix typo in mongocrypt.h.in documentation

---

bindings/python/pymongocrypt/binding.py
bindings/python/pymongocrypt/explicit_encrypter.py
bindings/python/pymongocrypt/mongocrypt.py
bindings/python/strip_header.py
bindings/python/test/test_mongocrypt.py

Implements the pymongocrypt side of https://jira.mongodb.org/browse/PYTHON-2012.
Patch: https://evergreen.mongodb.com/version/5dba26d232f4172b4e9ac3bb

PYTHON-2012 Support custom endpoint with AWS masterkey provider

---

bindings/node/README.md
bindings/node/lib/autoEncrypter.js
bindings/node/lib/clientEncryption.js
bindings/node/lib/stateMachine.js
bindings/node/src/mongocrypt.cc
bindings/node/test/stateMachine.test.js

Status:
- Update bindings to libmongocrypt to call mongocrypt_ctx_setopt_masterkey_aws_endpoint with the value of "endpoint" is passed DataKeyOpts.masterKey
- Update libmongocrypt to latest version.
- Implement prose test under the section Custom Endpoint Test.
- Update the return type (if necessary) of createDataKey to be a BSON binary
- Spawned mongocryptd should redirect stdout and stderr to /dev/null
- Resync the FLE JSON spec tests
- Update the prose test of Data key and double encryption to check command started events
- Check that bulk write batch splitting logic matches the section "Size limits for Write Commands"
- Update the prose test under the section BSON size limits and batch splitting.
Is validated by https://github.com/mongodb/node-mongodb-native/pull/2198

Node 2255/fle ga changes

---

.evergreen/config.yml

Per discussion, since this task fails on patch builds, let's skip it for patch builds.
Evergreen: https://evergreen.mongodb.com/version/5dc453d30ae606778ccf39ea

skip 'publish snapshot' on patch builds

---

bindings/node/lib/autoEncrypter.js
bindings/node/lib/mongocryptdManager.js
bindings/node/package.json

Now that we have server selection in 3.3.4-rc0 working, we
can remove the heuristic logic from the MongocryptdManager
and instead rely on server selection to do it for us.
Fixes NODE-2109

NODE-2109: Follow spec for auto-spawning mongocryptd

---

CMakeLists.txt
kms-message/CMakeLists.txt

Since kms_message is built as a static library, it needs to be
included on the link line for all statically compiled targets that
need to include it. Additionally, `KMS_MSG_STATIC` needed to be
defined during `mongocrypt_static` compilation in order to avoid
prefixing symbols which assumed a dynamic build.

fix static builds on windows

---

bindings/node/index.js
bindings/node/package.json

Rather than require users inject mongodb into
mongodb-client-encryption we assume that require('mongodb')
resolves to the user mongodb package. If users need to ensure
their mongodb version is used, they can use the extension function
to achieve the old injection effect.
Note: Uses getters to avoid a circular load call.

NODE-2339: change APIn to remove mandatory injection

---

kms-message/src/kms_request.c
test/test-mongocrypt-crypto-hooks.c

This method can return `NULL`, so a null check is required in order to prevent segfaults.
**NOTE:** sorry for the kind of cheesy test case. I think the unit test belongs in `kms_message` but there didn't seem to be existing tests there outside of the AWS test suite, and this was much easier for me to add.

MONGOCRYPT-212 add null check for `kms_request_get_canonical`

---

src/mongocrypt.h.in

There are some docstrings in `mongocrypt.h.in` that say to retrieve a failure status on a `mongocrypt_kms_ctx_t` object using `mongocrypt_ctx_status` -- I believe a few of these are wrong and should actually say `mongocrypt_kms_ctx_status`, based on the Python binding. Let me know if this isn't the case.

Replace mongocrypt_ctx_status with mongocrypt_kms_ctx_status

---

bindings/node/README.md
bindings/node/lib/clientEncryption.js

Was pointed out in the crypto audit of libmongocrypt.

fix typo in node bindings

---

kms-message/CMakeLists.txt

This file have to be installed as included from `kms_messgage.h` which is installed.
https://github.com/mongodb/libmongocrypt/blob/master/kms-message/src/kms_message/kms_message.h#L27

install kms_caller_identity_request.h

---

.evergreen/config.yml
bindings/python/.evergreen/test.sh

This change does three things:
1. Migrates Python tests to windows-64-vsMulti-small. This distro has the modern python toolchain which solves the current build failures.
1. Changes our evergreen to download the libmongocrypt build from "build-and-test-and-upload". This removes the need to compile libmongocrypt from source. I had to do this because libmongocrypt does not compile on windows-64-vsMulti-small.
1. Changes our test script to always use virtualenv on Windows.
Patch: https://evergreen.mongodb.com/version/5e729af11e2d17595815ecdc

PYTHON-2169 Migrate Python tests to windows-64-vsMulti-small

---

bindings/python/.evergreen/test.sh

https://jira.mongodb.org/browse/MONGOCRYPT-258
We can simplify the python binding test setup on Windows now that we test with windows-64-vsMulti-small (PYTHON-2169) using a real Windows toolchain. In particular we no longer need to use "venv" or manually upgrade pip/setuptools.

MONGOCRYPT-258 Simplify python binding test setup on Windows

---

test/test-mongocrypt-log.c

stdout is a readonly with musl libc which is used by Alpine Linux.
There is no define check for MUSL (i.e. there is no equivalent to __GLIBC__). As a result, I defined this test as only running on APPLE and GLIBC. This will miss Freebsd, etc but we will still get coverage on our core platforms.

MONGOCRYPT-261 Build tests on musl

---

kms-message/CMakeLists.txt
kms-message/src/kms_azure_request.c
kms-message/src/kms_b64.c
kms-message/src/kms_message/kms_azure_request.h
kms-message/src/kms_message/kms_b64.h
kms-message/test/test_kms_azure_online.c

Convenience helpers for constructing Azure requests in KMS message. The test-python task failure is unrelated, and tracked in MONGOCRYPT-276.

MONGOCRYPT-270 add Azure KMS message requests

---

CMakeLists.txt
kms-message/src/kms_request_str.h
src/mongocrypt-cache-oauth-private.h
src/mongocrypt-cache-oauth.c
src/mongocrypt-ctx-datakey.c
src/mongocrypt-ctx-private.h
src/mongocrypt-kms-ctx-private.h
src/mongocrypt-kms-ctx.c
src/mongocrypt-private.h
src/mongocrypt.c

Adds support for the create data key function using the Azure KMS provider.
Adds a simple oauth cache, which obtains a new token if the token is expiring within a buffer period of 5s.

MONGOCRYPT-269 create data key support for Azure

---

kms-message/src/kms_azure_request.c
src/mongocrypt-buffer.c
src/mongocrypt-ctx.c
src/mongocrypt-endpoint-private.h
src/mongocrypt-endpoint.c
src/mongocrypt-key-broker-private.h
src/mongocrypt-key-broker.c
src/mongocrypt-key-private.h
src/mongocrypt-key.c
src/mongocrypt-kms-ctx-private.h
src/mongocrypt-kms-ctx.c
test/test-mongocrypt-key.c

Summary:
- Support Azure for automatic/explicit encryption/decryption.
- Adds a new state to mongocrypt_key_broker_t, KB_AUTHENTICATING.
- Parses the Azure key encryption key from a key document.
I did the following to test:
- Ran all existing CSFLE C driver tests (which only tests AWS/local).
- Used the new csfle runner in this repo to test auto/explicit encryption/decryption like so:
Create a datakey:
```
./cmake-build/csfle create_datakey --kms_provider azure --azure_kek_keyname test-key --azure_kek_keyvaultendpoint https://key-vault-kevinalbs.vault.azure.net/
{ "_id" : { "$binary" : { "base64": "Gp4a+RjPT4q3s+nHVlCuUQ==", "subType" : "04" } }, "keyMaterial" : { "$binary" : { "base64": "Aw3skVxuBo+Ta52qMboDEdxfvMJC3BULtLUEKSpHproZKonZ7KA/1Pj0KsRGyDQ4wZnjuxkwa3ummJxlS2+cM14vLQYYMOtLXM+kn …
```

MONGOCRYPT-273 support Azure auto/explicit

---

.evergreen/config.yml
kms-message/src/kms_crypto_libcrypto.c

I noticed that a failure of test_kms_request was not failing the build-and–test-and-upload task. After fixing that, that surfaced a bug in the OpenSSL signature code.

MONGOCRYPT-281 fail task on script err

---

etc/rewrite.py
kms-message/src/hexlify.c
kms-message/src/hexlify.h
kms-message/src/kms_message_private.h
kms-message/src/kms_response_parser.c
kms-message/test/example-chunked-response.bin
kms-message/test/example-multi-chunked-response.bin
kms-message/test/test_kms_request.c

GCP HTTP responses used `Transfer-Encoding: chunked`. This adds support in the tiny kms-message HTTP parser.

MONGOCRYPT-282 support chunked transfer encoding

---

kms-message/CMakeLists.txt
kms-message/src/kms_crypto.h
kms-message/src/kms_gcp_request.c
kms-message/src/kms_message/kms_gcp_request.h
kms-message/src/kms_message/kms_request_opt.h
kms-message/src/kms_request_opt.c
kms-message/test/test_kms_gcp_online.c
kms-message/test/test_kms_online_util.c
kms-message/test/test_kms_online_util.h

This adds the API to KMS message for the three new GCP requests (oauth, encrypt, and decrypt) as well as the API for configuring a callback for producing the JWT signature.

MONGOCRYPT-271 add KMS message API for GCP

---

CHANGELOG.md
CMakeLists.txt
etc/generate-kek-tests.py
src/mongocrypt-ctx-datakey.c
src/mongocrypt-ctx-encrypt.c
src/mongocrypt-ctx-private.h
src/mongocrypt-ctx.c
src/mongocrypt-kek-private.h
src/mongocrypt-kek.c
src/mongocrypt-key-broker.c
src/mongocrypt-key-private.h
src/mongocrypt-key.c
src/mongocrypt-kms-ctx.c
src/mongocrypt-opts-private.h
src/mongocrypt-opts.c
src/mongocrypt.c
src/mongocrypt.h.in
test/data/kek-tests.json
test/test-conveniences.c
test/test-conveniences.h
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-setopt.c
test/test-mongocrypt-kek.c
test/test-mongocrypt-key.c
test/test-mongocrypt.c
test/test-mongocrypt.h
test/util/csfle.c

- Adds support for "local" and "aws" to the new API `mongocrypt_setopt_kms_providers` and `mongocrypt_ctx_setopt_key_encryption_key`
- Splits out key encryption key parsing/appending into a separate type, `_mongocrypt_kek_t`

MONGOCRYPT-283 consolidate KEK and KMS provider API

---

.evergreen/config.yml
bindings/java/mongocrypt/.evergreen/test.sh
bindings/java/mongocrypt/README.md
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CAPI.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptImpl.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptOptions.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/SigningRSAESPKCSCallback.java
bindings/java/mongocrypt/src/test/java/com/mongodb/crypt/capi/SigningRSAESPKCSCallbackTest.java

Wrapped:
* mongocrypt_setopt_kms_providers - to support new KMS provider options.
* mongocrypt_ctx_setopt_key_encryption_key - to support new data key options.
* mongocrypt_setopt_crypto_hook_sign_rsaes_pkcs1_v1_5 - to support signature callback for GCP.
MONGOCRYPT-284

MONGOCRYPT-284 Wrapped new api in the Java binding

---

src/mongocrypt.c
test/test-mongocrypt.c

Adds the same check from `mongocrypt_setopt_kms_provider_local` to `mongocrypt_setopt_kms_providers` for the local provider.

add local key length check

---

bindings/python/pymongocrypt/auto_encrypter.py
bindings/python/pymongocrypt/binding.py
bindings/python/pymongocrypt/crypto.py
bindings/python/pymongocrypt/explicit_encrypter.py
bindings/python/pymongocrypt/mongocrypt.py
bindings/python/test/test_crypto.py
bindings/python/test/test_mongocrypt.py

Tested this locally and it works for both Azure and GCP. No changes are needed in PyMongo.
Still working on getting some tests into Evergreen. Testing suggestions for pymongoctypt welcome @ShaneHarvey.

PYTHON-2371 Add Azure and GCP support for CSFLE

---

bindings/python/pymongocrypt/compat.py
bindings/python/pymongocrypt/explicit_encrypter.py
bindings/python/pymongocrypt/mongocrypt.py

I overlooked adding these in #118 
@kevinAlbs I did the best I could to add a brief description for each of these fields. It would be helpful if you could give it a quick read and give your feedback.

PYTHON-2371 Document expected masterKey fields for new KMS providers

---

bindings/python/pymongocrypt/compat.py
bindings/python/pymongocrypt/mongocrypt.py
bindings/python/test/test_mongocrypt.py

Turns out there were some changes needed beyond just adding the testing. These will need to be merged before CI can pass on https://github.com/mongodb/mongo-python-driver/pull/506

PYTHON-2409 Allow local.key KMS provider option to be specified as either bytes or a base64-encoded string

---

bindings/cs/MongoDB.Libmongocrypt/LibraryLoader.cs
bindings/cs/MongoDB.Libmongocrypt/MongoDB.Libmongocrypt.csproj
bindings/cs/MongoDB.Libmongocrypt/MongoDB.Libmongocrypt.targets

https://jira.mongodb.org/browse/CSHARP-3142
Note: changes in .sln file were made because solution wasn't opening in visual studio 2019 and were made automatically.

CSHARP-3142: mongocrypt.dll not present when using mongocsharpdriver in an 'SDK' project

---

.evergreen/config.yml
.evergreen/windows-upload-doit-unstable.json
README.md

I manually uploaded 1.1.0-beta release to https://s3.amazonaws.com/mciuploads/libmongocrypt/windows/latest_release/libmongocrypt_unstable.tar.gz using the AWS CLI. This automates it for future unstable releases, and notes the URL in the README for users.

MONGOCRYPT-291 note unstable URL and update release task

---

cmake/GetVersion.cmake

Running `cmake -P ./cmake/GetVersion.cmake` was returning:
`1.1.0beta1+20201102git80202647fc` though the pre-release tag was `1.1.0-beta1`.
After this change, it has the form `1.1.0-pre2+20201104gitf6765152f6`
This fixes the `publish-packages` tasks.

check for beta in GetVersion.cmake

---

bindings/python/README.rst
bindings/python/pymongocrypt/binding.py
bindings/python/pymongocrypt/version.py

Once merged, I will tag the release on master and push the tag. Bumping version to `1.1.0b1.dev0` will be done in a separate PR.

Release pymongocrypt 1.1.0b0

---

src/mongocrypt.h.in

Documents a typo in the API.
ES = "encryption scheme". SSA = "signature scheme with appendix". Defined in https://tools.ietf.org/html/rfc8017#section-8.2

Document misnamed API for signature callback

---

bindings/node/lib/autoEncrypter.js
bindings/node/lib/clientEncryption.js
bindings/node/lib/cryptoCallbacks.js
bindings/node/lib/stateMachine.js
bindings/node/package.json
bindings/node/src/mongocrypt.cc
bindings/node/src/mongocrypt.h
bindings/node/test/cryptoCallbacks.test.js

This patch set updates the Node.js bindings for libmongocrypt to support Azure and GCP as KMS providers for CSFLE. The changes should be straightforward, following the migration guide for this version of libmongocrypt. Notably, the KMS client code introduced a dependency on `BufferList` in order to simplify the logic of reading in chunks, and forwarding those chunks to libmongocrypt.
NODE-2825

feat: support Azure and GCP KMS providers [node.js]

---

README.md

In preparation for driver beta releases, users will need to obtain the latest unstable libmongocrypt.

Add notes for development packages

---

.evergreen/config.yml

Note that the patch build does not actually exercise this change, since we don't publish for patch builds.  That said, I did perform an additional patch build to verify that the Python venv sequence worked correctly.  However, the curator invocation still failed because the necessary credentials were not available.

MONGOCRYPT-297 fix publish-packages on Debian and Ubuntu

---

bindings/python/.evergreen/test.sh
bindings/python/.evergreen/utils.sh
bindings/python/test-requirements.txt

Use --prefer-binary to prefer older binary packages over newer source packages.
Pin to cffi 1.14.3 on Python 3.4.
This PR fixes the Python 3.4 cffi installation failure on RHEL 6.2:
```
[2020/12/02 15:40:38.595] + /opt/python/3.4/bin/python3 -c 'import sys; print(sys.version)'
--
[2020/12/02 15:40:39.711] running build_ext
[2020/12/02 15:40:39.711] 3.4.10 (default, Oct  6 2020, 00:42:05)
[2020/12/02 15:40:39.711] [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
[2020/12/02 15:40:42.622] + /opt/python/3.4/bin/python3 setup.py test
[2020/12/02 15:40:42.622] WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
[2020/12/02 15:40:44.231] DEPRECATION: Python 3.4 support …
```

PYTHON-2450 Always use a virtualenv to install test dependencies

---

bindings/python/.evergreen/test.sh
bindings/python/.evergreen/utils.sh
bindings/python/setup.py
bindings/python/test-requirements.txt

This PR fixes 3 tickets:
- PYTHON-2368 Test pymongocrypt with Python 3.9 
- PYTHON-2451 Reenable PyPy testing
- PYTHON-2408 Test with cryptography 3
We fixed PyPy testing on RHEL 6.2 by pinning to cryptography<2.9. It also fixes the follow error on macos:
```
[2020/12/04 00:50:38.033] 2.7.17 (default, Dec 23 2019, 21:25:34)
[2020/12/04 00:50:38.033] [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)]
[2020/12/04 00:50:38.034] + python -c 'import sys; print(sys.version)'
[2020/12/04 00:50:38.034] + createvirtualenv python .venv
[2020/12/04 00:50:38.034] + PYTHON=python
[2020/12/04 00:50:38.034] + VENVPATH=.venv
[2020/12/04 00:50:38.136] + python -m virtualenv --version
[2020/12/04 00:50:38.136] + VIRTUALENV='python -m virtualenv'
[2020/12/04 00:50:38.136] + python -m virtualenv …
```

PYTHON-2451 Reenable PyPy testing, add Python 3.9, test cryptography 3

---

src/mongocrypt-kms-ctx.c
src/mongocrypt-status-private.h
src/mongocrypt-status.c
test/test-mongocrypt-crypto-hooks.c

The KMS message crypto hooks (`kms_sha256`, `kms_sha256_hmac`, `kms_sign_rsaes_pkcs1_v1_5`) did not expose an out parameter for an error message, so an error in one of those hooks would be returned as a generic error message through libmongocrypt like `error constructing KMS message`.
The changes here wrap the passed context with a `mongocrypt_status_t` so the error message is returned through libmongocrypt.

MONGOCRYPT-257 propagate errors from KMS message hooks

---

test/fuzz_kms.c

First fuzzer, which will be integrated to be run on oss-fuzz.
Cross referencing:
- mongo-c-driver fuzzers https://github.com/mongodb/mongo-c-driver/pull/706
- OSS-fuzz mongo PR https://github.com/google/oss-fuzz/pull/4808

First fuzzer to be run on oss-fuzz.

---

bindings/node/README.md
bindings/node/index.d.ts
bindings/node/lib/clientEncryption.js
bindings/node/package.json

This PR adds TypeScript definitions to the `mongodb-client-encryption` binding package.
The type definitions were created based on the generated README information from JSDoc as well as going in the source code, as not all comments were entirely precise.
Please have a thorough look.

chore(node-binding): Add initial typings MONGOSH-527

---

kms-message/src/kms_b64.c
kms-message/test/test_kms_request.c
test/util/util.c

The functions that convert regular base64 to url safe base64 terminate their loops on '=' which trims the '=' padding from the final output. While the Azure base64 decoder tolerates the missing padding, python does not accept it and was discovered while testing against a python mock server.
Also fixed a sprintf warning from clang.

MONGOCRYPT-304 Fix base64 URL safe padding

---

src/mongocrypt-kms-ctx.c
src/mongocrypt-opts-private.h
src/mongocrypt-opts.c
src/mongocrypt.c
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt.h

Adds support for passing an AWS session token through to KMS requests.
This includes a unit test to ensure the correct `X-Amz-Security-Token` header is produced. libmongocrypt currently does not run integration tests on Evergreen. MONGOCRYPT-268 added a small command-line utility that uses libmongoc to  run the full state machine. It is not currently built in evergreen. But I used this to run a manual end-to-end test of the session token support with this script: https://gist.github.com/kevinAlbs/e6ba83450427577971beba3c5a417a77

MONGOCRYPT-302 support sessionToken

---

bindings/node/lib/stateMachine.js

TLS endpoints should always be authorized in order to prevent MITM
attacks. In order to properly communicate with GCP's KMS servers
we need to provide a `servername`, so the endpoint can serve the
correct TLS certificate.

fix: always authorize TLS endpoints, use servername for SNI

---

.evergreen/config.yml
kms-message/src/kms_message/kms_response.h

This adds a VS 2015 variant to compile to prevent future regressions.

MONGOCRYPT-307 fix compile on VS 2015

---

bindings/node/index.d.ts

See [NODE-3107](https://jira.mongodb.org/browse/NODE-3107)

chore: add AWS sessionToken TypeScript definitions

---

bindings/python/pymongocrypt/mongocrypt.py
bindings/python/test/test_mongocrypt.py

We already support `sessionToken` since we use `mongocrypt_setopt_kms_providers`. This change verifies that sessionToken can be passed without error.

PYTHON-2539 Ensure sessionToken is supported for temp AWS credentials

---

bindings/node/src/mongocrypt.cc
bindings/node/src/mongocrypt.h

This fixes two places where we weren't cleaning up memory after
creating binary instances
NODE-2985

fix: wrap all mongocrypt_binary_t in smart pointers

---

bindings/node/binding.gyp
bindings/node/lib/autoEncrypter.js
bindings/node/lib/stateMachine.js
bindings/node/package-lock.json
bindings/node/package.json

Automatic client side encryption needs to perform metadata look ups
like listCollections. In situations where the connection pool size
is constrained or in full use it can be impossible for an operation
to proceed. Adding a separate client in these situations permits the
metadata look ups to proceed unblocking operations.
Related to: https://github.com/mongodb/node-mongodb-native/pull/2760

fix(NODE-2995): add metadata client usage

---

bindings/node/.npmignore
bindings/node/package.json

`mongodb-client-encryption@1.2.3` was published with some extraneous files that don't belong in the distribution and this unexpectedly broke the build process of Compass on Windows machines. To avoid something like this in future package releases this PR adds `files` config option to `package.json` file that explicitly specifies which files will make it into the distribution (I asked Neal about what would be the better approach here and he suggested to go with `files` config) and removes `.npmignore` file that is redundant now

fix(NODE-3320): Explicitly provide list of artifacts to be published with package.files

---

bindings/node/src/mongocrypt.cc

See [NODE-3350](https://jira.mongodb.org/browse/NODE-3350)

fix(NODE-3350): do not export Init and helper function symbols

---

src/mongocrypt-ctx-encrypt.c
test/data/collection-info-no-validator.json
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt.c
test/test-mongocrypt.h

**Background**
A `mongocrypt_ctx_t` represents a state machine. The `MONGOCRYPT_CTX_NEEDS_COLLINFO` state signals the driver to send a `{ listCollections: 1}` command to the server and feed the response back to the `mongocrypt_ctx_t`. `listCollections` results may include a JSON schema including metadata about encrypted fields. The state is described in the [integrating guide](https://github.com/mongodb/libmongocrypt/blob/master/integrating.md#state-mongocrypt_ctx_need_mongo_collinfo).
The intended behavior is to cache the response of `listCollections` for one minute to avoid sending repeated `listCollections` commands to the server.
The bug is that the absence of a JSON schema is not cached. That results in repeated `listCollections` commands on collections with no schema from a client …

MONGOCRYPT-317 cache listCollections results with no JSON schema

---

src/mongocrypt-crypto-private.h
src/mongocrypt-crypto.c
src/mongocrypt-ctx-datakey.c
src/mongocrypt-key-broker.c

See MONGOCRYPT-336 for more information. There are no functional changes. This is in preparation of the key wrap / unwrap functions being used by the upcoming KMIP KMS provider.
New task failures on the Debian 9.2, Linux Distro Packaging, and SLES 12 64-bit variants appear due to BUILD-14027.

MONGOCRYPT-336 move key wrap and unwrap functions

---

.evergreen/config.yml

**Background & Motivation**
SLES 12 s390x is no longer a required platform to build.
Removing is required for the 1.3.0 release since the `publish-packages` task depends on the `build-and-test-and-upload` task on the `suse12-s390x` variant to succeed. The task is failing due to the issues noted in BUILD-14027.

MONGOCRYPT-355 remove SLES 12 s390x variant

---

bindings/python/CHANGELOG.rst
bindings/python/pymongocrypt/version.py
bindings/python/release.sh

Bugfix release for decrypting from a memoryview + bundle libmongocrypt 1.2.2 in release wheels.
Testing here: https://spruce.mongodb.com/version/6184705c5623431e8d266012

PYTHON-2909 pymongocrypt 1.1.2

---

bindings/node/index.d.ts
bindings/node/src/mongocrypt.cc
bindings/node/src/mongocrypt.h
bindings/node/test/stateMachine.test.js

Adds Node bindings for KMIP provider support. Bindings now wrap `mongocrypt_kms_ctx_get_kms_provider` and add the typescript definition for the new KMIP provider with a single `endpoint` url.

feat(NODE-3777): add node bindings for kms provider

---

bindings/node/index.d.ts

Adds typescript definitions for allowed TLS options for the KMS provider.

feat(NODE-3781): add tls options for kms providers

---

bindings/node/lib/autoEncrypter.js
bindings/node/test/autoEncrypter.test.js

Increases the value of `serverSelectionTimeoutMS` to the `MongoClient` that the connects to mongocryptd to 10 seconds.

feat(NODE-3177): increase serverSelectionTimeout in client

---

bindings/node/index.d.ts
bindings/node/lib/autoEncrypter.js
bindings/node/lib/clientEncryption.js
bindings/node/lib/stateMachine.js
bindings/node/package-lock.json
bindings/node/package.json
bindings/node/test/stateMachine.test.js

feat(NODE-3633): add Socks5 support

---

bindings/node/test/autoEncrypter.test.js

Increases the test timeout in the node bindings for the auto encrypter tests as the default 2000ms is getting hit before the new server selection timeout is reached.

test(NODE-3777): increase encrypter test timeout

---

bindings/node/index.d.ts
bindings/node/lib/stateMachine.js
bindings/node/test/stateMachine.test.js

- Update the Socks5 options naming to use the connection string
parameter names as keys, rather than shortened variants,
for easier integration into the Node.js driver
- Fix and test username/password authentication (noticed while
addressing the above, this is absolutely my bad)
- [related driver feedback](https://github.com/mongodb/node-mongodb-native/pull/3041#discussion_r772337188)

chore(NODE-3633): update Socks5 support for driver PR feedback

---

.evergreen/build_install_bson.sh
.evergreen/config.yml
.evergreen/linker-tests.sh
.evergreen/pkgconfig-tests.sh
bindings/node/.evergreen/find_cmake.sh

- Add variant named `macos_m1` running on distro `macos-1100-arm64` to run the task `build-and-test-and-upload`.
- Use `/opt/homebrew/bin/cmake` instead of `/Applications/Cmake.app/Contents/bin/cmake`. The former has `arm64` architecture and produces `arm64` builds by default. The latter has `x86_64` architecture and builds with `x86_64` architecture by default. See BUILD-14565.
Bindings tasks, like `build-and-test-node`, `build-and-test-java`, `build-and-test-csharp`, and `test-python` will require further changes. [This Evergreen patch build](https://spruce.mongodb.com/version/61df38b73e8e8655c0380c22) is configured with all tasks and should provide error logs.
The linked patch build includes a failing `build-and-test-node` on Windows 2016. I think it is unrelated to these changes.

MONGOCRYPT-340 add macOS m1 variant

---

bindings/node/index.d.ts
bindings/node/lib/autoEncrypter.js
bindings/node/lib/clientEncryption.js
bindings/node/lib/stateMachine.js
bindings/node/package-lock.json
bindings/node/test/stateMachine.test.js

- Changes the TLS provider options to function per KMS provider. This now ensures each KMS provider can customise their TLS settings.
- Adds validation on the TLS options not to support any insecure options.
Note Prose and spec tests are located in the main Node repo. Related PR https://github.com/mongodb/node-mongodb-native/pull/3070
Node CSFLE run against this specific branch: https://spruce.mongodb.com/version/61e753873066153369a025de/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

feat(NODE-3777): set tls options per kms provider

---

bindings/node/lib/stateMachine.js

The TLS socket used to communicate with the KMS provider is short lived (expected only to last a single KMS request). In testing KMIP support, the Node process retained a handle on the TLS socket even after explicitly ending it. Calling `end()` on a socket only "half-closes" it and this PR explicitly destroys the socket now.

fix(NODE-3777): destroy socket on end

---

bindings/node/README.md
bindings/node/index.d.ts
bindings/node/lib/clientEncryption.js

Consists of just documentation fixes, either type was already allowed due to how our BSON library handles Buffers

docs(NODE-3926): allow either Buffer or Binary in decrypt

---

.evergreen/build_all.sh
.evergreen/build_install_bson.sh
.evergreen/config.yml
.evergreen/linker-tests.sh
.evergreen/pkgconfig-tests.sh
bindings/java/mongocrypt/build.gradle.kts

- Update `macos_m1` builds to build with both x86_64 and arm64 architecture with `-DCMAKE_OSX_ARCHITECTURES='arm64;x86_64'`
- Rename the `macos_m1` variant to `macos_universal`.
The first attempt at using `-DCMAKE_OSX_ARCHITECTURES='arm64;x86_64'` failed on the [macos-1014 distro](https://evergreen.mongodb.com/lobster/evergreen/task/libmongocrypt_macos_build_and_test_universal_mac_patch_03720bce6905a0bc4c3e8fff7bfa5c92f3eb6c14_61f1c49257e85a6a75727184_22_01_26_22_00_50/0/task#bookmarks=0%2C167&l=). That motivated using the `macos-1100-arm64` distro.

MONGOCRYPT-372 make macos M1 builds universal builds

---

bindings/node/test/autoEncrypter.test.js

Fixes test when they run in live mode, will attach link to patch run in driver for proof
[patch](https://spruce.mongodb.com/version/62016c73c9ec446b917b4b5d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[test running and passing here](https://evergreen.mongodb.com/task_log_raw/mongo_node_driver_next_ubuntu1804_custom_dependency_tests_run_custom_csfle_tests_patch_12c6835155c256eefac8fed7bd36c41120731b91_62016c73c9ec446b917b4b5d_22_02_07_19_01_59/0?type=T#L1049)

test: fix incorrect done usage in beforeEach hook

---

CMakeLists.txt
src/mlib/error.h
src/mlib/path.h
src/mlib/path.test.c
src/mlib/str.h
src/mongocrypt-dll-private.h
src/os_posix/os_dll.c
src/os_win/os_dll.c
test/test-dll.cpp
test/test-mongocrypt-dll.c
test/test-mongocrypt.c
test/test-mongocrypt.h

This is a prereq for MONGOCRYPT-373. This introduces private components that can be used to load a dynamic library at runtime. This changes also include tweaks to the mlib path APIs added in #243 
Each commit can be reviewed individually for easier reading.

Dynamic library loading

---

test/test-mongocrypt-ctx-setopt.c

A small followup to #246. Updates to `_mongocrypt_ctx_opts_spec_t` [did not include](https://github.com/mongodb/libmongocrypt/pull/246/commits/97ba5faed3e1213ec79a2a1f06fdb38a9b6c334e) the addition of test cases to corresponding test cases asserting permission or prohibition of the `keyMaterial` field in datakey options in different contexts.

Add keyMaterial to setopt ctx option validity tests

---

bindings/node/index.d.ts
bindings/node/lib/autoEncrypter.js
bindings/node/lib/clientEncryption.js
bindings/node/lib/stateMachine.js
bindings/node/src/mongocrypt.cc
bindings/node/src/mongocrypt.h
bindings/node/test/autoEncrypter.test.js
src/mongocrypt-ctx-datakey.c
src/mongocrypt-ctx-private.h
src/mongocrypt-ctx.c
src/mongocrypt-key-broker-private.h
src/mongocrypt-key-broker.c
src/mongocrypt-kms-ctx-private.h
src/mongocrypt-kms-ctx.c
src/mongocrypt-opts-private.h
src/mongocrypt-opts.c
src/mongocrypt-private.h
src/mongocrypt.c
src/mongocrypt.h.in
test/example-state-machine.c
test/test-mongocrypt-ctx-decrypt.c
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt-datakey.c
test/test-mongocrypt-key-broker.c
test/test-mongocrypt-util.c
test/test-mongocrypt.c
test/util/util.c

~~WIP, no tests yet~~
- Add a function `mongocrypt_setopt_use_need_kms_credentials_state()` to opt into the following features
- Add a new `MONGOCRYPT_CTX_NEED_KMS_CREDENTIALS` state that is always entered before `MONGOCRYPT_CTX_NEED_KMS` if that opt-in has occurred
- Add a function `mongocrypt_ctx_provide_kms_providers()` to set the KMS providers on a per-context basis
- Internally:
- Move the KMS provider settings into their own struct
- Extract associated code from the `_mongocrypt_opts_t` functions into separate functions
- Pass along the per-context KMS provider settings explicitly where they were specified per-context

MONGOCRYPT-382 Add support for providing per-KMS-request credentials

---

bindings/node/test/autoEncrypter.test.js
src/mongocrypt-ctx-datakey.c
src/mongocrypt-ctx.c
src/mongocrypt-opts-private.h
src/mongocrypt-opts.c
src/mongocrypt-private.h
src/mongocrypt.c
src/mongocrypt.h.in
test/test-mongocrypt-ctx-decrypt.c
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt-datakey.c
test/test-mongocrypt.c

https://github.com/mongodb/libmongocrypt/pull/252 introduced a new context state, `MONGOCRYPT_CTX_NEED_KMS_CREDENTIALS`. In the `NEED_KMS_CREDENTIALS` state, `mongocrypt_ctx_provide_kms_providers()` may be called to provide credentials on-demand. This PR is a follow-up to address two caveats:
1. Users are expected to configure `aws: {}` in the KMS providers in the driver to opt into on-demand credentials. libmongocrypt errors on `aws: {}` set in the KMS providers. Drivers need to remove, and remember, if an empty `aws: {}` is configured on the KMS providers.
2. Drivers request aws credentials without needing them in data key contexts. For example: suppose `aws: {}` and `azure` are configured as KMS providers. Calling `createDataKey("azure")` from the driver will result in the …

MONGOCRYPT-382 require `aws: {}` to enter NEED_KMS_CREDENTIALS

---

.evergreen/config.yml
README.md

This makes several changes to support releases of libmongocrypt from a non-master release branch on a separate Evergreen project.
- Update the URLs in upload-all to set `${project}` to "libmongocrypt" and `${branch_name}` to "master". Use `${libmongocrypt_s3_suffix_copy}` of "latest-${branch}" for non-master branch. This avoids breaking workflows for bindings tasks.
- Update the URL in windows-upload to set `${project}` to "libmongocrypt" to avoid breaking workflows for users.
- Modify the libmongocrypt release process to create a branch before tagging. Update the libmongocrypt-release Evergreen project with the new branch.
- Do not run the publish-snapshot task on non-master branches.
Please see [MONGOCRYPT-411 Proposal](https://docs.google.com/document/d/1QTWrK_w6UciKgDR-pQ2BkAT6Ignzs8uN …

MONGOCRYPT-411 Support releases from branches

---

src/mongocrypt.c
src/mongocrypt.h.in
test/test-mongocrypt-ctx-decrypt.c
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt-datakey.c
test/test-mongocrypt.c

Allow an empty document to be set for "azure", "gcp", "local", and "kmip" KMS providers.
[MONGOCRYPT-382](https://jira.mongodb.org/browse/MONGOCRYPT-382) added support to passing credentials on-demand. It was later limited to only the "aws" KMS provider in https://github.com/mongodb/libmongocrypt/pull/257.
It is currently an error to pass an empty document for "azure", "gcp", "local", and "kmip" to `mongocrypt_setopt_kms_providers`.
The proposed driver implementation of on-demand KMS providers intends to permit on-demand credentials for all KMS providers. See the [conversation on this Java driver PR](https://github.com/mongodb/mongo-java-driver/pull/894#discussion_r829232804).

MONGOCRYPT-394 Allow on-demand credentials for KMS providers other than AWS

---

.evergreen/config.yml

This was my mistake in https://github.com/mongodb/libmongocrypt/pull/264.
The [default expansion name](https://github.com/evergreen-ci/evergreen/wiki/Project-Configuration-Files#default-expansions) is `${branch_name}`, not `${branch}`.
This was discovered after doing the `1.3.2-rc0` release.

MONGOCRYPT-411 use ${branch_name}, not ${branch}

---

.evergreen/config.yml

This was my mistake in #264.
The windows-upload task s3.get command was incorrectly updated.
The intended change was to update the s3.put command to make the upload URL consistent with the current upload URL.
This was discovered after doing the 1.3.2-rc1 release. The windows-upload task [failed to run the s3.get command](https://evergreen.mongodb.com/task/libmongocrypt_release_windows_uploader_windows_upload_67105e7aae76f87713debfe3bdd2b4d54702dbc9_22_03_18_21_03_28) because the `remote_file` did not exist.

MONGOCRYPT-411 fix URLs in windows-upload s3 cmds

---

src/mongocrypt-ctx-encrypt.c
src/mongocrypt-ctx-private.h
src/mongocrypt-opts-private.h
src/mongocrypt-opts.c
src/mongocrypt.c
src/mongocrypt.h.in
test/data/encrypted-field-config-map.json
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt.c

- Support a local EncryptedFieldConfigMap (MONGOCRYPT-410)
- Error if a collection is present in both EncryptedFieldConfigMap and SchemaMap.
- Append "encryptionInformation" to command for query analysis and to final command (MONGOCRYPT-404).
https://github.com/markbenvenuto/mongo-enterprise-modules/blob/fle2/fle_protocol.md#walkthrough-insert gives an overview of the FLE 2 interactions.

MONGOCRYPT-410 and MONGOCRYPT-404

---

src/mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-encrypt.c

This resolves a regression introduced in MONGOCRYPT-378. jsonSchema is not appended if there is no encryptedFieldConfig, local jsonSchema, or remote jsonSchema for the collection.
To verify this resolves the test from PYTHON-3188, I ran the test and overrode the path to libmongocrypt with the [PYMONGOCRYPT_LIB environment variable](https://github.com/mongodb/libmongocrypt/blob/master/bindings/python/README.rst#installing-from-source):
```sh
export PYMONGOCRYPT_LIB=/Users/kevin.albertson/code/libmongocrypt-pymongo-M378/cmake-build/libmongocrypt.dylib
python setup.py test --test-suite "test.test_encryption.TestEncryptedBulkWrite"
```
- Append an empty `jsonSchema` document to the command for mongocryptd / csfle if there is no encryptedFieldConfig, local jsonSchema, or remote jsonSchema for …

MONGOCRYPT-378 append empty jsonSchema as fallback

---

debian/gbp.conf

Evergreen patch build: https://spruce.mongodb.com/version/6244c7023066157a6c01e417/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
We apparently had this issue in the C driver about a year ago and somehow I forgot about making the fix here as well.

MONGOCRYPT-413 always use HEAD reference for generating Debian tarball

---

src/mongocrypt-ctx-rewrap-many-datakey.c

This PR fixes a missing vtable entry on transition directly to the `MONGOCRYPT_CTX_READY` state during rewrapManyDataKey when the set of KEKs to rewrap do not require KMS for KEK encryption (all already use, or are rewrapped to use, a local provider). The state machine indicates the client should invoke `mongocrypt_ctx_finalize` but does not set the appropriate `finalize` vtable function, leading to an unexpected "not applicable to context" error.

Fix missing vtable entry for MONGOCRYPT_CTX_READY state during rewrapManyDataKey

---

src/mongocrypt-ctx-rewrap-many-datakey.c

This PR fixes the incorrect assumption that every KMS provider requires only a _single_ round of KMS requests for encryption during rewrapManyDataKey, which is not the case for Azure or GCP providers. This PR introduces a check that reiterates over the list of datakey contexts after a call to `mongocrypt_ctx_kms_done` during encryption and remains in the `MONGOCRYPT_CTX_NEED_KMS` state if any datakey contexts still require KMS requests for encryption.

Support multiple rounds of KMS encryption requests for rewrapManyDataKey

---

src/mongocrypt-ctx-decrypt.c
src/mongocrypt-ctx-private.h
src/mongocrypt.h.in
test/test-mongocrypt-ctx-decrypt.c

- Have `mongocrypt_ctx_explicit_decrypt_init` call `mongocrypt_ctx_decrypt_init`.
- Test explicit decryption of `FLE2IndexedEqualityEncryptedValue` payload.
This simplifies decryption with the new FLE 2 payloads. Explicit decryption support is implied by automatic decryption support.
`mongocrypt_ctx_explicit_decrypt_init` already required the input `msg` to be a BSON document like: `{ "v" : (BSON BINARY value of subtype 6) }`. Decryption would unwrap the value of "v", then rewrap it in finalize. Unwrapping and rewrapping seems unnecessary. Explicit decryption seems like an unnecessary special case as implemented.

MONGOCRYPT-419 Consolidate explicit and automatic decryption

---

debian/changelog

This PR cherry-picks onto master the commits for the 1.4.0 Debian packaging.

libmongocrypt 1.4.0 Debian packaging

---

src/mongocrypt-buffer.c
src/mongocrypt-ctx-encrypt.c

This fixes a few issues encountered during csfle integration in mongo-c-driver:
- Failing to create the command will destroy an invalid `cslfe_status` object.
- UBSan catches a memcpy(d, NULL, 0)`, which is "benign" in most cases but still warns and is UB.
- The `$db` property should only be inserted if it isn't already a part of the command document. (Otherwise `csfle` errors because of a duplicate `$db`.)
- `csfle` doesn't report any errors on destruction, so attempting to check for errors will just log the most-recent error, which is irrelevant to the destruction process.

Runtime UB and csfle analysis fixes

---

bindings/node/lib/autoEncrypter.js
bindings/node/src/mongocrypt.cc
bindings/node/test/autoEncrypter.test.js

Specifically, pass a default `csfleSearchPaths` list of `['$SYSTEM']`,
and add support for `csfleRequired`.
As drive-by fixes, fix a typo that currently (unintentionally) leads to
`_mongocryptdClient` and `_mongocryptdManager` being initialized even
if `bypassAutoEncryption` was specified, and adjust the tests and the
`.teardown()` method for those cases.
Typings changes: https://github.com/mongodb/node-mongodb-native/pull/3206

feat(NODE-4136): adjust Node.js bindings for shared library spec

---

src/mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-encrypt.c

- Do not skip the `MONGOCRYPT_CTX_NEED_MONGO_COLLINFO` state when the `bypass_query_analysis` option is true.
If the target collection has an associated `encrypted_field_config`, it must be appended to the outgoing command with `_fle2_append_encryptionInformation`. The server uses the `encrypted_field_config` to process FLE 2 payloads.
The `MONGOCRYPT_CTX_NEED_MONGO_COLLINFO` state requests the driver to run `listCollections`. It is used to obtain a server-side `$jsonSchema` (for FLE 1 `schema`) or a server-side `encryptedFields` (for FLE 2 `encrypted_field_config`).

Do not skip NEED_MONGO_COLLINFO state with bypass_query_analysis

---

src/mongocrypt-crypto-private.h
src/mongocrypt-crypto.c
src/mongocrypt.c
src/mongocrypt.h.in
test/test-mongocrypt-crypto-hooks.c

This implements `mongocrypt_setopt_aes_256_ctr` function to supply user AES-CTR crypto functions
Some changes are generated by clang-format

MONGOCRYPT-395 Implement crypto callback for AES with CTR mode

---

src/mongocrypt-ctx-compact.c
src/mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-compact.c
test/test-mongocrypt-ctx-encrypt.c

- Set final compact context state to `MONGOCRYPT_CTX_DONE` or `MONGOCRYPT_CTX_ERROR`.
- Bypass the `compactStructuredEncryptionData` command from automatic encryption.
Both bugs were caught in integration testing.

Fix compact context terminal state and bypass

---

bindings/node/test/autoEncrypter.test.js

Loosening the test error message checking to instead assert we raise a subclass of our own error classes. The test is failing due to DNS configuration of the system. We don't want to add the DNS case to the filter that generates the "helpful" message the test refers to since it wouldn't be helpful to be told to ensure mongocryptd is in the path when the real issue is an incorrect mongocryptdURI.
It is blocking the adoption of new nodejs versions in the CI for the driver.

test: loosen test error assertion for fails to autospawn

---

bindings/node/lib/autoEncrypter.js
bindings/node/lib/cryptoCallbacks.js
bindings/node/lib/stateMachine.js
bindings/node/src/mongocrypt.cc

This is required for FLE2 support. Diff best viewed with whitespace changes hidden because it moves a function to an outer scope :)
(drive by, can be a separate PR if necessary)
This is required because `encryptedFields.fields[].queries[].contention`
must be a Long in order for the server/mongocryptd/the csfle
shared library to be able to process it.

feat(NODE-4218): add aes256-ctr support

---

src/mongocrypt.h.in

Add to `mongocrypt_ctx_provide_kms_providers`.

MONGOCRYPT-428 add missing MONGOCRYPT_EXPORT

---

bindings/python/pymongocrypt/binding.py
bindings/python/pymongocrypt/crypto.py
bindings/python/pymongocrypt/mongocrypt.py
bindings/python/pymongocrypt/version.py
bindings/python/test/data/compact/success/cmd.json
bindings/python/test/data/compact/success/encrypted-field-config-map.json
bindings/python/test/data/compact/success/encrypted-payload.json
bindings/python/test/data/encrypted-field-config-map.json
bindings/python/test/data/keys/12345678123498761234123456789012-local-document.json
bindings/python/test/data/keys/12345678123498761234123456789013-local-document.json
bindings/python/test/data/keys/ABCDEFAB123498761234123456789012-local-document.json
bindings/python/test/test_mongocrypt.py

3 changes:
- Bump _MIN_LIBMONGOCRYPT_VERSION to 1.5.0a1 and update binding header.
- [PYTHON-3241](https://jira.mongodb.org/browse/PYTHON-3241) Add mongocrypt_setopt_aes_256_ctr crypto callbacks
- [PYTHON-3241](https://jira.mongodb.org/browse/PYTHON-3241) Add support for encrypted_fields_map and bypass_query_analysis
I believe this is everything needed for FLE 2.0 support in pymongocrypt itself.

PYTHON-3241 FLE 2.0 support for pymongocrypt

---

bindings/python/test/data/collection-info.json
bindings/python/test/data/mongocryptd-command.json
bindings/python/test/data/schema-map.json
bindings/python/test/test_mongocrypt.py
etc/generate-test-data.py
test/data/collinfo-siblings.json
test/data/schema-map.json
test/data/schema.json

https://jira.mongodb.org/browse/PYTHON-3269
A few changes to make the mock test jsonSchemas valid according to the server's format:
- wrap "keyId" in an array
- rename "type" to "bsonType"
- rename "AEAD_AES_CBC_HMAC_SHA512" to "AEAD_AES_256_CBC_HMAC_SHA_512".
Note that this PR only changes the C and Python files, other bindings should to make similar changes on their own.

PYTHON-3269 Fix malformed mock jsonSchemas used in test suite

---

src/mongocrypt-ctx-encrypt.c
test/data/fle1-explain/with-csfle/cmd.json
test/data/fle1-explain/with-csfle/collinfo.json
test/data/fle1-explain/with-csfle/encrypted-payload.json
test/data/fle1-explain/with-mongocryptd/cmd-to-mongocryptd.json
test/data/fle1-explain/with-mongocryptd/cmd.json
test/data/fle1-explain/with-mongocryptd/collinfo.json
test/data/fle1-explain/with-mongocryptd/encrypted-payload.json
test/data/fle1-explain/with-mongocryptd/mongocryptd-reply.json
test/data/fle2-explain/with-csfle/cmd.json
test/data/fle2-explain/with-csfle/collinfo.json
test/data/fle2-explain/with-csfle/encrypted-payload.json
test/data/fle2-explain/with-mongocryptd/cmd-to-mongocryptd.json
test/data/fle2-explain/with-mongocryptd/cmd.json
test/data/fle2-explain/with-mongocryptd/collinfo.json
test/data/fle2-explain/with-mongocryptd/encrypted-payload.json
test/data/fle2-explain/with-mongocryptd/mongocryptd-reply.json
test/test-mongocrypt-ctx-encrypt.c

- Fix handling of the `explain` command for FLE 2.
- Append "encryptionInformation" in correct location.
- Strip "encryptionInformation" nested inside `explain`.
- Fix handling of the `explain` command for FLE 1 with `csfle`
- Use command database name for value of "$db".
- Append "$db" nested inside `explain`.
Integration tests were run in the C driver locally with both mongocryptd and csfle, and [on Evergreen here](https://spruce.mongodb.com/version/627ff0030ae6067da396c836/changes?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
These are the expectations of "explain" for csfle and mongocryptd found through experimenting.
mongocryptd and csfle expect "jsonSchema" as a sibling of "explain". Example:
```js
{
"explain": {
"find": "foo",
"$db": "db" // Required by csfle. Prohibited by …
```

MONGOCRYPT-427 Fix explain

---

kms-message/src/kms_request.c

We are seeing:
```
kms/kms_request.c:240:10: warning: ISO C does not support '__FUNCTION__' predefined identifier [-Wpedantic]
```

Fix for ISO C warning

---

CMakeLists.txt
kms-message/src/kms_response_parser.c
src/mongocrypt-ctx-encrypt.c
src/mongocrypt-ctx.c
src/mongocrypt-log.c
src/mongocrypt-marking.c
src/mongocrypt-traverse-util.c
test/example-state-machine.c
test/test-mongocrypt.c

Fixes MONGOCRYPT-430
A bogus value for `queryType` would break invariants of the encryption context. Instead, catch that early and return an error.

Ensure we handle all enums in a switch and have a default case

---

src/mongocrypt-ctx-encrypt.c
test/data/dollardb/omitted/cmd-to-mongocryptd.json
test/data/dollardb/omitted/cmd.json
test/data/dollardb/omitted/collinfo.json
test/data/dollardb/omitted/encrypted-payload.json
test/data/dollardb/omitted/mongocryptd-reply.json
test/data/dollardb/preserved/cmd-to-mongocryptd.json
test/data/dollardb/preserved/cmd.json
test/data/dollardb/preserved/collinfo.json
test/data/dollardb/preserved/encrypted-payload.json
test/data/dollardb/preserved/mongocryptd-reply.json
test/data/dollardb/preserved_empty/cmd-to-mongocryptd.json
test/data/dollardb/preserved_empty/cmd.json
test/data/dollardb/preserved_empty/collinfo.json
test/data/dollardb/preserved_empty/encrypted-payload.json
test/data/dollardb/preserved_empty/mongocryptd-reply.json
test/data/dollardb/preserved_fle1/cmd-to-mongocryptd.json
test/data/dollardb/preserved_fle1/cmd.json
test/data/dollardb/preserved_fle1/collinfo.json
test/data/dollardb/preserved_fle1/encrypted-payload.json
test/data/dollardb/preserved_fle1/mongocryptd-reply.json
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt.h

- If $db is included in the input command, preserve it in the output command.
- If $db is not included in the input command, do not add it to the output command.
- Always omit the $db to the command for mongocryptd.
C# expects $db to be on the command after encryption. This was done by [injecting $db into the response from mongocryptd](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs#L268-L278). That is no longer possible when using the `csfle` shared library. The `MONGOCRYPT_CTX_NEED_MONGO_MARKINGS` state is not entered for `csfle`.
Other drivers append $db to the command after encryption. See [Do drivers append $db before or after encryption](https://docs.google.com/spreadsheets/d/18O6cfAQKC3OIUMW4_prWnpaLBMDh-lm …

MONGOCRYPT-431 Preserve $db

---

bindings/node/lib/autoEncrypter.js
bindings/node/test/autoEncrypter.test.js
bindings/node/test/data/encrypted-document-nested.json

Handle cases in which the decrypted values are documents/arrays
in the devtools-specific decrypted-reponse marking.
This was previously untested because it’s quite a bit of effort
to generate new mock data (like the one added in this commit)
for the current test setup, but obviously that was a mistake.

fix(NODE-4279): handle decrypted nested documents well with devtools decoration

---

bindings/node/index.d.ts

Otherwise this was picking up `Document` from the HTML spec (if that was enabled in the relevant TS config).

fix: add missing import in Node.js bindings TS definitions

---

src/mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-encrypt.c

- Do not run ismaster check of mongocryptd if bypassing query analysis
MONGOCRYPT-429 added logic to run an `isMaster` command on mongocryptd when automatically encrypting the `create` and `createIndexes` command. The `create` and `createIndexes` commands are only supported on mongocryptd >= 6.0.0-rc5. The `isMaster` check is used to determine if mongocryptd supports `create` and `createIndexes`.
If query analysis is bypassed is set, a context expected not to enter the `MONGOCRYPT_CTX_NEED_MONGO_MARKINGS` state.
This change is validated with a C driver specification test here: https://github.com/mongodb/mongo-c-driver/pull/1023

MONGOCRYPT-435 do not run ismaster check if bypassing query analysis

---

bindings/python/.evergreen/test.sh
bindings/python/test/test_mongocrypt.py

The changes in https://github.com/mongodb/libmongocrypt/pull/352 caused the shared library tests to silently be skipped. This change fixes that and makes it less likely to happen in the future by adding the TEST_CRYPT_SHARED=1 env var. When TEST_CRYPT_SHARED=1 is set the test suite fails if crypt_shared cannot be loaded.

PYTHON-3287 Reenable shared library testing

---

CMakeLists.txt
README.md
bindings/python/pymongocrypt/binding.py
bindings/python/strip_header.py
src/mongocrypt-config.h.in
src/mongocrypt.h

The only reason we generate `mongocrypt.h` at configure-time is to generate the `MONGOCRYPT_VERSION` macro string. Since we are already doing configure-time generation of `mongocrypt-config.h`, it is easier to just move the version macro into that file, which is already `#include`d by `mongocrypt.h`.

Make mongocrypt.h a non-generated header

---

src/crypto/commoncrypto.c
test/test-mongocrypt-ctx-encrypt.c

- Add message to errors for unsupported CTR mode.
- Add string of CCCryptorStatus to errors.
Please see MONGOCRYPT-440 for Background & Motivation.
The list of error enums is taken from [CommonCryptoError.h on macOS 10.14](https://github.com/apple-oss-distributions/CommonCrypto/blob/878937e469969b56fa2d356a7af6a1420a555d5d/include/CommonCryptoError.h).

MONGOCRYPT-440 clarify error for unsupported CTR mode.

---

bindings/cs/MongoDB.Libmongocrypt/CryptClient.cs
bindings/cs/MongoDB.Libmongocrypt/Library.cs
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CAPI.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptImpl.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoExplicitEncryptOptions.java
bindings/node/lib/clientEncryption.js
bindings/node/src/mongocrypt.cc
bindings/python/pymongocrypt/binding.py
bindings/python/pymongocrypt/explicit_encrypter.py
bindings/python/pymongocrypt/mongocrypt.py
bindings/python/test/test_mongocrypt.py
src/mongocrypt-ctx-encrypt.c
src/mongocrypt-ctx-private.h
src/mongocrypt-ctx.c
src/mongocrypt.h
test/example-state-machine.c
test/test-mongocrypt-crypto-hooks.c
test/test-mongocrypt-ctx-decrypt.c
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-setopt.c

There are several commits in this changeset, and each can be read alone.
This change has two important facets:
- Allow passing `"Indexed"` and `"Unindexed"` as the algorithm string to `setopt_algorithm`. This mimics the user-facing API and allows drivers to be forwards-compatible in the face of new "index types."
- Change `setopt_query_type` to accepta a string for the `query_type` instead of an enumerator. (Implements [DRIVERS-2352](https://jira.mongodb.org/browse/DRIVERS-2352))

[MONGOCRYPT-441] Accept string arguments for queryType and "index_type"

---

bindings/node/index.d.ts
bindings/node/test/clientEncryption.test.js

MONGOCRYPT-441 has no impact besides updating `equality` to
be spelled lowercase.

chore(NODE-4304): accept string value for queryType

---

cmake/ImportBSON.cmake

Currently, building the imported libmongoc library generates the following error message:
```
warning: Configure the driver with ENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF. Automatic cleanup is deprecated and will be removed in version 2.0. [-W#pragma-messages]
```
This PR disables `ENABLE_AUTOMATIC_INIT_AND_CLEANUP` by default when building the imported libmongoc library to silence this warning. (Note: we may also want to consider changing this default value in the C driver CMake configuration from `ON` to `OFF` if able, given how many users are having to go out of their way to explicit disable it.)

Disable ENABLE_AUTOMATIC_INIT_AND_CLEANUP by default

---

bindings/python/test/test_mongocrypt.py
src/mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-setopt.c

- Require contention factor for indexed algorithm with explicit encryption
The server plans to support increasing the contention factor in the future. If libmongocrypt uses the fixed default value 4, that may risk the default client and server contention factors going out of sync.
This PR proposes making the contention factor a required client option for explicit encryption. The contention factor can be made optional later, if there is a way for explicit encryption to get the server default.

MONGOCRYPT-447 require contention factor for indexed algorithm

---

src/mongocrypt.h

Followup to MONGOCRYPT-450; improves the documentation of `mongocrypt_ctx_finalize()` to more accurately describe the structure of the resulting value.

MONGOCRYPT-450 Update documentation of mongocrypt_ctx_finalize

---

bindings/node/index.d.ts
bindings/node/lib/clientEncryption.js
bindings/node/test/clientEncryption.test.js

See the ticket description. Since edb12c6b54602f68abe has already
been merged, this is required in order for rewrapManyDatakey
(as it would otherwise inadvertently destroy key information when run).
Do not perform a bulk write if no keys are being updated.

fix(NODE-4356): update rewrapManyDataKey to use UpdateOne bulk ops

---

bindings/node/lib/common.js

Switch the `name` property of `MongoCryptError` to a getter in order to avoid the property setting errors caused by bulk write errors in the Node driver.

fix(NODE-4260): mongocrypterror has name getter

---

bindings/node/index.d.ts
bindings/node/lib/clientEncryption.js
bindings/node/src/mongocrypt.cc
bindings/node/test/clientEncryption.test.js
bindings/node/test/cryptoCallbacks.test.js

This PR removes the usage of indexKeyId in the Node bindings.
From DRIVERS-2348:
Queryable Encryption has two keys per field: the UserKey and IndexKey.
The UserKey encrypts user data.
The IndexKey is used to derive tokens for indexing.
libmongocrypt assumes IndexKeyId == UserKeyId when only the UserKeyId is specified.
IndexKeyId is must must match the "keyId" in encryptedFields for correct query results.
After discussing with Mark Benvenuto, Seny Kamara, Kenneth White, Cynthia Braund, the decision is not to add the IndexKeyId to EncryptOpts for these reasons:
We do not need to support the use-case where IndexKeyId != UserKeyId.
Adding IndexKeyId increases risk that a user sets an incorrect IndexKeyId.

fix(NODE-4339): remove indexKeyId

---

.evergreen/config.yml
README.md

The main goal with this change, as the PR title suggests, is to upload to a URL based on the tag name for release tags.  Note that this is in addition to the normal uploads based on the commit hash and that existing uploads and upload locations were deliberately left undisturbed.  A separate ticket (MONGOCRYPT-437) will deal with necessary adjustments to the existing upload locations.
These changes cannot be effectively observed in a patch build, so you will have to consult the `upload-all` task in the last two builds on the waterfall of the special Evergreen project:
https://evergreen.mongodb.com/waterfall/libmongocrypt-feature
The only difference between the aggregate changes on the feature branch used for the special Evergreen project and this PR is that the line
```
head_tag=$(git tag …
```

MONGOCRYPT-315 upload tagged releases to a URL containing the tag name

---

bindings/node/test/clientEncryption.test.js
bindings/node/test/cryptoCallbacks.test.js

`contentionFactor` must now be provided when encrypting as indexed. This updates the prose tests and extra unit test to provide it. See https://github.com/mongodb/specifications/commit/41b335af92c12258a4cbe7e93ad4f34ef31641a7

test(NODE-4343): contention factor required with indexed

---

.evergreen/build_all.sh
.evergreen/linker-tests.sh
.evergreen/pkgconfig-tests.sh
.evergreen/setup-env.sh

Make respects a `MAKEFLAGS` environment variable to specify additional command-line flags. It's possible to specify flags to the build executor to `cmake --build`, but we don't have a guarantee that `cmake --build` will actually be running Make. Setting `MAKEFLAGS` will give arguments to Make if it happens to be the build executor.
This change shaves off several minutes for most Linux and macOS tasks.

Set MAKEFLAGS to provide compilation parallelism

---

.evergreen/find-cmake.sh
bindings/node/.evergreen/find_cmake.sh
bindings/node/.evergreen/setup_environment.sh

commit ec2403e3e1cb3e362b178acc352626d8af28ed40 updated the Node bindings CI scripts to use the shared find-cmake script, but this change unintentionally broke the Node driver's CSFLE tests.
Updating the cmake path didn't resolve all the issues, we now have build issues with our bindings (see example patch https://spruce.mongodb.com/version/62c5df0c0305b96e4b828a82/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).  Rather than investigate this issue right now, I want to revert this change until it can be made and properly tested before merging.
The Node driver also has CSFLE work in-flight that is impacted by a broken CI, so we should either fix it quickly or just revert for now.

Revert "Node bindings should re-use top-level find-cmake.sh (#395)"

---

cmake/GetVersion.cmake

Followup to https://github.com/mongodb/libmongocrypt/pull/406 as requested.

Fix CMake GUI config errors due to external working directory (#406)

---

.evergreen/config.yml

Evergreen patch build: https://spruce.mongodb.com/version/62d09cffd1fe075d969e38e6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Before/after comparison of file artifacts associated with the `upload-all` task:
Before: https://mciuploads.s3.amazonaws.com/libmongocrypt/all/master/b14d06000535e55be0c619e936972805cac24d37/libmongocrypt-all.tar.gz
After: https://mciuploads.s3.amazonaws.com/libmongocrypt/all/master/4ac9be9c8cca65d2a0a0e7c069f4701db981cdf1/62d09cffd1fe075d969e38e6/libmongocrypt-all.tar.gz
Before: https://mciuploads.s3.amazonaws.com/libmongocrypt/all/master/latest/libmongocrypt-all.tar.gz
After: https://mciuploads.s3.amazonaws.com/libmongocrypt/all/master/latest/62d09cffd1fe075d969e38e6/libmongocrypt-all.tar.gz
(note that the 'After' URLs are from the patch build, so they also …

MONGOCRYPT-437 remove hard-coded branch names in Evergreen s3.put targets

---

bindings/node/README.md
bindings/node/test/clientEncryption.test.js

In https://github.com/mongodb/libmongocrypt/pull/414, I updated the URI in the clientEncryption tests to use authentication because I saw errors locally.  This causes CI in the driver to fail.  Upon investigation, my initial changes weren't necessary.  I mistakenly tested locally with a standalone server with auth enabled, but the tests connect to a standalone without auth.  The connection succeeds, but the `drop` command fails because auth is enabled on the standalone.  I mistakenly interpreted the error "command 'drop' requires authentication" to mean authentication was required to run any drop command, and updated the URI.
This PR reverts that change to fix the driver tests.

chore: revert change to uri in node binding tests

---

src/mongocrypt-ctx-datakey.c
src/mongocrypt-key-broker.c
src/mongocrypt-opts-private.h
src/mongocrypt-opts.c
src/mongocrypt.c
test/test-gcp-auth.c
test/test-mongocrypt.c

- Support `accessToken` for `gcp` KMS provider.
This change is intended to enable drivers to pass an `accessToken` for `gcp` on-demand.
The expected behavior is:
- User configures `kmsProviders` with `gcp: {}` to have the driver fetch `gcp` credentials.
- When in the state `MONGOCRYPT_CTX_NEED_KMS_CREDENTIALS`, the driver obtains an `accessToken` and passes to libmongocrypt with `mongocrypt_provide_kms_providers`.
- The driver obtains an `accessToken` by sending an HTTP request to the GCP Metadata Server, noted in [AIP-4115](https://google.aip.dev/auth/4115).
The `accessToken` passed in `mongocrypt_provide_kms_providers` is not cached in `crypt->cache_oauth_gcp`. The `MONGOCRYPT_CTX_NEED_KMS_CREDENTIALS` state is always entered before `mongocrypt_ctx_t` may reach out to KMS. The …

MONGOCRYPT-461 Support `accessToken` for `gcp` KMS provider

---

bindings/java/mongocrypt/src/test/java/com/mongodb/crypt/capi/MongoCryptTest.java
bindings/python/test/test_mongocrypt.py
kms-message/src/kms_request.c
kms-message/test/test_kms_request.c
kms-message/test/test_kms_util.c
kms-message/test/test_kms_util.h

- Use `\r\n`, not `\n`, as the end-of-line delimitter in HTTP requests.
The Go driver integration tests were run with this branch in a [patch build](https://spruce.mongodb.com/version/62e16a0c3e8e8618242ec912/) to test sending KMS requests to live services.

MONGOCRYPT-457 Use CRLF instead of LF newlines

---

.evergreen/build_all.sh
.evergreen/clang-tidy.sh
.evergreen/compile.sh
.evergreen/compile_cs.sh
.evergreen/config.yml
.evergreen/create-packages-and-repos.sh
.evergreen/debian_package_build.sh
.evergreen/find-cmake.sh
.evergreen/linker-tests.sh
.evergreen/pkgconfig-tests.sh
.evergreen/prep_c_driver_source.sh
.evergreen/setup-env.sh
README.md

This changeset ensures most of the build shell scripts execute cleanly in Bash with "strict mode." Several environment variables used by the scripts are given default empty values in `setup-env.sh`. The "create packages" script was moved out-of-line from `config.yml` and placed in a dedicated file to allow for braced shell substitutions without EVG expansions interfering. The behavior of the scripts is otherwise unchanged.

Make all shell scripts nounset-clean, enable "strict mode"

---

src/mongocrypt-kms-ctx.c
test/data/kms-tests.json
test/test-mongocrypt-kms-responses.c

- Return HTTP body in KMS error replies.
- Update `kms-tests.json` test runner
- Test non-oauth GCP and Azure requests.
- Support array of strings for "expect".
When parsing an HTTP reply from a KMS, libmongocrypt makes incorrect assumptions about the returned JSON body.
For example: creating a data key for the "gcp" KMS provider with an incorrect `masterKey.location` results in a `mongocrypt_status_t` with the message: `Error in KMS response '', code: '0'. HTTP status=404`.
The full reply body is:
```json
{
"error": {
"code": 404,
"message": "The request concerns location 'foobar' but was sent to location 'global'. Either Cloud KMS is not available in 'invalid' or the request was misrouted. gRPC clients must ensure that 'x-goog-request-params' is specified in request metadata. See …
```

MONGOCRYPT-306 Return HTTP body in KMS error replies

---

src/mongocrypt-kms-ctx.c
test/test-mongocrypt.c

Fixes the following always-true assertion in `mongocrypt_kms_ctx_get_kms_provider`, which context suggests should have been an always-_false_ assertion.
```
warning: implicit conversion turns string literal into bool: 'char [25]' to 'bool' [-Wstring-conversion]
BSON_ASSERT ("unknown KMS request type");
~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
As a drive-by fix, also addresses the same warning in `_mongocrypt_tester_mongocrypt`, though this instance appears to have the correct behavior.
```
warning: implicit conversion turns string literal into bool: 'char [109]' to 'bool' [-Wstring-conversion]
!"tester mongocrypt requested WITH_CRYPT_SHARED_LIB, but no "
~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Address -Wstring-conversion warnings in assertions

---

src/mongocrypt-kms-ctx.c

- add "Invalid KMS response" to error parsing GCP access token.
Drivers expect the substring "Invalid KMS response" error message in the "Custom Endpoint" [prose test 9](https://github.com/mongodb/specifications/tree/b63ea83e782b1fe2081ff0ad38bd088525396f41/source/client-side-encryption/tests#test-cases). This was not considered when implementing MONGOCRYPT-306. Rather than require all drivers update tests, add the string back to the error message.
MONGOCRYPT-306 changed an [error message](https://github.com/mongodb/libmongocrypt/pull/422/files#diff-1d46e573cbccf1b7d005fcee4face95abca81c6e5c39355da793252fd1170eadL577).

MONGOCRYPT-306 add "Invalid KMS response" to error.

---

bindings/node/README.md
bindings/node/etc/README.hbs
bindings/node/index.d.ts
bindings/node/lib/clientEncryption.js

NODE-4517 (part of NODE-4443)
This PR removes experimental tags from the key management API in preparation for the release of mongodb-client-encryption@2.2.0.
It also adds a doc comment for rewrapManyDataKey.

feat(NODE-4517): add official support for the key management API

---

src/mongocrypt-ctx-encrypt.c
test/data/fle1-collMod/cmd-to-mongocryptd.json
test/data/fle1-collMod/cmd.json
test/data/fle1-collMod/insert/cmd.json
test/data/fle1-collMod/insert/collinfo.json
test/data/fle1-collMod/mongocryptd-reply.json
test/test-mongocrypt-ctx-encrypt.c

- Check the `collMod` command for `validator.$jsonSchema` and send it to query analysis.
Since MONGOCRYPT-429, automatic encryption has supported the `collMod` command. Prior to MONGOCRYPT-429, it was always an error to automatically encrypt a `collMod` command. A `collMod` command is not bypassed because it may include sensitive plaintext in a `validator` field:
```json
{
"collMod": "encryptedCollection",
"validator": {
"encryptedField": "plaintext",
}
}
```
A `collMod` command may also include a `validator.$jsonSchema`:
```json
{
"collMod": "encryptedCollection",
"validator": {
"$jsonSchema": {
"encryptedField": {
"encrypt": {
"bsonType": "string",
"algorithm": "AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic",
"keyId": {
"$binary": {
"base64": "AAAAAAAAAAAAAAAAAAAAAA==",
"subType": "04"
} …
```

MONGOCRYPT-463 check the `collMod` command for `validator.$jsonSchema`

---

bindings/python/README.rst

Added a few words to point most users away from this path.

Make it clear most users don't need libmongocrypt

---

bindings/node/lib/autoEncrypter.js
bindings/node/lib/clientEncryption.js
bindings/node/package-lock.json
bindings/node/package.json
bindings/node/test/autoEncrypter.test.js
bindings/node/test/clientEncryption.test.js
bindings/node/test/stateMachine.test.js

This updates the Node bindings to first attempt to use the exported `BSON` from the `mongodb` module before falling back to the old behaviour. This means that:
- Driver 4.9.0 and higher will use the exported `BSON` from the driver itself.
- Driver 4.x before 4.9.0 and driver 3.x will continue to use the `bson` object passed in the options or on `client.topology`
This allows driver 4.9.0 and higher to not need a connected client to be able to user csfle.
Main of the Node driver is now pinning on the latest commit in this PR and passing, running all live tests: https://spruce.mongodb.com/task/mongo_node_driver_next_ubuntu1804_custom_dependency_tests_run_custom_csfle_tests_latest_pinned_commit_40d485c292a14f8251a4e3724d1bb5f8cf11577c_22_08_17_20_53_00/tests?execution=0&sortBy=STATUS&sortDir=A …

fix(NODE-4556): attempt to use exported BSON

---

src/mongocrypt-ctx-datakey.c
src/mongocrypt-key-broker.c
src/mongocrypt-opts-private.h
src/mongocrypt-opts.c
src/mongocrypt.c
test/test-mongocrypt.c

Refer: MONGOCRYPT-473
This changeset adds support for `{ azure: { accessToken: 'abc' } }` to be specified as a KMS provider. This will bypass the logic that attempts to obtain an access token from Azure and instead uses the given token directly. This is required to support Automatic KMS for Azure, as drivers need to be able to provide the automatically-obtained access token to libmongocrypt directly.

[MONGOCRYPT-473] Support "accessToken" as an Azure KMS option

---

CMakeLists.txt
src/mlib/str.h
src/mongocrypt-ctx.c
test/test-mongocrypt-ctx-setopt.c

- Support case-insensitive values for "algorithm" and "queryType"
- Add `mstr_eq_ignore_case`
This is a goal in [DBX Scope: Driver Support for Range Index](https://docs.google.com/document/d/1kkiqr91-HPpr0lDCm1lDVWSvRCuDKKGgdmwYgi2OA7A/edit), requested by product management.

MONGOCRYPT-484 Support case-insensitive values for "algorithm" and "queryType"

---

src/crypto/cng.c
src/crypto/commoncrypto.c
src/crypto/libcrypto.c

This is mean to preview the proposed sorts of changes in a subset of the code-base.  Assuming this looks good to everyone, I will proceed with similar changes under the `src/` directory (excepting examples and tests).
Evergreen patch build: https://spruce.mongodb.com/version/6317a41030661513b86bf30a/tasks?limit=100&page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

MONGOCRYPT-469 improved and more consistent null pointer checks

---

.evergreen/config.yml

One could also use the preferred "-C" argument, but we use older versions of Git that may not yet support that option.
This fixes main-project build breakages following merge of #453

When executing git, we must be in a repository.

---

src/mc-fle2-encryption-placeholder-private.h
src/mc-fle2-encryption-placeholder.c
src/mc-fle2-insert-update-payload-private.h
src/mc-range-mincover-private.h
src/mc-range-mincover.c
src/mongocrypt-marking.c
test/data/fle2-insert-range/int32/mongocryptd-reply.json
test/data/fle2-insert-range/int64/mongocryptd-reply.json
test/data/range-min-cover/mincover_int32.cstruct
test/data/range-min-cover/mincover_int64.cstruct
test/test-mc-range-mincover.c
test/test-mongocrypt-ctx-encrypt.c

- Update range placeholder payloads to match https://github.com/mongodb/mongo/commit/241b350350eca6eddbc36f036ce824b8e75df0a5#diff-d854f7244c2c241eb65c905ebc150c8e8f5f44ba3d5ca2ac89ca0efd944dc8cf.
- Update fields in `getMincoverInt{32,64}_args_t`.
This PR does not fully resolve MONGOCRYPT-478.
https://github.com/mongodb/mongo/commit/241b350350eca6eddbc36f036ce824b8e75df0a5#diff-d854f7244c2c241eb65c905ebc150c8e8f5f44ba3d5ca2ac89ca0efd944dc8cf made several changes to the existing payloads:
- FLE2RangeSpec is renamed to FLE2RangeFindSpec.
- FLE2RangeSpec has new indexMin/indexMax fields.
- The terms min/max now refer to the index bounds. lowerBound/upperBound refers to the query bounds.
- sparsity is now int64_t.
Test data was updated by printing output from server unit tests: …

MONGOCRYPT-478 update payloads and terms

---

CMakeLists.txt
src/mc-fle-blob-subtype-private.h
src/mc-fle2-payload-iev-private.h
src/mc-fle2-payload-iev.c
src/mongocrypt-ctx-decrypt.c
src/mongocrypt-traverse-util.c
test/test-mc-fle2-payload-iev.c
test/test-mongocrypt-ctx-decrypt.c

- Rename `mc_FLE2IndexedEqualityEncryptedValue_t` to `mc_FLE2IndexedEncryptedValue_t`.
- Support decryption of `FLE2RangeIndexedValue`.
`FLE2RangeIndexedValue` shares a common data layout with `FLE2IndexedEqualityEncryptedValue`. The additional data is not needed by libmongocrypt to decrypt.
This PR renames of `mc_FLE2IndexedEqualityEncryptedValue_t` to `mc_FLE2IndexedEncryptedValue_t` to support decrypting both payloads.

MONGOCRYPT-479 Decrypt the new FLE2RangeIndexedValue

---

bindings/node/index.d.ts
bindings/node/lib/autoEncrypter.js
bindings/node/lib/clientEncryption.js
bindings/node/src/mongocrypt.cc
bindings/node/test/autoEncrypter.test.js
bindings/node/test/clientEncryption.test.js

Decided to expose this both on `AutoEncrypter` and `ClientEncryption` for now, but happy to move it to another place altogether if there’s a strong preference.

feat(NODE-4328): expose libmongocrypt version in bindings

---

bindings/python/pymongocrypt/mongocrypt.py
bindings/python/release.sh
bindings/python/setup.py
bindings/python/test/data/key-document-gcp.json
bindings/python/test/data/kms-reply-gcp.txt
bindings/python/test/test_mongocrypt.py

Integration tests are in https://github.com/mongodb/mongo-python-driver/pull/1064

PYTHON-3367 Add support for GCP attached service accounts when using GCP KMS

---

src/mongocrypt-ctx.c
test/test-mongocrypt-ctx-encrypt.c

- Update error returns in `mongocrypt_ctx_provide_kms_providers` to set the `ctx->state` to `MONGOCRYPT_CTX_ERROR`
An error in a context function is expected to set the state of the context as `MONGOCRYPT_CTX_ERROR`. Some drivers require this behavior for correctness. For example, the Node.JS bindings [do not always check the return values](https://github.com/mongodb/libmongocrypt/blob/400167e2092036babd2f000b13a0c87f5503442f/bindings/node/src/mongocrypt.cc#L822) of some `mongocrypt_ctx_*` functions, and may rely on the [context state to return an error](https://github.com/mongodb/libmongocrypt/blob/400167e2092036babd2f000b13a0c87f5503442f/bindings/node/lib/stateMachine.js#L230).

MONGOCRYPT-488 set context error state in provide_kms_providers

---

.evergreen/config.yml
bindings/node/.evergreen/setup_environment.sh
bindings/node/.evergreen/test.sh
bindings/node/etc/build-static.sh
bindings/node/index.d.ts
bindings/node/lib/autoEncrypter.js
bindings/node/lib/clientEncryption.js
bindings/node/lib/credentialsProvider.js
bindings/node/package-lock.json
bindings/node/package.json
bindings/node/test/autoEncrypter.test.js
bindings/node/test/credentialsProvider.test.js
bindings/node/test/release.test.js

Allows the state machine to load kms provider credentials from the environment for AWS.
- Adds the @aws-sdk/credential-providers module as an optional dependency.
- Will attempt to load missing credentials if user does not supply their own refresh function.
- Deprecates the `onKmsProviderRefresh` option. See: https://jira.mongodb.org/browse/NODE-4731
- Changes evergreen config to run both with and without the optional dependency.

feat(NODE-4234): add aws credentials provider

---

src/mongocrypt-util.c
src/os_posix/os_dll.c

FreeBSD is not an officially support platform, but it supports the runtime library extensions sufficient that we can implement the SO module querying functions on it.
These changes have been built and verified in FreeBSD 13.

[MONGOCRYPT-470] Support SO path queries on FreeBSD

---

.evergreen/config.yml
bindings/node/.evergreen/setup_environment.sh

On Oct 25, 2022, Node LTS "Hydrogen" 18 went active, and this changed the major version downloaded by `nvm {use,install} --lts`. The new Node binaries have a runtime-link dependency on some newer versions of glibc symbols that are not available on older Linux distros under test. The downloaded `node` executable can not be launched on these older systems, confusing `nvm` and preventing the CI from running properly.
This changeset pins the older build variants to download the prior LTS release (16.x).

ci(NODE-4779): Pin to an earlier Node LTS release on platforms that are not supported by prebuilt Node 18+

---

.evergreen/config.yml

Now that SUSE15 hosts are spawning, I realized that I missed one variant in #488. Oops, that's embarrassing.

ci(NODE-4779): Missing Pin of Node 16 on SUSE15 Variant

---

src/mongocrypt-ctx-datakey.c
src/mongocrypt-ctx.c
test/test-gcp-auth.c
test/test-mongocrypt-ctx-setopt.c
test/test-mongocrypt.c

These changes will raise an error and not create a datakey when the datakay uses a different KMs provider than the initial KMS provider configured in `mongocrypt_setopt_kms_providers`. There are two added tests: one with a configured KMS provider and one with KMS provider that needs credential (when it is configured with an empty object).

MONGOCRYPT-492 Add check if datakey provider and the initial KMS provider set match

---

src/mongocrypt-ctx-encrypt.c
src/mongocrypt-ctx-private.h
src/mongocrypt-ctx.c
src/mongocrypt.h
test/data/fle2-find-range/date/encrypted-field-map.json
test/data/fle2-find-range/date/encrypted-payload.json
test/data/fle2-find-range/date/mongocryptd-reply.json
test/data/fle2-find-range/double/encrypted-field-map.json
test/data/fle2-find-range/double/encrypted-payload.json
test/data/fle2-find-range/double/mongocryptd-reply.json
test/data/fle2-find-range/int32/encrypted-field-map.json
test/data/fle2-find-range/int32/encrypted-payload.json
test/data/fle2-find-range/int32/mongocryptd-reply.json
test/data/fle2-find-range/int64/encrypted-field-map.json
test/data/fle2-find-range/int64/encrypted-payload.json
test/data/fle2-find-range/int64/mongocryptd-reply.json
test/data/fle2-insert-range/date/encrypted-field-map.json
test/data/fle2-insert-range/date/encrypted-payload.json
test/data/fle2-insert-range/date/mongocryptd-reply.json
test/data/fle2-insert-range/double/encrypted-field-map.json
test/data/fle2-insert-range/double/encrypted-payload.json
test/data/fle2-insert-range/double/mongocryptd-reply.json
test/data/fle2-insert-range/int32/encrypted-field-map.json
test/data/fle2-insert-range/int32/encrypted-payload.json
test/data/fle2-insert-range/int32/mongocryptd-reply.json
test/data/fle2-insert-range/int64/encrypted-field-map.json
test/data/fle2-insert-range/int64/encrypted-payload.json
test/data/fle2-insert-range/int64/mongocryptd-reply.json
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-setopt.c

- Rename queryType and algorithm from "range" to "rangePreview"
The `encryptedFields` in the server now expects the string `rangePreview`: https://github.com/mongodb/mongo/commit/484eee157ecc039fafbbef6a4aae0286c8bbc3b5#diff-64f7154b6f37606f91956209094c8cc9005f11ee48d8f54210a65cbb8bd102b8R56
It is expected to change back to "range" once the feature is stabilized.

MONGOCRYPT-494 rename queryType and algorithm from "range" to "rangePreview"

---

.evergreen/config.yml
README.md
etc/packager.py
etc/repo_config.yaml

Evergreen patch build: https://spruce.mongodb.com/version/6384eb75850e615387a38ee9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Note that the `build-and-test-csharp` task is failing on Ubuntu 22.04.  I have communicated with @DmitryLukyanov about this and we concluded that it would best for me to go ahead with this PR and let the C# team address the failing task when it makes sense for the team's priorities.

MONGOCRYPT-446 add build variant and package publications for Debian 11 and Ubuntu 22.04

---

.evergreen/config.yml
src/mc-range-encoding.c
src/mongocrypt-marking.c
src/mongocrypt-util-private.h
src/mongocrypt-util.c

- Add helpers to ignore conversion warnings for `isinf`, `isnan`, and `isfinite`
- Add variant to test clang 7.0.1 with Ubuntu 18.04
Conversion errors [were observed](https://spruce.mongodb.com/task/libmongocrypt_ubuntu1804_64_clang7_build_and_test_and_upload_patch_6bbbee8aa1b0ae6c46b4ed30d03f2016a3e03114_63866519850e6110e8bb51c7_22_11_29_20_01_30/logs?execution=0) on Ubuntu 18.04 with clang 7.0.1:
```
/opt/mongodbtoolchain/v3/bin/clang -DBSON_STATIC -DKMS_MSG_STATIC -DMLIB_HAVE_STRINGS_H -DMLIB_USER -DMONGOCRYPT_LITTLE_ENDIAN -DMONGOCRYPT_STATIC_DEFINE -I/data/mci/59ac622bce7b889019af64f1728d4e55/libmongocrypt/kms-message/src -I/data/mci/59ac622bce7b889019af64f1728d4e55/libmongocrypt/src -I/data/mci/59ac622bce7b889019af64f1728d4e55/libmongocrypt/cmake-build/src …
```

MONGOCRYPT-501 fix conversion warning on clang 7 with glibc

---

.evergreen/config.yml

No patch build since it wouldn't show anything; the `publish-packages` task is skipped for patch builds.
The cause of the failure seems to be that I somehow failed to sync the build variant definitions.  While the artifacts are actually built in `build-*` tasks on the target platform (Ubuntu 22.04 in this case), we need the packaging task to run Ubuntu 20.04 because we reuse the server's `packager.py` script and it apparently fails with the newer Python in Ubuntu 22.04.  This change takes the Ubuntu 22.04 amd64 variant (which has the failing task) and applies to it the same pattern I used for the Ubuntu 22.04 arm64 variant (which I somehow figured out during development).

MONGOCRYPT-503 fix publish-packages on Ubuntu 22.04 build variant

---

.evergreen/config.yml
bindings/node/.evergreen/setup_environment.sh

This PR pins the Node CI the Node 18 (the current latest LTS node version).  It also makes two other small changes (see the notes sections below).
A requirement of the ticket is that we make sure our release will be pinned to Node16 since they build on rhel7.  This was already addressed and can be confirmed in the config.yml (see [here](https://github.com/mongodb/libmongocrypt/blob/4a520d7cccee09d3d4ce4cec207701f31e050c7e/.evergreen/config.yml#L1130)).
Note: you may see failing socks5 tests on the CI.  These tests are also failing on libmongocrypt master occasionally.
https://github.com/mongodb/libmongocrypt/commit/216f7854cbee5dbd9247099b6db88c38d9d2c53c added debian and ubuntu22 support but did not add `build-and-test-node-no-optional-dependencies` to the new variants.  This PR adds the …

ci(NODE-4666): pin to node18 instead of latest

---

src/mc-tokens-private.h
src/mc-tokens.c
test/test-mc-tokens.c

Server needs to be able to construct a libmongocrypt token `mc_ServerDataEncryptionLevel1Token_t` from a server token (i.e. `mongo::ServerDataEncryptionLevel1Token`). We use a raw buffer for this but let the server own the buffer rather then deep copy it in this case.
Feel free to suggest a better name.

MONGOCRYPT-506 Extend token API for server needs

---

bindings/node/.eslintrc.json
bindings/node/lib/autoEncrypter.js
bindings/node/lib/mongocryptdManager.js
bindings/node/test/autoEncrypter.test.js

Node18 changed the default dns resolution ordering from "ipv4 always first" to "returned in the order that the dns resolver returns them in".  This breaks some environments that use mongocryptd, since by default mongocryptd does not listen on ipv6 addresses.
There are workarounds
- configure mongocryptd to listen on ipv6 addresses
- specify a `mongocryptdURI` that uses `127.0.0.1` instead of `localhost`
- set the resolution globally on the node process
But none of these are ideal for customers or for driver CI.
This PR adds logic to force the driver to use ipv4 addresses when no `mongocryptdURI` is specified.
Driver CI task successfully passing with these changes - https://spruce.mongodb.com/version/639752c0c9ec447a54d40daa/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC.

fix(NODE-4880): specify family of ipv4 when connecting to default mongocryptd uri

---

.evergreen/config.yml
bindings/java/mongocrypt/build.gradle.kts

- Remove `rhel-67-s390x` variant.
- Replace `rhel-67-s390x` with `rhel72-zseries-test` in Java tasks.
Building on RHEL 6.7 on S390X adds difficulty for upgrading cmake. Upgrading cmake may be helpful for integrating the Intel Decimal Floating-Point Math Library library as part of MONGOCRYPT-483.
The latest documented server version to support RHEL 6 on S390X is MongoDB Server 4.2.17. Automatic encryption needs mongocryptd or the crypt_shared library on the same machine as the application. So it is already not possible to do automatic encryption with version > 4.2.17 of mongocryptd / crypt_shared.
RHEL 6 is End of life (EOL). Redhat does not support it any longer. Server does not support RHEL 6 for MongoDB 5.0 or later.

MONGOCRYPT-513 Drop RHEL 6.7 on S390X

---

kms-message/src/kms_port.h

The build system in the server is different than the libmongocrypt build system. This is leading to the following error:
```src/third_party/libmongocrypt/dist/kms-message/src/kms_request.c:371:16: warning: call to undeclared function 'strcasecmp'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
0 == kms_strcasecmp (previous_key->str, kv->key->str)) {
^
src/third_party/libmongocrypt/dist/kms-message/src/kms_port.h:29:24: note: expanded from macro 'kms_strcasecmp'
#define kms_strcasecmp strcasecmp
^
```

MONGOCRYPT-511 Fix missing strings.h header in kms_port.h

---

CMakeLists.txt
src/mlib/int128.h
src/mlib/int128.test.c
src/mlib/int128.test.cpp
src/mlib/macros.h
src/mlib/str.h

This changeset adds a new trivial type `mlib_int128`, which presents a method of performing 128-bit binary arithmetic. This is a prerequesite to MONGOCRYPT-483, which requires 128-bit integers and integer arithmetic.
Some platforms, such as 64-bit GCC, provide an `__int128` abstraction, but other platforms do not. MSVC and all 32-bit targets do not have such extensions. For this reason, this PR implements 128-bit arithmetic using only standard C99.
Usage looks like this:
- `mlib_int128` a typedef of a trivial type that occupies 16 bytes of storage. There is no distinction between signed/unsigned: Operations that depend on sign (for now, just integer comparison) require specifying whether you want a signed compare or an unsigned compare.
- `MLIB_INT128(N)` a macro that creates a 128-bit …

MONGOCRYPT-483: A 128-bit integer abstraction

---

src/mongocrypt-kms-ctx.c

- Include KMS error in libmongocrypt status.
KMS message reports errors with the `kms_request_get_error` function.
C# tests got [this error](https://evergreen.mongodb.com/test_log/dot_net_driver_tests_zlib_compression_posix__version~4.2_os~ubuntu_1804_topology~standalone_auth~noauth_ssl~nossl_compressor~zlib_test_netstandard20_6a203a450f97af76bcba73ea0815170bf63aa2a8_22_12_01_22_59_28/0?test_name=7dd4a46e3db12d370732f583af2d313c&group_id=&text=true): `failed to create KMS message` with no additional information.

MONGOCRYPT-514 check more KMS errors

---

cmake/ImportBSON.cmake

- Disable snappy on C driver build
This resolves the currently failing [build-and-test-and-upload](https://evergreen.mongodb.com/task/libmongocrypt_macos_build_and_test_and_upload_8d6d64f0d8461e6f088bd6d9d1af10bfd32a0bfd_23_01_02_22_27_58) task:
```
[2023/01/02 22:28:47.588] [354/399] Linking C executable csfle
[2023/01/02 22:28:47.588] FAILED: csfle
[2023/01/02 22:28:47.588] : && /Applications/Xcode13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -O2 -g -DNDEBUG -arch arm64 -arch x86_64 -isysroot /Applications/Xcode13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/csfle.dir/test/util/csfle.c.o …
```

Disable snappy on C driver build

---

test/test-mongocrypt-crypto.c

Some `status` objects were being leaked by duplicate `status = mongocrypt_status_new ()` assignments.

Address leaks in test-mongocrypt-crypto.c

---

.evergreen/config.yml
src/mlib/endian.h
src/mlib/int128.test.cpp

- Add `rhel83-zseries-small` distro to run C++ tests on big endian architecture.
- Fix int128 tests on big endian.
- Add debug prints to int128 tests.
Running tests on RHEL 8.3 zSeries in the C driver shows a test failure:
https://spruce.mongodb.com/task/mongo_c_driver_zseries_rhel83_debug_compile_sasl_openssl_cse_patch_a8560d7488778e480b7c61a0f8931ddbcc310c7d_63c6d3472fbabe0efe2f7708_23_01_17_16_56_40/logs?execution=0
```
[2023/01/17 16:59:25.279] num=27828649044156246570177174673037165454 den=499242349997913298655486252455941907 expect.quotient=0 expect.remainder27828649044156246570177174673037165454
[2023/01/17 16:59:25.279] /data/mci/14145729f69a17cdf3e60d1356dda1b7/mongoc/libmongocrypt/src/mlib/int128.test.cpp:203: CHECK( expect.quotient == res.quotient ) failed!
[2023/01/17 …
```

MONGOCRYPT-483 fix int128 test on big endian

---

.evergreen/build_all.sh

- add `LIBMONGOCRYPT_BUILD_TYPE` option to make `CMAKE_BUILD_TYPE` configurable.
This is motivated by updating libmongocrypt to support decimal128 Range Index CDRIVER-4394.
The C driver currently builds libmongocrypt by invoking `cmake` directly in `compile-unix.sh` and `compile-windows.sh`. Here is the [snippet from compile-windows.sh](https://github.com/mongodb/mongo-c-driver/blob/9e18dd1b08591242a4da33be1f55f3a33c629d07/.evergreen/compile-windows.sh#L125-L130):
```bash
git clone --depth=1 https://github.com/mongodb/libmongocrypt --branch 1.7.0-alpha1
mkdir libmongocrypt/cmake-build
cd libmongocrypt/cmake-build
"$CMAKE" -G "$CC" "-DCMAKE_PREFIX_PATH=${INSTALL_DIR}/lib/cmake" -DENABLE_SHARED_BSON=ON -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" ../
"$CMAKE" --build . --target INSTALL --config …
```

MONGOCRYPT-483 make `CMAKE_BUILD_TYPE` configurable.

---

src/csfle-markup.cpp

Using GCC 13 (Fedora 38) the build is failing
```
/builddir/build/BUILD/libmongocrypt-1.6.2/src/csfle-markup.cpp: In function 'int {anonymous}::do_main(int, const char* const*)':
/builddir/build/BUILD/libmongocrypt-1.6.2/src/csfle-markup.cpp:201:24: error: 'uint32_t' in namespace 'std' does not name a type; did you mean 'wint_t'?
201 |       static_cast<std::uint32_t> (strlen (doc_ns)),
|                        ^~~~~~~~
|                        wint_t
```
See https://gcc.gnu.org/gcc-13/porting_to.html

MONGOCRYPT-518 add missing header for GCC 13

---

bindings/node/lib/autoEncrypter.js
bindings/node/lib/clientEncryption.js
bindings/node/lib/stateMachine.js
bindings/node/test/stateMachine.test.js

Node driver v5 removes callback support so we needed to update `createDataKey` and `markCommand` to use the promise API.
This included searches through the codebase for all CRUD methods - all other usage already uses async await or promises.
Patch build on the Node driver pointing at this commit: https://spruce.mongodb.com/version/63cac4515623431af90fd308/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

fix(NODE-4987): node csfle uses promises instead of callbacks

---

CMakeLists.txt
cmake/IntelDFP.cmake
src/mc-dec128.h

This will ensure that we get the proper function references, regardless of where DFP comes from.

Reuse the proper DFP names from bid_conf.h

---

src/mongocrypt-ctx-encrypt.c
src/mongocrypt-private.h

- wrap errors from processing crypt_shared markings
`_mongo_feed_markings` and `_mongo_done_markings` set an error on the context on failure. The original error is currently overwritten. Attempting to run a Range Index test in Go using libmongocrypt 1.6.0 results in the following error reported from libmongocrypt:
```
unified_spec_test.go:337: 
Error Trace:    /Users/kevin.albertson/code/mongo-go-driver-G2433/mongo/integration/unified_spec_test.go:337
/Users/kevin.albertson/code/mongo-go-driver-G2433/mongo/integration/mongotest.go:263
Error:          Expected nil, but got: &errors.errorString{s:"did not expect error but got mongocrypt error 1: Consuming the generated csfle markings failed"}
Test:           TestClientSideEncryptionSpec/fle2-Range-Date-Aggregate.json/FLE2_Range_Date._Aggrega …
```

MONGOCRYPT-519 wrap errors from processing crypt_shared markings

---

bindings/node/README.md
bindings/node/index.d.ts
bindings/node/lib/clientEncryption.js
bindings/node/lib/common.js
bindings/node/lib/credentialsProvider.js
bindings/node/lib/stateMachine.js
bindings/node/src/mongocrypt.cc
bindings/node/test/clientEncryption.test.js
bindings/node/test/common.test.js

This PR adds range index support in explicit encryption.
Changes included
- ClientEncryption.encrypt() logic was refactored to a private helper to be shared between encrypt() and encryptExpression()
- A new option, expressionMode, is passed down from _encrypt() into the bindings.  This toggles whether or not we are encrypting an expression or a regular bson value.
- maybeCallback was copied into the bindings
- documentation was generated

feat(NODE-4694): support range indexes

---

bindings/node/src/mongocrypt.cc

`strncasecmp` is not present in Windows so we redefine it in those environments.

fix(NODE-4997): no strncasecmp on windows

---

.evergreen/config.yml

MONGOCRYPT-315 added an upload URL for the libmongocrypt-all.tar.gz of the form: `https://mciuploads.s3.amazonaws.com/libmongocrypt/all/<tag>/libmongocrypt-all.tar.gz`
The [1.7.0 upload-all task](https://spruce.mongodb.com/task/libmongocrypt_release_publish_snapshot_upload_all_a29f4d35d974e0ec32dd48cd57fba197873cf68e_23_01_20_22_08_03/files?execution=0&sortBy=STATUS&sortDir=ASC) does not have the expected tagged URL upload.
The [1.6.0 upload-all task](https://spruce.mongodb.com/task/libmongocrypt_release_publish_snapshot_upload_all_e78460cfbac270dc5e26b61c6b4355e6b9e9e460_22_12_06_17_32_15/files?execution=0) has the tagged URL upload.
The `expansions.update` command expects `tag_expansion.yml` spelling. https://github.com/mongodb/libmongocrypt/pull/465 changed the spelling from …

MONGOCRYPT-520 fix tag upload

---

.earthlyignore
.evergreen/earthly.sh
.evergreen/ensure-cmake.sh
.evergreen/ensure-ninja.sh
Earthfile
etc/c6-vault.repo
etc/install-package.sh

I've been using a variation of this for local dev on most projects for a long time. Unlike the prior mongo-c-driver PR with the same purpose, this one is far simpler and trimmed down.
This does not modify CI or introduce any new EVG tasks. Perhaps in the future? For now, it's just useful for local dev. It only defines a target that runs `build_all.sh`, and does not export any artifacts. Adding new tasks and artifacts may be a task for the future.

Add a Basic Earthly File

---

bindings/node/test/release.test.js

Sometimes this test times out in the before hook running npm pack. Takes around ~600ms for me locally but sometimes on CI it takes over 2s. This moves the default timeout to 5s on that test.
https://spruce.mongodb.com/version/63d284791e2d177b176053f5/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

test(NODE-4897): bump release test timeout

---

src/mongocrypt-kms-ctx.c
test/data/kms-tests.json

- do not assert on base64 decode error
Without the fix, `./cmake-build/test-mongocrypt _test_kms_responses` results in the assert:
```
- Encryption response with invalid base64
/Users/kevin.albertson/code/libmongocrypt-M525/src/mongocrypt-kms-ctx.c:590 _ctx_done_aws(): precondition failed: result_len >= 0
```

MONGOCRYPT-525 do not assert on base64 decode error

---

.evergreen/config.yml
.evergreen/debian_package_build.sh
Earthfile
src/mc-range-edge-generation-private.h

This fixes a confusion about the data model available on certain platforms.
This changeset also defines an additional `debian-package-build-i386` task that will validate this platform going forward. We also now have an Earthly target for the deb-build, and the changes were validated there (using `earthly --platform=i386 +deb-build`).

[MONGOCRYPT-524] Fix ILP32-target builds

---

.evergreen/config.yml
Earthfile
cmake/IntelDFP.cmake
etc/rpm/tweak.awk

This PR adds a new EVG task to the "Linux Distro Packaging" group that builds an RPM using Fedora Rawhide, based on the same RPM spec that is used in the upstream. This will be the first Earthly-based task running in EVG.
This changeset also caught an accidental new built-time dependency on Git that wasn't listed in the upstream `libmongocrypt.spec`. I hope that this will allow us to preempt RPM-related build issues in the future, before merging errant changesets.
Tweaks:
- Don't BuildRequires git, and just use 'patch' on the IntelDFP sources if possible.
- Only install exactly what is requried by BuildRequires for creating the RPM, to detect accidental new build dependencies.
(I note that the Docker availability and stability in the EVG distros isn't entirely stable, but I have narrowed …

Define a new EVG task that runs the RPM build

---

cmake/IntelDFP.cmake

value taken from RPM %{ix86} definition
```
$ rpm --eval %{ix86}
i386 i486 i586 i686 pentium3 pentium4 athlon geode
```

MONGOCRYPT-532 Fix i686 (32-bit) build

---

cmake/ImportBSON.cmake
src/mc-fle2-payload-iev.c

Addresses the following error when compiling with `-DENABLE_MONGOC=OFF`:
```
CMake Error at cmake/ImportBSON.cmake:153 (target_include_directories):
Cannot specify include directories for target "mongoc_static" which is not
built by this project.
Call Stack (most recent call first):
cmake/ImportBSON.cmake:162 (_import_bson)
CMakeLists.txt:22 (include)
```
The conditional presence of `mongoc_static` is already being handled correctly further below in ImportBSON.cmake:
```cmake
if (TARGET mongoc_static)
add_library (_mongocrypt::mongoc ALIAS mongoc_static)
endif ()
```
As a drive-by fix, also addresses a -Wtautological-compare warning in mc-fle2-payload-iev.c which may hinder compilation from source by the C Driver.

Permit -DENABLE_MONGOC=OFF when compiling libmongocrypt

---

bindings/node/lib/credentialsProvider.js
bindings/node/test/credentialsProvider.test.js
bindings/node/test/index.test.js

We strictly check for an existing object but with zero keys for a kmsProviders credentials before attempting auto fetching.
Yes, this could be surprising to existing AWS users that were able to leave kmsProviders empty. They need to provide an 'aws' key set to `{}`
The kmsProviders settings needs to have a key that exists but is set to an empty object in order to enable auto obtaining credentials. Otherwise future credential providers will both be obtained without actually requesting it.

fix(NODE-5053): enforce empty map for kmsProvider auto credentials

---

CMakeLists.txt
cmake/ImportDFP.cmake
cmake/IntelDFP.cmake
src/mc-dec128.h
src/mc-dec128.test.cpp
src/mc-optional-private.h
src/mc-range-edge-generation-private.h
src/mc-range-edge-generation.c
src/mc-range-encoding-private.h
src/mc-range-encoding.c
src/mc-range-mincover-private.h
src/mc-range-mincover.c
src/mc-rangeopts.c
src/mongocrypt-marking.c
test/test-mc-range-edge-generation.c
test/test-mc-range-encoding.c
test/test-mc-range-mincover.c
test/test-mongocrypt-ctx-encrypt.c

The configure-time option `MONGOCRYPT_ENABLE_DECIMAL128` can be used to enable/disable Decimal128 range support. This is enabled by default.
- Wrap Decimal128 code in conditions on whether Decimal128 is available.
- Only supports IntelDFP for now.

[MONGOCRYPT-536] A Toggle for Decimal128 Range Support

---

.evergreen/build_all.sh

Reduces verbosity of build output when compiling libmongocrypt. If xtrace is desirable, users invoking build_all.sh (directly or indirectly via compile.sh) can opt into enabling xtrace themselves by setting `set -o xtrace` before invoking `build_all.sh`.

Remove xtrace in build_all.sh

---

bindings/node/.evergreen/test.sh
bindings/node/lib/credentialsProvider.js
bindings/node/package-lock.json
bindings/node/package.json
bindings/node/test/credentialsProvider.test.js
bindings/node/test/requirements.helper.js

NODE-4462
- Added `gcp-metadata` dependency as peer optional
- If `gcp: {}` is an empty map we will auto fetch credentials
- added a simulated test, int tests will be in driver NODE-5050

feat(NODE-5049): add support for kms gcp service accounts

---

bindings/node/index.d.ts
bindings/node/test/types/index.test-d.ts

- Add empty credentials as a viable type for aws/gcp
currently empty credentials raise a TS error

feat(NODE-5066): add automatic credential usage to TS definitions

---

src/mc-tokens-private.h
src/mc-tokens.c
test/test-mc-tokens.c

This defines and adds derivation functions for the following v2 token types:
* `ServerTokenDerivationLevel1Token = HMAC(indexKey, 2)`
* `ServerDerivedFromDataToken = HMAC(ServerTokenDerivationLevel1Token, value)`
Only `ServerDerivedFromDataToken` will really be used in the v2 payloads. `ServerTokenDerivationLevel1Token` is just an intermediate type used for deriving the `ServerDerivedFromDataToken`.

MONGOCRYPT-540 Define QE v2 token types and implemente token derivation

---

src/mongocrypt-ctx-encrypt.c

- add missing destroy and context fail on error
- remove unnecessary `bson_init`

MONGOCRYPT-554 fix cleanup in `_fle2_finalize` error case

---

bindings/node/README.md
bindings/node/lib/providers/azure.js
bindings/node/lib/providers/index.js
bindings/node/lib/providers/utils.js

This PR fixes tsdoc comment issues preventing the docs from generating, as well as generates the docs to include documentation for azure kms automatic credential refresh.

docs(NODE-5094): fix docs for azure kms credential refresh

---

bindings/node/.evergreen/install-dependencies.sh

Other repos that use this script run npm install after installing Node.js. We can't in mongodb-client-encryption, because when releasing npm install will attempt to build from source, which fails because we haven't built libmongocrypt yet (build-static.sh).

ci(NODE-5131): remove npm install in node download script

---

bindings/node/test/cryptoCallbacks.test.js

The CTR cipher test fails on the driver repo running the crypto callbacks tests because QEv2 no longer uses the CTR cipher mode and uses CBC instead - so the stub isn't called and no expected error gets propagated.

test(NODE-5179): remove ctr cipher tests

---

bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CAPI.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptImpl.java
bindings/java/mongocrypt/src/test/java/com/mongodb/crypt/capi/MongoCryptTest.java

Temporarily disable unit test until data files are updated
JAVA-4891
Driver patch build: https://spruce.mongodb.com/version/642de10157e85afa5de9e619/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

Java: Update payloads to new QE protocol

---

src/mongocrypt-buffer.c

Resolves MONGOCRYPT-568. See ticket for details. Verified by [this patch](https://spruce.mongodb.com/version/642f09242a60ed79889f29d9).
For consistency with other `mongocrypt_buffer_t` copy functions such as [_mongocrypt_buffer_copy_to](https://github.com/mongodb/libmongocrypt/blob/9dc3f6cefef442fea41c1f2f186c03a31477ea90/src/mongocrypt-buffer.c#L215), opted to allow `buf->data == NULL` rather than asserting a non-zero length.
Note: `mongocrypt_buffer_t` functions do not seem to be consistent with asserting what the value of `buf->owned` should be given `buf->data == NULL` (e.g. [_make_owned](https://github.com/mongodb/libmongocrypt/blob/9dc3f6cefef442fea41c1f2f186c03a31477ea90/src/mongocrypt-buffer.c#L28) allows `buf->data == NULL && buf->owned`, but …

MONGOCRYPT-568 Avoid calling memcpy with NULL argument in _mongocrypt_buffer_copy_from_data_and_size

---

CMakeLists.txt
cmake/Platform.cmake
cmake/mongocrypt-config.cmake

`mongocrypt::platform` is an `INTERFACE` library that defines usage requirements related to platform features and dependencies on system libraries. When a library links to a libmongocrypt library, it will transitively link to `mongocrypt::platform`, which will propagate usage requirements required for consuming libmongocrypt (e.g. runtime support libraries)

Define a mongocrypt::platform target for platform requirements

---

.evergreen/config.yml
.lsan-suppressions

- remove trailing newline in `compile_env` to fix leak detection
The trailing newline in `compile_env` results in the `env` command run separately in the [`build and test` function](https://github.com/mongodb/libmongocrypt/blob/master/.evergreen/config.yml#L76-L78). This results in the [environment variables being printed](https://parsley.mongodb.com/evergreen/libmongocrypt_ubuntu1804_64_build_and_test_asan_50eaa4b9da767d817710d7e8612b15f1b1b9f2d4_23_04_17_21_26_57/0/task?bookmarks=0,5271&shareLine=59) instead of applying the `compile_env` to the environment.
This patch includes a leak to verify leak detection is working: https://spruce.mongodb.com/version/644045600ae6068d54cab675
After enabling, ASAN reported two errors.
1. An [odr-violation from …

remove trailing newline in `compile_env`

---

src/mongocrypt-ctx-encrypt.c

MONGOCRYPT-555
Missing a call to `bson_destroy(&converted)` after converted as initialized.

Fix memory leak in _finalize

---

src/mc-fle2-rfds-private.h
src/mc-fle2-rfds.c
src/mongocrypt-ctx-encrypt.c
test/test-mc-fle2-payload-iev-v2.c
test/test-mc-fle2-payload-uev-v2.c
test/test-mc-fle2-rfds.c

MONGOCRYPT-558
MONGOCRYPT-559
MONGOCRYPT-560
This addresses the issues brought up in the above tickets. We will not be removing calls to `BSON_INITIALIZER`, but we are addressing the other issues uncovered in these tickets.

Improve bson_t initialization behavior

---

bindings/node/CHANGELOG.md
bindings/node/lib/stateMachine.js
bindings/node/package-lock.json
bindings/node/package.json

This PR fixes a bug in the driver's auto encryption.  The full details of the bug are listed in NODE-4896.
patch w/ driver: https://spruce.mongodb.com/version/644ac2897742aef2bc3b0cc4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
No drivers changes needed here, because CI pulls in `mongodb-client-encryption@alpha`.  Our custom csfle tests don't run in load balanced mode, so they were unaffected and we can wait to update the pinned commit until after the official 2.8.0 release.

fix(NODE-4896): do not pass explicit session into state machine helpers

---

bindings/node/test/clientEncryption.test.js

Patch against this exact commit: https://spruce.mongodb.com/version/6451168856234306eb1923f7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

test(NODE-5238): set min/max range options when required.

---

src/mongocrypt.c

Related: MONGOCRYPT-526
Fix race condition by moving critical section into the mutex protected scope.
See the following repo for a tool to test the race condition fixed in this PR: https://github.com/kkloberdanz/libmongocrypt_stresstest

Fix Race Condition

---

src/mongocrypt.c
test/test-mongocrypt-csfle-lib.c

- Include the error from `mcr_dll_open` when crypt_shared fails to load and an override path is set.
See MONGOCRYPT-576 for motivation for this change.

MONGOCRYPT-576 Include the error from `mcr_dll_open` in hard error

---

bindings/node/README.md
bindings/node/index.d.ts
bindings/node/lib/clientEncryption.js
bindings/node/lib/errors.js

This PR marks the QE equality API as stable.

docs(NODE-5264): mark QE equality stable

---

.evergreen/config.yml
bindings/node/.evergreen/install-dependencies.sh
bindings/node/.evergreen/prebuild.sh
bindings/node/.evergreen/test.sh
bindings/node/test/providers/credentialsProvider.test.js

- Breaks out the prebuild script in the Node bindings to its own task.
- Adds Node 20 to bindings and tests it on Ubuntu 20 distros.
- Only prebuilds and publishes Node bindings on specific distros with Node 16.
- Fixes HTTP header errors on Node 20 tests.
Distros Node publishes from now:
- MacOS M1 arm64 11.00
- MacOS x64 10.14
- Ubuntu 16 arm64
- Ubuntu 16 x64
- Windows x64

test(NODE-5268): use node 20 in ci

---

src/mlib/int128.test.cpp

Observed the following internal compiler error when attempting to compile on `windows-vsCurrent` EVG distros (on which new CMake versions use the VS 2022 generator by default):
```
src\mlib\int128.test.cpp(95,21): fatal error C1001: Internal compiler error. [cmake-build\mlib.int128.test.vcxproj]
(compiler file 'msc1.cpp', line 1691)
[...]
src\mlib\int128.test.cpp(43,12): message : while evaluating constexpr function 'mlib_int128_from_string' [cmake-build\mlib.int128.test.vcxproj]
src\mlib\int128.test.cpp(92,31): message : while evaluating constexpr function 'operator ""_i128' [cmake-build\mlib.int128.test.vcxproj]
[...]
```
Assuming this is related to https://developercommunity.visualstudio.com/t/User-defined-literals-cause-ICEs/10259122 as linked in the corresponding comment. Its …

Workaround ICE on VS 2022 due to int128.test.cpp

---

CHANGELOG.md
README.md

Cherry-picks commits 4decbf03f2d4e35ea4aeaae72b2132cd933f0f3f and 85bc65d56fa1c7b8ca499d8523ac269815704076 onto the `master` branch.
These changes were only made on the r1.8 branch. This was likely an oversight during the 1.8.0 release. The [release instructions](https://github.com/mongodb/libmongocrypt/blob/c03b40b14cd675dca5f0c7d79384519fd55edfda/README.md#releasing) say to make these changes on the master branch:
> - Commit these changes (on `master`) so that both the `master` branch and the new branch you are about to create refer to the new branch (note that this means you will commit changes to this file, and `CHANGELOG.md`)

update Linux package instructions for 1.8; update CHANGELOG

---

bindings/node/README.md
bindings/node/etc/README.hbs
bindings/node/index.d.ts
bindings/node/lib/clientEncryption.js
bindings/node/lib/errors.js

This PR deprecates any public callback types and overloads of public async functions that take callbacks.  Additionally, this PR notes on any publicly exported classes that the classes will be moved into the driver in the coming major release.

feat(NODE-5431): add node bindings v6 deprecations

---

.evergreen/config.yml
bindings/node/package-lock.json
bindings/node/package.json

- Dropping support for Node.js 14
- Update variable name nvm_use -> node_lts in evg config
Removing support for EOL node versions helps us keep our tooling and testing up to date and modern. 
The minimum supported Node.js  version is now v16.20.1. We strive to keep our minimum supported Node.js version in sync with the runtime's [release cadence](https://nodejs.dev/en/about/releases/) to keep up with the latest security updates and modern language features.

feat(NODE-5417)!: bump minimum Node.js version to v16.20.1

---

src/mongocrypt-kms-ctx.c

Intends to resolve Coverity issues with CIDs: 121015, 121014, 121009, 121005
`kms_response_parser_get_response` may return NULL if parsing a KMIP response is incomplete.
I expect this has little (or no) current impact. This change may prevent a NULL dereference if future error conditions are added to `kms_response_parser_get_response`.

check return of `kms_response_parser_get_response`

---

src/mc-fle2-payload-iev-v2.c
src/mc-fle2-payload-iev.c

I expect these are low impact leaks that could only appear on encrypting or decrypting malformed data.

MONGOCRYPT-582 fix leaks on errors

---

.evergreen/config.yml
etc/packager.py
etc/repo_config.yaml

Full Evergreen patch build: https://spruce.mongodb.com/version/64bae49461837d89197ad676/tasks?limit=100&page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
I also manually inspected the differences in a set of RPM packages between the patch build and its base build for RHEL8. This is because the way that RPMs are built works a little differently after updating `packager.py`. The differences that were observed were all expected and the updated `packager.py` produces working RPMs.

MONGOCRYPT-580 Add package publication for missing os/arch combinations

---

bindings/node/addon/mongocrypt.cc
bindings/node/test/bindings.test.ts

this PR relaxes the assertions in Node's C++ bindings to allow `undefined` values for `Uint8Array` options.  The logic was accidentally made a bit too strict in https://github.com/mongodb/libmongocrypt/pull/682, which broke Node's driver CI.
I only applied the fix to options touched in https://github.com/mongodb/libmongocrypt/pull/682.  Additionally, this was only relevant to options (not function arguments). So for example, the following is still invalid (because the first argument to `makeDecryptionContext` must be provided and was never optional): `mongocrypt.makeDecryptionContext(undefined)`.

fix(NODE-5516): allow `undefined` values for optional Uint8Arrays arguments

---

kms-message/CMakeLists.txt
kms-message/src/kms_port.c
kms-message/src/kms_request.c
kms-message/src/kms_request_str.c

Full Evergreen patch build: https://spruce.mongodb.com/version/64d65ca9850e610b584fe1e8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

MONGOCRYPT-586 port in C driver-specific KMS changes

---

cmake/ImportBSON.cmake
src/crypto/libcrypto.c
src/mc-fle2-encryption-placeholder.c
test/test-mongocrypt-ctx-encrypt.c

Some simple tweaks.
It would be helpful if we ran all our CI builds with `-Wall -Werror`, but when I tried to enable that it quickly became apparent that there are multiple moving parts that need to be sorted out. As a result, I am going to write a separate ticket for that work.

MONGOCRYPT-512 fix warnings from -Wsign-compare

---

.evergreen/benchmark-java.sh
.evergreen/config.yml
bindings/java/mongocrypt/benchmarks/build.gradle.kts
bindings/java/mongocrypt/benchmarks/src/main/java/com/mongodb/crypt/benchmark/BenchmarkRunner.java
bindings/java/mongocrypt/benchmarks/src/main/resources/keyDocument.json
bindings/java/mongocrypt/build.gradle.kts
bindings/java/mongocrypt/settings.gradle.kts

Add a benchmark in the Java bindings to measure throughput of decrypting documents with many encrypted values.
This PR partially resolves MONGOCRYPT-589. A following PR is planned to export the struct definition of `mongocrypt_binary_t` and update bindings to avoid calls to `mongocrypt_binary_data` and `mongocrypt_binary_len`.
The benchmark is intended to measure the workload identified in DRIVERS-2581 and compare future changes.
The benchmark uses the `rhel90-dbx-perf-large` distro suggested in DRIVERS-2666. The results appears stable: [10 executions](https://spruce.mongodb.com/task/libmongocrypt_benchmark_benchmark_java_patch_f6817fa54b4913d42b8f8718577f4884133530fb_64eca5d2a4cf47658d19ef8d_23_08_28_13_49_06/logs?execution=9) produced the same `Decrypting median ops/sec` of `31`.
[Java …

MONGOCRYPT-589 Add bulk decrypt benchmark with Java bindings

---

CHANGELOG.md

This PR copies missing CHANGELOG from the `r1.8` branch.

update CHANGELOG for 1.8.1 and 1.8.2

---

.evergreen/config.yml
bindings/node/.evergreen/install-dependencies.sh

Fixes Node 16 failures on npm latest.

ci(NODE-5604): use npm 9 on eol node versions

---

Earthfile

This fixes the `rpm-package-build` task.
Evergreen patch build: https://evergreen.mongodb.com/version/64f9d75132f4173437b314b2?redirect_spruce_users=true
I would also cherry-pick this change onto the `r1.8` branch to make the `rpm-package-build` task green on that branch as well.

Use Fedora 38 for RPM build

---

bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CAPI.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CAPIHelper.java
src/mongocrypt-binary-private.h
src/mongocrypt-crypto.c
src/mongocrypt.h
test/test-mongocrypt-crypto-hooks.c

- Export definition of `mongocrypt_binary_t`.
- Read fields of `mongocrypt_binary_t` directly in Java bindings.
Languages interfacing with libmongocrypt may observe slower throughput with frequent calls to C functions.
[HELP-27047](https://jira.mongodb.org/browse/HELP-27047) identifies a problematic workload: decrypting documents with 1500 encrypted values.
Profiling showed significant samples spent in calls to `mongocrypt_binary_data` and `mongocrypt_binary_len`.
[A prototype benchmark](https://github.com/mongodb/DRIVERS-2581) showed improvement by using the struct definition directly, rather than calling `mongocrypt_binary_data` and `mongocrypt_binary_len`:
```
run_test 'Baseline' ... begin
Baseline   (ms): 9.868333
Decrypting (ms): 35.971542
Overhead   (ms): 26.103209
Overhead   (+%): …
```

MONGOCRYPT-589 export `mongocrypt_binary_t`

---

.evergreen/config.yml

- Skip or remove `test-java` tasks failing to find JDK.
Some `test-java` tasks fail to locate the JDK ([example](https://spruce.mongodb.com/task/libmongocrypt_debian11_test_java_ce14f0cebfe9d33bf5d2f5467a0fb8a36908e80c_23_09_05_12_41_16/logs?execution=0)):
```
[2023/09/05 13:04:41.741] + JAVA_HOME=/opt/java/jdk8
[2023/09/05 13:04:41.741] + ./gradlew -version
[2023/09/05 13:04:41.745] ERROR: JAVA_HOME is set to an invalid directory: /opt/java/jdk8
[2023/09/05 13:04:41.745] Please set the JAVA_HOME variable in your environment to match the
[2023/09/05 13:04:41.745] location of your Java installation.
```
Java does not appear installed on `debian11-large` (`java` results in `command not found` and `locate java` does not locate a JDK). A JDK install may need to be requested with a BUILD …

MONGOCRYPT-593 Skip or remove `test-java` tasks failing to find JDK.

---

.evergreen/earthly.sh
etc/format.sh

This PR makes minor changes to `./.evergreen/earthly.sh` and `etc/format.sh` to address the following errors encountered locally:
```
zsh: ./.evergreen/earthly.sh: bad interpreter: /usr/bin/bash: no such file or directory
```
```
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
pipx>=0.17.0<2.0
~~~~~~~~^
```

fix earthly and format script

---

bindings/java/mongocrypt/.gitignore
bindings/java/mongocrypt/benchmarks/src/main/java/com/mongodb/crypt/benchmark/BenchmarkRunner.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CipherCallback.java

- Add multi-threaded bulk decryption benchmark.
- Pool `Cipher` instances to improve throughput.
Profiling showed significant samples spent in calls to `Cipher.getInstance`.
[A prototype benchmark](https://github.com/mongodb/DRIVERS-2581) showed improvement by using a ThreadLocal for `Cipher` instances. Use of a ThreadLocal is not proposed given ["Thread-local variables" of JEP 444](https://openjdk.org/jeps/444#:~:text=This%20JEP%20proposes%20to%20finalize,cannot%20have%20thread%2Dlocal%20variables.):
> because virtual threads can be very numerous, use thread locals only after careful consideration.
This PR proposes adding a pool of `Cipher` objects. `CipherPool` is loosely based on [`PowerOfTwoBufferPool`](https://github.com/mongodb/mongo-java-driver/blob/ed1fadbeb30731b80a02d5a3aaead816a …

MONGOCRYPT-595 pool `Cipher` instances

---

bindings/node/package-lock.json
bindings/node/package.json

version 6x of the Node driver is incompatible with mongodb-client-encryption <6.0.0.  This PR specifies that the 2.x version of mongodb-client-encryption must be used with a <6.0.0 driver in the package.json.
this change is only for Node driver CI on the 4.x branch.
successful patch: https://spruce.mongodb.com/version/652045a92a60ed19da065615/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

fix(NODE-5632): specify mongodb dependency <6.0.0

---

bindings/node/package-lock.json
bindings/node/package.json

This is a repeat of https://github.com/mongodb/libmongocrypt/pull/701.  The node-2.x branch #701 merged into was branched from the wrong Nodejs release tag.  I've reset the branch to the node-v2.9.0 release tag and am re-opening this PR.

fix(NODE-5632): specify mongodb dependency <6.0.0 

---

bindings/node/.evergreen/install-dependencies.sh

Most of our CI uses node 16, so we cannot upgrade `npm` to latest.

ci(no-story): do not upgrade npm on node-2.x branch

---

cmake/IntelDFP.cmake

The user reported issue was a result of the `-i` option being left out of the `PATCH_COMMAND` when the program being called is `patch` rather than `git`. This is actually something that seems like it should happen essentially never (since dev systems without git are probably very rare). However, it's an easy fix.
Evergreen patch build: https://spruce.mongodb.com/version/652832f230661510ed316f10/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

MONGOCRYPT-594 patch requires -i option before patch file

---

src/mongocrypt-dll-private.h
src/mongocrypt.c
src/os_posix/os_dll.c
src/os_win/os_dll.c

Warn if `mcr_dll_path` is not supported.
MONGOCRYPT-481 reports a build error on AIX due to no implementation of `mcr_dll_path`.
`mcr_dll_path` is only used by `_validate_csfle_singleton` to ensure a unique copy of the library is loaded. Validating is not strictly necessary to proceed.
This PR proposes warning if `mcr_dll_path` is not supported to enable building on more platforms.
Tested locally by adding expectedly undefined macro to check:
```diff
--- a/src/os_posix/os_dll.c
+++ b/src/os_posix/os_dll.c
@@ -53,7 +53,7 @@ void *mcr_dll_sym(mcr_dll dll, const char *sym) {
#endif
-#ifdef __APPLE__
+#if defined(__APPLE__) && defined(NOTDEFINED)
#include <mach-o/dyld.h>
#include <mach-o/nlist.h>
```
Running `./cmake-build/test-mongocrypt _test_csfle_load_twice` results in:
```
begin …
```

MONGOCRYPT-481 Warn if `mcr_dll_path` not implemented

---

cmake/IntelDFP.cmake
etc/mongo-inteldfp-alpine-arm-fix.patch

MONGOCRYPT-601
Without this fix, building on Alpine on ARM64 results in the compiler error below.
Since we do not support ancient versions of Solaris, the redefinition of `wchar_t` does not seem necessary, therefore it is safe to remove.
```
In file included from /build/cmake-build/_deps/intel_dfp-src/LIBRARY/src/bid_internal.h:41,
from /build/cmake-build/_deps/intel_dfp-src/LIBRARY/src/bid_trans.h:61,
from /build/cmake-build/_deps/intel_dfp-src/LIBRARY/src/bid128_asin.c:29:
/build/cmake-build/_deps/intel_dfp-src/LIBRARY/src/bid_functions.h:46:15: error: conflicting types for 'wchar_t'; have 'int'
46 | typedef int   wchar_t;
|               ^~~~~~~
In file included from /usr/include/stdlib.h:21,
from /usr/include/fortify/stdlib.h:23,
from …
```

MONGOCRYPT-601 fix build for Alpine on ARM64

---

.evergreen/config.yml

Add `build-and-test-node` and `build-and-publish-node` tasks to `rhel83-zseries`.

ci(NODE-4193): Add Enterprise RHEL 8 zSeries

---

src/mongocrypt-util.c

This returns an error to the caller instead of a hard compile error. The 34a6e9d585e4b8fd1c4f18ffa57a08a6f3338546 commit partially addressed this, but this file wasn't touched by it.
This lets mongocrypt work on a platform without dll_path support, like AIX, but CSFLE is untested.

MONGOCRYPT-603 Don't return a compile error if dll_path unsupported

---

.evergreen/benchmark-python.sh
.evergreen/config.yml
bindings/python/test/performance/keyDocument.json
bindings/python/test/performance/perf_test.py

https://jira.mongodb.org/browse/PYTHON-3838
Implements the decryption benchmark described in https://github.com/mongodb/specifications/blob/master/source/client-side-encryption/tests/benchmarks.rst#benchmarking-bulk-decryption
Modeled after the Java benchmark here: https://github.com/mongodb/libmongocrypt/blob/4e64586/bindings/java/mongocrypt/benchmarks/src/main/java/com/mongodb/crypt/benchmark/BenchmarkRunner.java

PYTHON-3838 Add decryption benchmark

---

bindings/python/pymongocrypt/binary.py
bindings/python/pymongocrypt/binding.py
bindings/python/test/performance/perf_test.py

The second half of https://jira.mongodb.org/browse/PYTHON-3838.
Note we don't have to update our `_MIN_LIBMONGOCRYPT_VERSION` because the mongocrypt_binary_t definition hasn't changed.
Benchmark before this change:
```
[2023/12/05 14:23:50.775] Finished TestBulkDecryption, threads=1. MEDIAN ops_per_second=11.68
[2023/12/05 14:23:50.775] Finished TestBulkDecryption, threads=2. MEDIAN ops_per_second=4.22
[2023/12/05 14:23:50.775] Finished TestBulkDecryption, threads=8. MEDIAN ops_per_second=2.55
[2023/12/05 14:23:50.775] Finished TestBulkDecryption, threads=64. MEDIAN ops_per_second=2.42
```
Benchmark after:
```
[2023/12/05 14:21:44.102] Finished TestBulkDecryption, threads=1, median ops_per_second=12.45
[2023/12/05 14:21:44.102] Finished TestBulkDecryption, threads=2, median …
```

PYTHON-3838 Use mongocrypt_binary_t definition to improve performance

---

src/mongocrypt.c
test/test-mongocrypt.c

Fix leak (and return error) if configuring "aws" and "local" with `mongocrypt_setopt_kms_providers` after credentials were previously configured.
Calling `mongocrypt_setopt_kms_providers` with "aws" twice or after configuring with `mongocrypt_setopt_kms_provider_aws` results in a memory leak. Here is a report from LSan:
```
Direct leak of 4 byte(s) in 1 object(s) allocated from:
#0 0x1051ff978 in malloc+0x8c (libclang_rt.asan_osx_dynamic.dylib:arm64+0x53978)
#1 0x102ed8980 in bson_malloc bson-memory.c:70
#2 0x102ede58c in bson_strndup bson-string.c:448
#3 0x102e5cbac in _mongocrypt_validate_and_copy_string mongocrypt.c:971
#4 0x102e5c7cc in mongocrypt_setopt_kms_provider_aws mongocrypt.c:186
#5 0x102d84280 in _test_setopt_kms_providers test-mongocrypt.c:817
#6 0x102d76c04 in main …
```

MONGOCRYPT-610 fix leak after repeated configuring of "aws" and "local" creds

---

.evergreen/config.yml

Follow-up for ef5b0b54adaadf3b8a1a151aa31b91702bf17187
After this is merged, I will also cherry-pick to `r1.8`.

MONGOCRYPT-580 fix package publications for newly added distros

---

src/mongocrypt.c
src/mongocrypt.h
test/test-mongocrypt-crypto-hooks.c

Add `mongocrypt_is_crypto_available` to report whether libmongocrypt is built with native crypto support.
libmongocrypt can be built without native crypto support with the CMake option `DISABLE_NATIVE_CRYPTO`. If native crypto is disabled, crypto primitives must be supplied with callbacks (e.g. `mongocrypt_setopt_crypto_hooks` and friends).
DRIVERS-2718 proposes having driver bindings prefer using libmongocrypt with native crypto when available for the observed performance imporvement. This may require driver check if libmongocrypt is built with native crypto at runtime:
> Add a method in CAPI like bool isCryptoAvailable(). Change the wrapper to call that method and only register crypto callbacks if it returns false.

MONGOCRYPT-616 add `mongocrypt_is_crypto_available`

---

bindings/python/CHANGELOG.rst
bindings/python/pymongocrypt/credentials.py
bindings/python/pymongocrypt/explicit_encrypter.py
bindings/python/pymongocrypt/mongocrypt.py
bindings/python/pymongocrypt/version.py
bindings/python/test/test_mongocrypt.py

https://jira.mongodb.org/browse/PYTHON-4172
This change extends the python-side kms provider validation rules to the new named providers. Note that we already pass kms_providers directly to libmongocrypt so this change isn't a blocker. All users need to do is ensure they have a libmongocrypt with [MONGOCRYPT-605](https://jira.mongodb.org/browse/MONGOCRYPT-605) installed (>= v1.9.0).
This change also fixes a bug in the python binding which blocks named kms providers from being used in create_data_key. The bug results in this `EncryptionError: unknown kms_provider: aws:name1` error:
```python
return target.create_data_key(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/shane/git/mongo-python-driver/pymongo/encryption.py", line 747, in create_data_key
with …
```

PYTHON-4172 Support named KMS providers

---

src/mc-dec128.h
src/mc-rangeopts-private.h
src/mc-rangeopts.c
src/mongocrypt-ctx.c
src/mongocrypt-opts-private.h
src/mongocrypt-private.h
src/mongocrypt.c
test/test-mc-fle2-rfds.c
test/test-mc-rangeopts.c

Extends the FLE2RangeInsertSpec and RangeOpts structures to support the passthrough and bounds checking of trim factor. Does not actually use the trim factor in the query or insert algos yet.

SERVER-85740 Extend libmongocrypt to support trimFactor passthrough

---

.evergreen/config.yml
bindings/java/mongocrypt/.evergreen/publish.sh

- use `include_expansions_in_env` to pass expansions
Prior to this PR, internal [Agent Logs](https://spruce.mongodb.com/task/libmongocrypt_java_release_publish_java_4261b443ef174ae741d7d45ead83f37c70d64de2_24_02_07_02_01_25/logs?execution=0&logtype=agent) included the evaluated expansions. Changes in this PR were verified by inspecting the [Agent Logs](https://spruce.mongodb.com/task/libmongocrypt_java_release_publish_java_patch_1be6cd3908bc23ac0404c2be73afed929597fdfd_65cbc8df1e2d1751c8d7263d_24_02_13_19_54_08/logs?execution=0&logtype=agent) on a patch build.
This PR uses `include_expansions_in_env` to pass expansions as environment variables to the publish.sh script. Using `include_expansions_in_env` is a suggested solution in [Unsafe Secret Usage in Evergreen Projects …

MONGOCRYPT-623 use `include_expansions_in_env` to pass expansions

---

README.md
doc/releasing.md

- Separate Homebrew release steps
- Add link to Debian release steps.
- Move release instructions to separate document.
The separate steps is intended to provide linkable sections. I plan to request a Jira automation to create MONGOCRYPT tickets tracking the pending Homebrew and Debian steps after a release is tagged.
Moving the release instructions to a separate document is intended to simplify the main README. I expect only internal developers are concerned with releasing.

Separate release steps

---

bindings/python/.evergreen/test.sh
bindings/python/CHANGELOG.rst
bindings/python/README.rst
bindings/python/pymongocrypt/binding.py
bindings/python/pymongocrypt/mongocrypt.py
bindings/python/release.sh

PYTHON-4181 Use libmongocrypt native crypto when available for better performance
TODO:
Before:
```
[2024/02/22 11:54:56.554] Running benchmark with pymongocrypt: 1.9.0.dev0 libmongocrypt: 1.10.0-20240222+gitae4c445a80
[2024/02/22 11:54:56.554] Finished TestBulkDecryption, threads=1, median ops_per_second=13.17
[2024/02/22 11:54:56.554] Finished TestBulkDecryption, threads=2, median ops_per_second=5.24
[2024/02/22 11:54:56.554] Finished TestBulkDecryption, threads=8, median ops_per_second=4.41
[2024/02/22 11:54:56.554] Finished TestBulkDecryption, threads=64, median ops_per_second=4.01
```
After (10-50x higher throughput):
```
[2024/02/26 13:50:13.106] Running benchmark with pymongocrypt: 1.9.0.dev0 libmongocrypt: 1.8.1-20240226+gita6d8858092
[2024/02/26 13:50:13.106] Finished …
```

PYTHON-4181 Use libmongocrypt native crypto when available for 10-50x better performance

---

bindings/python/README.rst

Some minor improvements to PYTHON-4181.

PYTHON-4181 Improve libmongocrypt install docs

---

.evergreen/config.yml
Earthfile
README.md
etc/packager.py
etc/repo_config.yaml

This PR adds PPA publishing to Debian 12 (both arm64 and x86_64).
Development packages were uploaded in [this patch build](https://spruce.mongodb.com/version/65d8f2291e2d17c1f5afdae5/), and can be tested with Earthly:
```
./.evergreen/earthly.sh +test-deb-packages-from-ppa --env=deb12 --distro="debian bookworm"
```
Release packages are expected with the 1.9.1 release.

MONGOCRYPT-622 publish Debian 12 packages

---

src/mongocrypt.h
test/test-mongocrypt-crypto-hooks.c
test/test-mongocrypt-crypto-std-hooks.c
test/test-mongocrypt-crypto-std-hooks.h

Test that crypto hooks may be set with `mongocrypt_setopt_aes_256_ctr` without setting other crypto hooks.
Document the `ctx` argument in `mongocrypt_setopt_aes_256_ctr` as unused.
libmongocrypt provides native crypto primitive (HMAC, AES, SHA) implementations by default. The native crypto may be disabled with the CMake option `DISABLE_NATIVE_CRYPTO`. When native crypto is disabled, drivers are expected to provide crypto hooks (callbacks).
libmongocrypt native crypto for AES-CTR mode is not supported on macOS <= 10.14. noted in MONGOCRYPT-440:
> AES-CTR mode is required for Queryable Encryption (aka FLE 2). It is not supported on macOS 10.14 or earlier.
DRIVERS-2718 encourages drivers to prefer libmongocrypt with native crypto for improved performance:
> Package the crypto-enabled …

MONGOCRYPT-647 test CTR hook can be set without other hooks

---

src/mongocrypt-ctx-encrypt.c
src/mongocrypt-ctx-private.h
src/mongocrypt-ctx.c
src/mongocrypt.h
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-setopt.c
test/test-mongocrypt.c
test/test-mongocrypt.h

Related main repo changes: https://github.com/10gen/mongo/pull/19645
Related enterprise changes: https://github.com/10gen/mongo-enterprise-modules/pull/1994
The new "range" query/index type works with both range V1 and V2. When we are using range V2, we can't use "rangePreview" as either an index type or query type. 
For range V1, the "range" query type is compatible with the "rangePreview" index type; this is for the case where we are using an old collection with "rangePreview" query type since we want to encourage using the new name. The alternative behavior would be that when using range V1, we force users to always use "rangePreview". I thought this was undesirable if we want to treat that name as deprecated. Conversely, the "rangePreview" query type is incompatible with the "range" …

MONGOCRYPT-621 Rename rangePreview to range

---

src/mongocrypt.h

API notes marking the "rangePreview" API as experimental were removed in [#766](https://github.com/mongodb/libmongocrypt/pull/766/files#diff-cdd5d6a17e876defa9e5fb2c5753de9522cc53ed8a9f22864f17f68646ab7bb6L678) but have not yet been released.
This PR proposes adding back notes to give a heads-up to consumers (primarily, other drivers) that "rangePreview" is experimental, and API for "rangePreview" may be removed in a future release.

MONGOCRYPT-621 document "rangePreview" API as experimental

---

CMakeLists.txt
src/mongocrypt-opts.c
test/test-gcp-auth.c
test/test-mongocrypt-cleanup.c
test/test-mongocrypt-compact.c
test/test-mongocrypt-crypto-hooks.c
test/test-mongocrypt-csfle-lib.c
test/test-mongocrypt-ctx-decrypt.c
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-rewrap-many-datakey.c
test/test-mongocrypt-ctx-setopt.c
test/test-mongocrypt-datakey.c
test/test-mongocrypt-log.c
test/test-mongocrypt-opts.c
test/test-mongocrypt.c
test/test-mongocrypt.h
test/test-named-kms-providers.c

When the option is enabled, newly created mongocrypt_t objects will have use_range_v2 set to true. In testing, we add a new _mongocrypt_init_for_testing which disables this option before calling mongocrypt_init, which is needed because there are a multitude of tests which implicitly rely on the range V1 behavior (ex. by testing the actual encrypted payload blob against a specific encrypted payload blob). As part of MONGOCRYPT-661 (enabling this flag by default), we will audit these tests and decide which ones to update for the new behavior, which to leave as-is (while explicitly disabling range V2) and which to remove.

MONGOCRYPT-663 Add cmake option to enable Range V2

---

bindings/node/addon/mongocrypt.h

- Add `NODE_API_EXPERIMENTAL_NOGC_ENV_OPT_OUT` to fix issue https://github.com/nodejs/node/issues/52229
No
- To get builds working again on Node.js 20.x
Node.js v20.12.0 introduced a change that prevented compiling the existing source without defining the above macro.

fix(NODE-6109): allow building from source on latest Node.js 20.x

---

bindings/java/mongocrypt/src/main/resources/META-INF/native-image/jni-config.json
bindings/java/mongocrypt/src/main/resources/META-INF/native-image/reflect-config.json

The whole `driver-core/src/main/resources/META-INF/native-image/jni-config.json` goes here: `NativeImageApp` works without any of this metadata as long as it does not run encryption tours. And when it does run those without this `jni-config.json`, it fails in `com.mongodb.crypt.capi.CAPI`.
JAVA-5407

Add GraalVM reachability metadata

---

kms-message/src/kms_gcp_request.c
kms-message/src/kms_request_str.c
src/crypto/libcrypto.c
src/mc-fle2-encryption-placeholder.c
src/mc-fle2-payload-iev-v2.c
src/mc-fle2-rfds.c
src/mc-rangeopts.c
src/mongocrypt-cache-key.c
src/mongocrypt-ctx-decrypt.c
src/mongocrypt-ctx-encrypt.c
src/mongocrypt-key.c
src/mongocrypt-marking.c
src/mongocrypt-util.c
src/os_posix/os_dll.c

This PR addresses some issues identified by Coverity. See individual commits for the CID.
There are many Coverity issues referencing uninitialized access of the `bson_iter_t::value` field:
```c
bson_iter_t iter1;
BSON_ASSERT (bson_iter_init (&iter1, &bson)); // Does not initialize `iter1.value`
bson_iter_t iter2 = iter1; // Assigns uninitialized `value`.
```
I expect this is OK in practice. I do not expect `bson_iter_t::value` is meant to be directly accessed. The `bson_iter_t::value` is initialized and returned in `bson_iter_value`. Regardless, this PR errs towards safety and zero-initializes the `bson_iter_t` where issues were reported.
Once https://github.com/mongodb/mongo-c-driver/pull/1587 is released in libbson, libmongocrypt can upgrade the libbson dependency to avoid this issue in …

MONGOCRYPT-625 address Coverity issues

---

src/mongocrypt-ctx-decrypt.c
src/mongocrypt-ctx-encrypt.c

This is a follow-up to https://github.com/mongodb/libmongocrypt/pull/782 to address additional issues reported in Coverity.

MONGOCRYPT-625 Fix additional coverity warnings

---

doc/releasing.md

This is intended to satisfy the static analysis reporting requirement of SSDLC. Rather than finding a tool that exports SARIF, this chooses the alternative:
> If SARIF output is not supported, teams MUST manually report JIRA tickets and create static analysis reports
An `SSDLC Report` view has been added to Coverity to reduce needed manual effort. The resulting spreadsheet appears consistent with how the server reports Coverity issues.
I expect this process can also be used by C and C++ too if desired.

MONGOCRYPT-676 add release step to generate SSDLC static analysis report

---

doc/releasing.md

This PR intends to meet the requirement:
> Projects that are also published on distribution channels MUST comply with the corresponding SSDLC policy.
libmongocrypt is published to the MongoDB PPA. I expect that is considered a distribution channel. [Authorized publication on distribution channels (Change Log 1.1)](https://docs.google.com/document/d/1u0m4Kj2Ny30zU74KoEFCN4L6D_FbEYCaJ3CQdCYXTMc/edit#bookmark=id.5ed6jwn4f29f) describes the requirement for recording the release author and version.
This PR proposes adding a step to record this information to a spreadsheet. Updating the same spreadsheet is already part of the C driver release. I expect this can be done for the C++ driver too if desired.

MONGOCRYPT-682 add step to record release

---

Earthfile
cmake/FetchMongoC.cmake
cmake/IntelDFP.cmake
doc/releasing.md
etc/cyclonedx.sbom.json
etc/purls.txt

Add an SBOM Lite to describe bundled dependencies. Partially resolves MONGOCRYPT-672.
The `sbom-generate` Earthly target was copied from https://github.com/mongodb/mongo-c-driver/pull/1594
Though `libbson` is not third-party, I expect including `libbson` is required. I [suggested clarifying](https://docs.google.com/document/d/1mXxDdY38nGVKWJhIbH83X6mcHsxllAiunH2hg-NdDsY/edit?disco=AAABM36ReZg) in the scope goals with rationale.
Dependencies for libmongocrypt language bindings are not included. I expect language bindings will define their own SBOM Lite files referring to the libmongocrypt C library, as is [done for Node](https://github.com/mongodb/libmongocrypt/blob/6bd195e8e6cd027a71925a7c83413d53d9521365/bindings/node/sbom.json).

MONGOCRYPT-672 Add SBOM Lite

---

kms-message/src/kms_kmip_request.c

Just a tiny comment fix, but this was apparently lying around in my local checkout of libmongocrypt for a couple months 🙂  
Refs: http://docs.oasis-open.org/kmip/spec/v1.0/os/kmip-spec-1.0-os.html#_Ref242030690

Fix KMIP operations reference in comment

---

.evergreen/config.yml
Earthfile

This PR adds amd64 and arm64 builds of libmongocrypt for Alpine Linux 3.18 (a musl-based distro).
The approach uses the same `"tar and upload libmongocrypt libraries"` function in the Evergreen configuration that is used by other tasks. This way, consumers who want the Alpine artifacts can retrieve them based on the build variant name, as with artifacts built for other platforms and distros.
Evergreen patch build: https://spruce.mongodb.com/version/663d35d51c3e9b0007936faf/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
I confirmed that the artifacts produced by these tasks are for the correct architectures:
```
roberto@build01:~/Downloads$  find libmongocrypt-a* -name '*.so'
libmongocrypt-amd64/sharedbson/lib/libmongocrypt.so
libmongocrypt-amd64/sharedbson/lib/libkms_message.so …
```

MONGOCRYPT-416 build on Alpine Linux 3.18 (via Earthly)

---

bindings/java/mongocrypt/build.gradle.kts

Add a `mustRunAfter("unzipJava")` for `processResources`.
This is a follow-up PR to https://github.com/mongodb/libmongocrypt/pull/789 intended to address the `test-java` task failures.
Here is a patch build with both the `test-java` and `benchmark-java` tasks passing: https://spruce.mongodb.com/version/66475f9231a6190007b5316f 
https://github.com/mongodb/libmongocrypt/pull/789 tried using `dependsOn`, but resulted in a failure in the `benchmark-java` task. I expect there is opportunity to further improve the Gradle config for the benchmark project. Example: there is an (unrelated?) [exception thrown](https://parsley.mongodb.com/evergreen/libmongocrypt_benchmark_benchmark_java_f8eb858170f1c3e08dfe36508731adb734b7d64d_24_05_15_16_53_31/0/task?bookmarks=0,1242&shareLine=900) in the …

run `processResources` after `unzipJava`

---

.gitignore
Earthfile
doc/releasing.md

Add an `sbom-download` target to download an Augmented SBOM. Add step to release to attach Augmented SBOM.
Partially resolves MONGOCRYPT-680.
Addresses the requirement:
> Drivers MUST publish Augmented SBOM documents (produced by Silk processing SBOM Lite documents) alongside releases.
Related: I expect it is not needed to run `silkbomb upload`. Onboarding to [SilkBomb > Generate SBOM from purls](https://docs.devprod.prod.corp.mongodb.com/mms/python/src/sbom/silkbomb/docs/ONBOARDING/#generate-sbom-from-purls) notes:
> (Preferred) Commit the generated CycloneDx SBOM to source control. Silk will automatically get the latest version of your SBOM every night.
The SBOM Lite is committed to `etc/cyclonedx.sbom.json`.

MONGOCRYPT-680 attach Augmented SBOM to release

---

bindings/node/addon/mongocrypt.cc
bindings/node/src/index.ts

See the ticket for motivation/why it would be convenient to have this earlier than the 'main' range V2 work 🙂

fix(NODE-6173): add rangeV2 feature flag toggle to Node.js bindings

---

bindings/cs/MongoDB.Libmongocrypt/CryptClientFactory.cs
bindings/cs/MongoDB.Libmongocrypt/Library.cs
bindings/cs/MongoDB.Libmongocrypt/LibraryLoader.cs
bindings/cs/README.md
bindings/cs/Scripts/build.cake

Use libmongocrypt native crypto when available.
- Bundle crypto-enabled libmongocrypt on Mac.
- On linux continue to bundle crypto-disabled libmongocrypt, but inform users to install the crypto-enabled libmongocrypt on their system and use the new environment variable `LIBMONGOCRYPT_PATH` to make it available to the driver. If `LIBMONGOCRYPT_PATH` is not set then we default to using the packaged crypto-disabled libmongocrypt.
| Method                     | ThreadsCount | Mean        | Error     | StdDev    | Median      |
|--------------------------- |------------- |------------:|----------:|----------:|------------:|
| BulkDecryptionUsingBinding | 1            |    50.83 ms |  0.975 ms |  2.279 ms |    49.70 ms |
| BulkDecryptionUsingBinding | 2            |    71.34 ms |  1.422 ms | …

CSHARP-4944: Enable use of native crypto in libmongocrypt bindings

---

Earthfile
doc/releasing.md
etc/silk-create-asset-group.sh

This PR makes changes to support attaching an Augmented SBOM for all releases (not just feature releases):
- Add a release step to create a Silk asset group when doing a minor release.
- Add `--branch` argument to `sbom-download` target.
I expect attaching the Augmented SBOM is required for all releases. I left a [suggestion](https://docs.google.com/document/d/1mXxDdY38nGVKWJhIbH83X6mcHsxllAiunH2hg-NdDsY/edit?disco=AAABOjmUj4c) in the Client Libs scope to clarify.
The naming choice of `libmongocrypt-${branch}` for the `asset_id` is arbitrary, but was met with approval in this [slack thread](https://mongodb.slack.com/archives/C05N744KWQ4/p1716297227559829?thread_ts=1716296884.511029&cid=C05N744KWQ4).

MONGOCRYPT-680 Create Silk asset group in release

---

bindings/python/CHANGELOG.rst
bindings/python/pymongocrypt/version.py

Patch build: https://spruce.mongodb.com/version/6655b963736e870007224561/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PYTHON-4459 Prep for PyMongoCrypt 1.9.2 Release

---

.evergreen/linker-tests.sh
.evergreen/prep_c_driver_source.sh
CMakeLists.txt
cmake/FetchMongoC.cmake
cmake/ImportBSON.cmake
cmake/IntelDFP.cmake
cmake/Patch.cmake
etc/cyclonedx.sbom.json
etc/libbson-remove-GCC-diagnostic-pragma.patch
etc/purls.txt
src/mc-range-mincover-generator.template.h
src/mc-tokens-private.h
src/mc-tokens.c
src/mongocrypt-buffer.c
src/mongocrypt-private.h

Update bundled libbson to 1.27.1
Apply workarounds to resolve errors on RHEL 6.2 with gcc 4.4.7:
- Define `__STDC_LIMIT_MACROS` when compiling with C++.
- Disable GCC diagnostic macros in functions for gcc < 4.6.
Remove workarounds for older libbson:
- Replace `CONCAT` macro with `BSON_CONCAT`.
- Remove `BSON_SUBTYPE_ENCRYPTED` (now defined in libbson).
- Remove workaround for CDRIVER-3340.
Verified with this patch build: https://spruce.mongodb.com/version/6650b53f05094a0007522646
Updating bundled libbson is to address an issue reported in Skyk that was fixed in libbson 1.25.0: https://security.snyk.io/vuln/SNYK-UNMANAGED-MONGODBMONGOCDRIVER-6156642
Defining `__STDC_LIMIT_MACROS` resolves an error on [this patch](https://parsley.mongodb.com/evergreen/libmongocrypt_rhel_62_64_bit_build_and_ …

MONGOCRYPT-685 update libbson to 1.27.1

---

bindings/java/mongocrypt/build.gradle.kts
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CAPI.java
bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptImpl.java

* Only register crypto Java callbacks if mongocrypt_is_crypto_available returns false
* Package crypto-enabled shared libraries on Mac and Windows
* Continue to package crypto-disabled shared libraries on Linux due to OpenSSL incompatibilities. Applications can force use of a crypto-enabled shared library by manually installing it in the system path or else specify the path via jna.library.path system variable.
JAVA-5306

Use native cryptography where available

---

bindings/python/pymongocrypt/binding.py
src/mongocrypt.h

Document "range" as unstable.
There are pending changes that may impact "range" in libmongocrypt (SERVER-91077).
I expect "range" should have kept documentation indicating instability. I consider this a bug and intend to include this documentation in a 1.10.1 release.
This is expected to be a short-term documentation note and to be removed before resolving MONGOCRYPT-584.
This is related to https://github.com/mongodb/specifications/pull/1601 to document the driver API as unstable.

MONGOCRYPT-696 document "range" as unstable

---

CMakeLists.txt

Intended to address this warning when running CMake:
```
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.28/Modules/FetchContent.cmake:1331 (message):
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is 
not set.  The policy's OLD behavior will be used.  When using a URL       
download, the timestamps of extracted files should preferably be that of  
the time of extraction, otherwise code that depends on the extracted      
contents might not be rebuilt if the URL changes.  The OLD behavior       
preserves the timestamps from the archive instead, but this is usually not
what you want.  Update your project to the NEW behavior or specify the    
DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this      
robustness issue.
Call Stack (most …
```

enable policy CMP0135

---

cmake/FetchMongoC.cmake
cmake/IntelDFP.cmake
cmake/Patch.cmake

This is a follow-up to https://github.com/mongodb/libmongocrypt/pull/818 to resolve two observed issues:
- Configuring with `LIBBSON_PATCH_ENABLED=OFF` incorrectly disabled patching for IntelDFP.
- Patching libbson failed on a local Windows build in non-Cygwin shell.

MONGOCRYPT-685 fix disabling patching and whitespace

---

doc/releasing.md
etc/silk-create-asset-group.sh
etc/ssdlc_compliance_report.md
etc/third_party_vulnerabilities.md

- Add release steps to attach `ssdlc_compliance_report.md`.
- Add release steps to check Silk.
As a drive-by improvement, update the Silk asset group name to include the branch suffix to ease locating in the [Silk web UI](https://us1.app.silk.security/inventory/asset-group?assetId=&assets-filters=%5B%7B%22filterCriteria%22%3A%22startsWith%22%2C%22filterField%22%3A%22name%22%2C%22filterString%22%3A%5B%22libmongocrypt%22%5D%2C%22filterType%22%3A%22string%22%7D%5D&assets-page=1).
`ssdlc_compliance_report.md` is based off the [template](https://gist.github.com/rtimmons/8253d1dfcc5f233bdb2d9c73b8e5c129#file-minimal-md) referenced in [Proposal: SSDLC Compliance Verification Flow](https://docs.google.com/document/d/1yRbq_LZLn9vq4PzqWFqe9-zyhC97B3-mr_LiCKVuJrc/edit) and the report [proposed for …

MONGOCRYPT-683 add SSDLC report

---

doc/releasing.md

This PR includes tweaks to the release instructions after following for the 1.10.1 release. Notable changes:
Run `snyk monitor` when checking Snyk. This is intended to update vulnerability checks for dependency changes. [snyk monitor documentation](https://docs.snyk.io/snyk-cli/commands/monitor) notes:
> If you make changes to your code, you must run the `monitor` command again.
Add step to update [libmongocrypt Security Testing Summary](https://docs.google.com/document/d/1dc7uvBzu3okAIsA8LSW5sVQGkYIvwpBVdg5v4wb4c4s/edit#heading=h.5t79jwe4p0ss) with a link to the Evergreen patch. This is intended to satisfy a reporting requirement noted in this [slack thread](https://mongodb.slack.com/archives/C06F31ZEKU1/p1718920120640689?thread_ts=1718047795.692869&cid=C06F31ZEKU1).

MONGOCRYPT-625 update release instructions

---

bindings/python/test/data/compact/success/encrypted-payload.json
src/mongocrypt-ctx-encrypt.c
test/data/compact/no-range/cmd.json
test/data/compact/no-range/collinfo.json
test/data/compact/no-range/encrypted-field-config-map.json
test/data/compact/no-range/encrypted-payload.json
test/test-mongocrypt-compact.c

See MONGOCRYPT-699. Bug was discovered by a PHP driver test receiving an error running `compactStructuredEncryptionData` on non-range fields in server 7.0 after upgrading libmongocrypt:
```
Command 'compactStructuredEncryptionData' requires field 'encryptionInformation' when range fields are present
```
A drivers integration test for running compact with range fields is proposed in https://github.com/mongodb/specifications/pull/1605

MONGOCRYPT-699 Omit `encryptionInformation` in compact if no range fields are used

---

src/mc-range-edge-generation-private.h
src/mc-range-edge-generation.c
src/mc-range-encoding-private.h
src/mc-range-encoding.c
src/mc-range-mincover-private.h
src/mc-range-mincover.c
src/mc-rangeopts-private.h
src/mc-rangeopts.c
src/mongocrypt-marking-private.h
src/mongocrypt-marking.c
test/test-mc-range-edge-generation.c
test/test-mc-range-encoding.c
test/test-mc-range-mincover.c
test/test-mongocrypt-marking.c

Error if precision-mode encoding cannot be used when precision is specified.
Patch build: https://spruce.mongodb.com/version/66849c9eb759740007686794
Applies similar changes from https://github.com/10gen/mongo/pull/23753. See SERVER-91571 for motivation.
The server validates in `validateEncryptedFieldConfig` to prevent creating a collection with an invalid `min/max/precision`. This PR proposes adding the validation in the `mc_getTypeInfo*` functions. This is intended to validate regardless of how `min/max/precision` was specified (manually for explicit encryption or from placeholders for automatic encryption).
The error check is only applied for rangev2 to match server behavior. This motivated passing a `use_range_v2` argument to multiple functions. The argument may be removed once …

MONGOCRYPT-703 Error if precision-mode encoding cannot be used

---

cmake/ImportBSON.cmake

Save and restore `BUILD_VERSION` before adding C driver project in CMake.
Intended to resolve an observed error building libmongocrypt with `MONGOCRYPT_MONGOC_DIR` specified: https://github.com/mongodb/mongo-c-driver/pull/1656#discussion_r1657626974. The `BUILD_VERSION` intended for libmongocrypt was incorrectly applied to the C driver subproject.
`MONGOC_FETCH_TAG_FOR_LIBBSON` is only defined when `FetchMongoC.cmake` is loaded. When `MONGOCRYPT_MONGOC_DIR` is used, libbson is not fetched, and `MONGOC_FETCH_TAG_FOR_LIBBSON` is not defined.
This PR clears and restores the normal and cache variable for `BUILD_VERSION`. An attempt was made to set `BUILD_VERSION` to an empty string unconditionally. [CMake unset](https://cmake.org/cmake/help/latest/command/unset.html) notes:
> **unsetting a …

MONGOCRYPT-706 clear `BUILD_VERSION` before including C driver

---

cmake/ImportBSON.cmake

zlib is not needed in libmongocrypt. Disabling addresses local build failures with zlib 1.2.13 on Homebrew clang version 18.1.8:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/stdio.h:225:7: error: expected identifier or '('
225 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_3_2, __DARWIN_EXTSN(fdopen));
|          ^
/Users/kevin.albertson/code/libmongocrypt/cmake-build/_deps/embedded_mcd-src/src/zlib-1.2.13/zutil.h:147:33: note: expanded from macro 'fdopen'
147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
|                                 ^
```
The build failure appears resolved when using newer versions of zlib. Building newer versions of the C driver with zlib 1.3.1 (due …

disable zlib in mongoc subproject

---

src/mc-efc-private.h
src/mc-efc.c
src/mongocrypt-ctx-encrypt.c
test/test-mc-efc.c
test/test-mongocrypt-ctx-encrypt.c

Error earlier if "rangePreview" is used with auto encryption with rangeV2 enabled.
Evergreen patch: https://spruce.mongodb.com/version/668ffe0531e5a60007090e86
Partially resolves MONGOCRYPT-661. Intended to improve the error if "rangePreview" is used when rangeV2 is enabled.
Prior to this PR, auto encryption with "rangePreview" and rangeV2 enabled results in an error parsing payloads from query analysis (mongocryptd or crypt_shared). Example:
```
Error parsing FLE2RangeInsertSpec: Missing field 'trimFactor' in placeholder
```
This PR proposes erroring earlier. If libmongocrypt receives an `encryptedFields` with "rangePreview" specified, return an error like the following:
```
Cannot use field 'foo' with 'rangePreview' queries. 'rangePreview' is unsupported. Use 'range' instead. 'range' is …
```

MONGOCRYPT-661 improve unsupported error for "rangePreview"

---

src/mc-range-encoding.c
test/test-mc-range-encoding.c

Removes maximum precision assertions.
Corresponding server PR:https://github.com/10gen/mongo/pull/24903

MONGOCRYPT-695 Remove upper bound assertions on FLE2 range precision

---

CHANGELOG.md
src/mongocrypt.h

Follow-up to https://github.com/mongodb/libmongocrypt/pull/861.
~~This PR is not-yet ready to merge. It is awaiting pending [protocol changes](https://jira.mongodb.org/issues/?jql=project%3DMONGOCRYPT%20and%20labels%3D%22range-ga-drivers%22%20and%20status%20!%3D%20closed).~~

MONGOCRYPT-661 document "range" as stable

---

.evergreen/config.yml

Follow-up to https://github.com/mongodb/libmongocrypt/pull/805. Intended to resolve issue using Alpine build reported in MONGOCRYPT-708.
The `--artifact` command was not supplied with an `--env`, resulting in use of the [default environment](https://github.com/mongodb/libmongocrypt/blob/b1753358f4e243d164f31fe31338c2ef70f3cb77/Earthfile#L375) (Ubuntu 22.04).
Removes the redundant `build` command. The `--artifact` command runs the necessary target.
Checking the binary of a [prior task](https://spruce.mongodb.com/task/libmongocrypt_alpine_arm64_earthly_build_with_earthly_b1753358f4e243d164f31fe31338c2ef70f3cb77_24_07_31_17_07_01/files?execution=0&sortBy=STATUS&sortDir=ASC) shows a shared library dependency of `ld-linux-aarch64.so.1`:
```
mkdir libmongocrypt-alpine-before
cd …
```

MONGOCRYPT-708 pass environment for Alpine task

---

cmake/ImportBSON.cmake

Resolves an observed warning when running `cmake -S. -Bcmake-build` with CMake 3.30.1:
```
CMake Warning at cmake-build/_deps/embedded_mcd-src/build/cmake/MongoSettings.cmake:176 (message):
The value of ENABLE_EXTRA_ALIGNMENT=“” is not a regular boolean value
Call Stack (most recent call first):
cmake-build/_deps/embedded_mcd-src/build/cmake/MongoSettings.cmake:269 (mongo_setting)
cmake-build/_deps/embedded_mcd-src/CMakeLists.txt:214 (mongo_bool_setting)
```

MONGOCRYPT-719 resolve CMake warning of non-boolean `ENABLE_EXTRA_ALIGNMENT`

---

src/mc-rangeopts-private.h
src/mongocrypt.h

Follow-up to https://github.com/mongodb/libmongocrypt/pull/867. Document `sparsity` as optional.
PR also addresses minor typo fixes in `mongocrypt.h`.

MONGOCRYPT-722 fix docstring to indicate `sparsity` is optional.

---

.evergreen/config.yml
bindings/python/pymongocrypt/asynchronous/state_machine.py
bindings/python/test/test_mongocrypt.py

The signature in pymongo is `async def fetch_keys(self, filter: bytes) -> AsyncGenerator[bytes, None]`

PYTHON-4670 Fix handling of AsyncMongoCryptCallback.fetch_keys

---

src/mongocrypt.h

Motivated by question about expected lifetime of `mongocrypt_kms_ctx_t` with respect to `mongocrypt_ctx_t` ([see slack](https://mongodb.slack.com/archives/C0668RJBA0J/p1724089719861209)).
Calling `mongocrypt_ctx_destroy (ctx)` [frees](https://github.com/mongodb/libmongocrypt/blob/d05dbf3c0d6e03da8c0b25a6fd0214c1165f9214/src/mongocrypt-key-broker.c#L1117) associated `mongocrypt_kms_ctx`'s.

clarify lifetime of returned `mongocrypt_kms_ctx_t`

---

.evergreen/config.yml

**Description:** 
This PR adds tag-based publishing to the `upload-java`, matching the functionality of the `upload-all` task. It integrates the "fetch source" function to assign release tags properly to the "use-tag" variable.
As we move the Java binding into the `mongo-java-driver` repository, using release tags to locate binaries will help ensure that we depend on the correct binaries. This approach is clearer and more informative than specifying revisions in build scripts of `mongo-java-driver`.
Links:
Current publishing demonstration: [Evergreen release task](https://parsley.mongodb.com/evergreen/libmongocrypt_release_ubuntu2004_64_upload_java_9a88ac5698e8e3ffcd6580b98c247f0126f26c40_24_08_01_18_30_17/0/task?bookmarks=0,61&shareLine=49)
JAVA-5590

Add fetch source to upload-java for tag-based uploads.

---

integrating.md
kms-message/README.md
src/mc-fle-blob-subtype-private.h

Followup to https://github.com/mongodb/mongo-c-driver/pull/1746 which address kms-divergence-check task failure in C Driver EVG builds + similar updates to specification links.

Update references to Markdown MongoDB specifications

---

src/mongocrypt-key-broker.c
src/mongocrypt-kms-ctx.c
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt-datakey.c

Follow-up to https://github.com/mongodb/libmongocrypt/pull/783. Retry oauth requests on network or transient HTTP errors.
Verified by this patch build: https://spruce.mongodb.com/version/66fefa4733b962000781f45c
Retrying oauth requests was a [non-goal of the scope](https://jira.mongodb.org/browse/WRITING-18063). However, extending the retry mechanism to oauth requests was not much effort. It may further improve the success rate of KMS requests. I expect oauth requests are safe to retry.

MONGOCRYPT-599 retry oauth requests

---

src/mongocrypt-ciphertext.c
src/mongocrypt-ctx-encrypt.c
src/mongocrypt-key-broker.c
src/mongocrypt-log.c
src/mongocrypt-marking.c

Remove/replace unnecessary memset calls.
Verified by [this patch](https://spruce.mongodb.com/version/67041413723f3f000708f57e)
**Background & Motivation**
This PR is intended to address point 5 in audit identified in MONGOCRYPT-686. The memset calls are not intended to securely zero out memory. Securing process memory is a non-goal of libmongocrypt (per MONGOCRYPT-89). This PR was motivated by [discussion addressing the audit](https://docs.google.com/document/d/1vEifWIhZrwJjiS4WrVo7ZI09kpZJH1a0gOTEVJPeobE/edit?disco=AAABWsDJGHk).

MONGOCRYPT-726 Remove/replace unnecessary memset calls.

---

src/mongocrypt-opts.c
test/example-state-machine.c
test/test-mongocrypt-assert-match-bson.h
test/test-mongocrypt-kek.c
test/test-mongocrypt-key-cache.c

Replace use of the soon-to-be-deprecated `bson_as_json` with `bson_as_relaxed_extended_json`.
CDRIVER-5700 plans to deprecate `bson_as_json` due to producing Legacy Extended JSON by default. libmongocrypt's use of `bson_as_json` appears limited to logging and tests. Calls are updated to use the portable Relaxed Extended JSON format (rather than preserve the Legacy Extended JSON format).

MONGOCRYPT-724 remove use of `bson_as_json`

---

.evergreen/config.yml
src/mc-fle2-encryption-placeholder-private.h
src/mc-fle2-find-range-payload-private-v2.h
src/mc-fle2-insert-update-payload-private-v2.h
src/mc-fle2-rfds-private.h
src/mc-rangeopts-private.h
src/mongocrypt-ctx-private.h
src/mongocrypt-ctx.c
src/mongocrypt-key-private.h
src/mongocrypt-key.c
src/mongocrypt-marking-private.h
test/test-mongocrypt.h

- Fix alignment errors reported by UBSan.
- Add a UBSan task to Evergreen.
This PR is hopefully intended to address the reported errors in MONGOCRYPT-725 by addressing reported UBSan errors like the following:
```
cmake-build/_deps/embedded_mcd-src/src/libbson/src/bson/bson.c:1778:10: runtime error: member access within misaligned address 0x000131f052b0 for type 'bson_impl_inline_t', which requires 128 byte alignment
0x000131f052b0: note: pointer points here
00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
^
```
The UBSan errors appear due to dynamic allocation of structs containing libbson types defined with a default 128-byte alignment: `bson_t` and `bson_iter_t`. This only appeared to impact `mongocrypt_ctx_t` and …

MONGOCRYPT-725 fix UBSan alignment errors

---

test/test-mc-fle2-payload-iup-v2.c
test/test-mc-range-mincover.c
test/test-mongocrypt-ctx-rewrap-many-datakey.c

Observed when running the test suite locally while reviewing https://github.com/mongodb/libmongocrypt/pull/901. It is unclear why these are not being caught by the sanitizer tasks on Evergreen.

Address memory leaks in test suite

---

.evergreen/config.yml
CHANGELOG.md

Partially resolves MONGOCRYPT-688. Drop PPA packaging task RHEL 6.
The `publish-packages` task is failing on RHEL 6. Publishing to RHEL 6 is disabled ([see slack thread](https://mongodb.slack.com/archives/C04LGNQV4M7/p1730404465788919)). Re-enabling can be requested, but this PR takes the opportunity to drop PPA packages for RHEL 6.
As a result users will be unable to install [with these steps](https://www.mongodb.com/docs/manual/core/csfle/reference/libmongocrypt/#redhat) on RHEL 6. But they can still build from source (at least until MONGOCRYPT-688 is fully resolved).
This PR does not-yet drop support for building on RHEL 6. Users can continue to build from source. CHANGELOG.md is updated to warn about dropping support of RHEL 6 entirely in the future.

MONGOCRYPT-688 drop RHEL 6 packaging task

---

.evergreen/config.yml
.evergreen/earthly.sh
Earthfile

This PR is intended to address rate-limiting errors pulling from dockerhub causing task failures on Evergreen. [Example](https://spruce.mongodb.com/task/libmongocrypt_alpine_amd64_earthly_build_with_earthly_b150e745c573793e7d27568f4be2d6f83d879f82_24_11_15_14_38_07/logs?execution=0):
> docker: Error response from daemon: toomanyrequests: Too Many Requests (HAP429).
[DEVPROD-12779](https://jira.mongodb.org/browse/DEVPROD-12779) [notes](https://jira.mongodb.org/browse/DEVPROD-12779?focusedCommentId=6856395&focusedId=6856395&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6856395):
> In the meantime there is an artifactory mirror for dockerhub that can be used for pull containers.
Running `docker pull …

Use Artifactory for image registry

---

src/mc-tokens-private.h
src/mc-tokens.c
test/test-mc-tokens.c

This PR adds a new function `_new_from_buffer_copy` to `mc-tokens`. 
The existing function `_new_from_buffer` performs a shallow copy on the `src` buffer where the data pointer value is simply copied to the `dst` buffer. This seems to be an explicit decision according the [PR](https://github.com/mongodb/libmongocrypt/pull/514) where this function was added.
Part of the [`FLEToken` refactor ](https://jira.mongodb.org/browse/SERVER-96316) in the server necessitates a constructor that creates a token from a buffer. Because we cannot guarantee that the buffer passed in won't be deleted throughout the lifetime of the program, we must deep copy it to ensure that there isn't an access of stale/deleted data in the token object.

MONGOCRYPT-743 implement token _new_from_buffer_copy 

---

.evergreen/config.yml
CHANGELOG.md

This commit bumps our builds from MacOS 10.14 to MacOS 11. 10.14 has been
unsupported for several years. MacOS 11 is also EOL, but it seems to pass
all of our tests and isn't quite as old as 10.14. I tried to bump all the
way to MacOS 14, but ran into some kind of linking error. I think we can
return to that upgrade at a different time.

DEVPROD-6063: update to macos 11

---

README.md
integrating.md

I expect the design rationale is not relevant to most non-developer users.

relocate and reword design rationale

---

doc/releasing.md

Applies similar changes from https://github.com/mongodb/mongo-cxx-driver/pull/1282: Add release process step to update the GitHub Webhook.
**Background**
Updating the `debian/unstable` branch may result in Jira ticket comments for commits added to the branch ([example](https://jira.mongodb.org/browse/MONGOCRYPT-696?focusedCommentId=6633671&focusedId=6633671&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6633671)). I expect this is not helpful, and results in unnecessary emails.
The [webhook](https://github.com/mongodb/libmongocrypt/settings/hooks) is now updated to limit updates to `master` and `r1.12`:
```
https://githook.mongodb.com?branches=master..r1.29
```
Consequently, the webhook must be updated when new release branches are created.

add release instruction to update webhook

---

bindings/python/pymongocrypt/binding.py
bindings/python/pymongocrypt/mongocrypt.py

PYTHON-4992 Support retrying KMS requests.
The mongocrypt <1.12 code can be removed once we update the min required version.

PYTHON-4992 Support retrying KMS requests

---

integrating.md

Suggest wrapping the error when `mongocrypt_kms_ctx_fail` returns false. This may help users identify the cause of a network error.

MONGOCRYPT-752 suggest wrapping error

---

.evergreen/init.sh
CONTRIBUTING.md
etc/format.sh

- Update formatting script for Python 3.12
- Add CONTRIBUTING.md
- Relocate design rationale from README.md to integrating.md
The formatting script is updated to address an observed error on Python 3.12:
```
$ bash etc/format-all.sh
Traceback (most recent call last):
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pkg_resources'
```
The error comes from this check:
```
run_python -c 'import pkg_resources; pkg_resources.require("pipx>=0.17.0,<2.0")'
```
`pkg_resources` is removed in Python 3.12. I expect that check is not strictly needed. This check has been removed.
A `MONGOCRYPT_PYTHON` environment variable is added to specify an override python version. This is documented in a new CONTRIBUTING.md document.

Fix format script

---

kms-message/src/kms_message.c
kms-message/src/kms_message_private.h

set_error is an awful generic name for a global function.
Sadly this easily conflicts with other libraries if you statically link this into an application.
please have us rename set_error to kms_set_error to avoid link errors with libraries/applications that also have set_error as function.

MONGOCRYPT-760 Rename `set_error` to `kms_set_error`

---

.github/workflows/release-python.yml

We had the environment name wrong, and we need to coerce the dry_run flag to a string for comparision.

PYTHON-5017 Fix handling of post-publish step again

---

.evergreen/config.yml
.evergreen/linker-tests.sh
.evergreen/pkgconfig-tests.sh
.lsan-suppressions
CHANGELOG.md
cmake/ImportBSON.cmake
test/test-mc-fle2-tag-and-encrypted-metadata-block.c

- Fix Evergreen config to apply `-fsanitize=address`.
- Suppress `dlerror` leak. Fix test leaks.
- Restore default of `ENABLE_EXTRA_ALIGNMENT=OFF` to imported libbson.
Verified by this [patch build](https://spruce.mongodb.com/version/676571030624120007db3430/).
As a drive-by fix, the unused `build-and-test-asan-s390x` is removed.
https://github.com/mongodb/libmongocrypt/pull/622 accidentally disabled ASan due to a bash comment (`# Add ...`) appearing in a folded (`>-`) YAML block:
```yaml
compile_env: >-
${compile_env|}
LIBMONGOCRYPT_EXTRA_CFLAGS="-fsanitize=address -pthread"
ASAN_OPTIONS="detect_leaks=1 detect_odr_violation=0"
```
This PR moves the comment outside of the block to fix:
```yaml
compile_env: >-
${compile_env|}
LIBMONGOCRYPT_EXTRA_CFLAGS="-fsanitize=address -pthread" …
```

MONGOCRYPT-731 re-enable ASan tasks

---

kms-message/test/test_kmip_reader_writer.c
kms-message/test/test_kms_assert.h
kms-message/test/test_kms_azure_online.c
kms-message/test/test_kms_gcp_online.c
kms-message/test/test_kms_request.c
test/test-mc-fle2-payload-iev-v2.c
test/test-mc-fle2-payload-iev.c
test/test-mc-fle2-payload-iup-v2.c
test/test-mc-fle2-payload-iup.c
test/test-mc-fle2-payload-uev.c
test/test-mc-fle2-rfds.c
test/test-mc-range-edge-generation.c
test/test-mc-range-encoding.c
test/test-mc-range-mincover.c
test/test-mc-rangeopts.c
test/test-mc-tokens.c
test/test-mongocrypt-assert-match-bson.c
test/test-mongocrypt-assert.h
test/test-mongocrypt-cache.c
test/test-mongocrypt-crypto-hooks.c
test/test-mongocrypt-crypto.c
test/test-mongocrypt-ctx-decrypt.c
test/test-mongocrypt-ctx-encrypt.c
test/test-mongocrypt-kek.c
test/test-mongocrypt-key-cache.c
test/test-mongocrypt-kms-responses.c
test/test-mongocrypt-marking.c
test/test-mongocrypt.c

- Increase sleep time in `_test_encrypt_cache_expiration`.
- Flush stdout and stderr in tests to fix test log output.
Verified by this [patch build](https://spruce.mongodb.com/version/677e86c33b8c4a0007633e5e). The `debian-package-build*` task failures appear unrelated.
The sleep time in `_test_encrypt_cache_expiration` is increased from 2ms to 10ms to address observed test failures on [Windows tasks](https://spruce.mongodb.com/task/libmongocrypt_windows_test_build_and_test_shared_bson_patch_0727c321e4982446ea235cb613976b68c694b4a8_6777edfd528c89000717db3b_25_01_03_14_02_38/logs?execution=0). I expect this is due to the coarse resolution of `bson_get_monotonic_time` on Windows: CDRIVER-4526. `bson_get_montonic_time` is used to [check the current …

increase sleep time in cache test and flush test output

---

.evergreen/config.yml
.evergreen/create-packages-and-repos.sh

To fix an observed error on [RHEL 7.1 ppc64el](https://spruce.mongodb.com/task/libmongocrypt_rhel_71_ppc64el_build_and_test_and_upload_5b381e9968cdc8d39fbad7ef9bd60c38bd838c41_25_01_09_21_28_37/logs?execution=0):
```
/opt/mongodbtoolchain/v3/bin/python3: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/mongodbtoolchain/revisions/69f4f0673ffcb290ce2307560a4883ecf2ad138c/stow/openssl.Dd4/lib/libcrypto.so.1.1)
```
Verified by this [patch build](https://spruce.mongodb.com/version/678664ae6eb3120007b4e83f).
Uses the find-python3 script from drivers-evergreen-tools to find a working version of Python on the host.

use script from drivers evergreen tools to find python

---

kms-message/src/kms_request.c

```
kms/kms_request.c:792:14: warning: initialization of pointer of type
'char *' to null from a constant boolean expression
[-Wbool-conversion]
return false;
^~~~~
kms/kms_request.c:860:14: warning: initialization of pointer of type
'char *' to null from a constant boolean expression
[-Wbool-conversion]
return false;
^~~~~
kms/kms_request.c:864:14: warning: initialization of pointer of type
'char *' to null from a constant boolean expression
[-Wbool-conversion]
return false;
^~~~~
```

MONGOCRYPT-766 Fix compilation in C23

---

src/mongocrypt-ctx-encrypt.c
src/mongocrypt-ctx-private.h
test/test-mongocrypt-ctx-encrypt.c

Do not error if remote `$jsonSchema` has sibling fields.
When processing a response to `listCollections`, libmongocrypt only checks the response for a top-level `$jsonSchema` within `validator`.
libmongocrypt errors if the `$jsonSchema` has sibling fields and query analysis (mongocryptd/crypt_shared) indicates the JSON Schema has encrypted fields:
```python
db.command({
"create": "coll",
"validator": {
"$jsonSchema": csfle_schema, # Defines 'secret' as encrypted.
"secret": "foo" # Sibling validator contradicts the JSON schema.
}
})
encrypted_db["coll"].find_one({}) # Error: schema requires encryption, but collection JSON schema validator has siblings
```
The [spec says this of the motivation](https://github.com/mongodb/specifications/blob/d9b434db87abec375df46864d4fedb2297bc80ec/source/cli …

MONGOCRYPT-771 Remove check for `$jsonSchema` siblings

---

src/mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-encrypt.c

Do not warn if local schema does not require encryption
Verified by this patch build: https://spruce.mongodb.com/version/679f718a7f3b450007729cee
libmongocrypt currently logs a warning if a response from query analysis (mongocryptd/crypt_shared) indicates a local schema does not require encryption. However, this log is generated even for an empty local schema. I do not expect configuring an empty local schema to be discouraged. Quoting [the spec](https://github.com/mongodb/specifications/blob/d9b434db87abec375df46864d4fedb2297bc80ec/source/client-side-encryption/client-side-encryption.md):
> Drivers MUST document that a local schema is more secure
I expect this warning was intended to inform users that non-encryption JSON schema validation does not apply. However, mongocryptd already …

MONGOCRYPT-770 do not warn if local schema does not require encryption

---

.github/workflows/release-python.yml

Error seen during overnight build: https://github.com/mongodb/libmongocrypt/actions/runs/13172517847
[Invalid workflow file: .github/workflows/release-python.yml#L73](https://github.com/mongodb/libmongocrypt/actions/runs/13172517847/workflow)
error parsing called workflow ".github/workflows/release-python.yml" -> "./.github/workflows/codeql.yml" : failed to fetch workflow: workflow was not found.

PYTHON-5047 Fix static scan in release process

---

etc/cyclonedx.sbom.json

Resolves MONGOCRYPT-776 for the master branch.
> [!NOTE]
> This PR (and related) only update the purls and SBOM Lite document as needed. Updates to release processes and scripts are deferred to a separate PR.
The CycloneDX specification for the `serialNumber` field [states](https://cyclonedx.org/docs/1.6/json/json/#serialNumber):
> Every BOM generated SHOULD have a unique serial number, even if the contents of the BOM have not changed over time. If specified, the serial number must conform to [RFC 4122](https://www.ietf.org/rfc/rfc4122.html). Use of serial numbers is recommended.
Our release processes up to this point have been updating the SBOM Lite document by bumping the `version` field on each release and reusing the same serial number for all releases (using `serialNumber` only to …

MONGOCRYPT-776 Regenerate SBOM Lite for silkbomb:2.0 forward compatibility

---

.github/workflows/release-python.yml

Passing release build: https://github.com/mongodb/libmongocrypt/actions/runs/13442504103/job/37560307343

PYTHON-5141 Update SBOM usage for Kondukto

---

src/mc-schema-broker.c

Fix an (unreleased) bug discovered by Coverity with ID [171701](https://coverity.corp.mongodb.com/#/project-view/20156/10050?selectedIssue=171701).
Intended to unblock the upcoming 1.13.0 release.

MONGOCRYPT-768 remove possible double-free

---

kms-message/CMakeLists.txt

Related to MONGOCRYPT-783.
kms-message [sets](https://github.com/mongodb/libmongocrypt/blob/9378602db9d57ab82e47f8eee7bdd212c7234026/kms-message/CMakeLists.txt#L7) `CMAKE_C_STANDARD` to `90` despite extensively using C99 features.
This is also despite both [libmongocrypt](https://github.com/mongodb/libmongocrypt/blob/95f8281e98e65a08c9e529090e174e2249037202/CMakeLists.txt#L19) and the (bundled) [C Driver](https://github.com/mongodb/mongo-c-driver/blob/9b19be93f114a96ece47b7530e5e60e7a0512cae/CMakeLists.txt#L403) already requiring C99.
Raising the C standard to C99 addresses the following warnings:
- Clang:
- `-Wc99-extensions` for `_Bool`: 145 unique, 3532 total.
- `-Wlong-long`: 11 unique, 67 total.
- `-Wvariadic-macros`: 6 unique, 117 total.
- `-Woverlength-strings`: 1 unique, 1 total. …

MONGOCRYPT-783 set CMAKE_C_STANDARD=99 for kms-message

---

src/mongocrypt-ctx-encrypt.c

Resolves MONGOCRYPT-784.
Followup to https://github.com/mongodb/libmongocrypt/pull/954, which introduced a by-value `bson_iter_t` parameter for [find_collections_in_pipeline](https://github.com/mongodb/libmongocrypt/blob/33fdf65cce5a0c0cdd293c64ed40e4a8205c3ce0/src/mongocrypt-ctx-encrypt.c#L2242) which triggers the following MSVC warning when `ENABLE_EXTRA_ALIGNMENT` is enabled for the bson library:
```
error C2719: 'pipeline_iter': formal parameter with requested alignment of 128 won't be aligned
```

MONGOCRYPT-784 avoid passing over-aligned bson_iter_t by value in parameters

---

src/mongocrypt-ctx-encrypt.c

Building libmongocrypt on Linux from the current master commit 8270531 was unsuccessful. The following error was produced.
````{verbatim, lang = "markdown"}
[ 22%] Building C object CMakeFiles/mongocrypt.dir/src/mongocrypt-ctx-encrypt.c.o
In file included from libmongocrypt/src/mongocrypt-opts-private.h:27,
from libmongocrypt/src/mongocrypt-key-private.h:22,
from libmongocrypt/src/mongocrypt-cache-key-private.h:22,
from libmongocrypt/src/mongocrypt-key-broker-private.h:24,
from libmongocrypt/src/mongocrypt-ctx-private.h:26,
from libmongocrypt/src/mongocrypt-ctx-encrypt.c:22:
libmongocrypt/src/mongocrypt-ctx-encrypt.c: In function ‘_mongo_op_collinfo’:
libmongocrypt/src/mongocrypt-ctx-encrypt.c:43:74: error: incompatible type for argument 1 of ‘tmp_json’
43 | …
```

MONGOCRYPT-786 Fix incompatible type error

---

test/test-mongocrypt.c
test/test-mongocrypt.h

Make `tester` object `static` to avoid large stack object.
The test runner uses fixed size arrays for [temporary data](https://github.com/mongodb/libmongocrypt/blob/c3dff011c9c0dc326c31414471a4b613e0d91365/test/test-mongocrypt.h#L49-L51):
```c
/* Arbitrary max of 2048 instances of temporary test data. Increase as needed.
*/
#define TEST_DATA_COUNT 2048
```
Increasing this array was needed for tests added in MONGOCRYPT-723. However, increasing this array to 3000 resulted in an [observed segfault](https://spruce.mongodb.com/task/libmongocrypt_windows_test_build_and_test_and_upload_patch_c3dff011c9c0dc326c31414471a4b613e0d91365_67af5a0f2ac9680007bb2b31_25_02_14_14_58_23/logs?execution=0) on Windows tests.
With this PR, this [patch build](https://spruce.mongodb.com/task/libmongocrypt_windows_t …

MONGOCRYPT-775 make `tester` object `static`

---

.evergreen/config.yml

Add downloads for the libmongocrypt-all.tar.gz for the latest stable and unstable tagged releases.
The 1.13.0 release was manually uploaded and is accessible by:
https://mciuploads.s3.amazonaws.com/libmongocrypt/all/latest/stable/libmongocrypt-all.tar.gz
Once available, latest unstable releases are expected to accessible by:
https://mciuploads.s3.amazonaws.com/libmongocrypt/all/latest/unstable/libmongocrypt-all.tar.gz
Requested in MONGOCRYPT-764.

MONGOCRYPT-764 add latest downloads

---

CMakeLists.txt
src/mongocrypt.c
test/test-mongocrypt-csfle-lib.c

- Improve error message when loading incorrect library for crypt_shared.
- Change "CSFLE" to "crypt_shared" in log and error messages to match the library rename in MONGOCRYPT-434.
Verified with this [Evergreen patch](https://spruce.mongodb.com/version/67c85a9a61fd92000765f040).
https://jira.mongodb.org/browse/MONGOCRYPT-738 references several reports of users accidentally passing the path to libmongocrypt instead of the crypt_shared library. This produces an error message like:
```
A CSFLE override path was specified [./cmake-build/libmongocrypt.dylib], but we failed to open a dynamic library at that location. Load error: [(null)]
```
With this PR, accidentally passing a path to libmongocrypt results in an error like:
```
Tried to load crypt_shared dynamic library at path …
```

MONGOCRYPT-738 Improve error on failure to load crypt_shared

---

bindings/python/CHANGELOG.rst
bindings/python/pymongocrypt/mongocrypt.py
bindings/python/pymongocrypt/options.py
bindings/python/test/test_mongocrypt.py

PYTHON-5191 Add key_expiration_ms option for DEK cache lifetime

PYTHON-5191 Add key_expiration_ms option for DEK cache lifetime

---

.evergreen/config.yml
.evergreen/earthly.sh
Earthfile

Follow-up to https://github.com/mongodb/libmongocrypt/pull/911
Use of Artifactory is likely the cause of frequently encountered HTTP errors ([example](https://spruce.mongodb.com/task/mongo_c_driver_alpine3.17_clang_check:sasl=Cyrus%C2%A0%E2%80%A2%C2%A0tls=OpenSSL%C2%A0%E2%80%A2%C2%A0test_mongocxx_ref=r3.9.0_patch_c186295845d80a6047fd7ba6b7fde56567080ab9_67d03ad1274f720007fd9433_25_03_11_13_29_55/logs?execution=0)). Quoting [slack](https://mongodb.slack.com/archives/C0V7VEU15/p1741630372464459):
> Our Artifactory cluster is just three hosts, and they run really hot.
Using Artifactory is not needed. Quoting [DEVPROD-12970](https://jira.mongodb.org/browse/DEVPROD-12970):
> We're unblocked for now after Docker agreed to add our IPv6 block to their allowlist
Unqualified images names (e.g. …

MONGOCRYPT-747 Use less Artifactory for Earthly images

---

src/mc-fle2-encryption-placeholder.c
src/mc-fle2-find-equality-payload-v2.c
src/mc-fle2-find-equality-payload.c
src/mc-fle2-insert-update-payload-v2.c
src/mc-fle2-insert-update-payload.c
test/test-mc-fle2-encryption-placeholder.c
test/test-mc-fle2-find-equality-payload-v2.c
test/test-mc-fle2-payload-iup-v2.c
test/test-mc-fle2-payload-iup.c

Fixes a possible double-free on failure to parse in:
- `mc_FLE2EncryptionPlaceholder_parse`
- `mc_FLE2FindEqualityPayload_parse`
- `mc_FLE2FindEqualityPayloadV2_parse`
- `mc_FLE2InsertUpdatePayload_parse`
- `mc_FLE2InsertUpdatePayloadV2_parse`
Verified by this patch build: https://spruce.mongodb.com/version/67d42734867d07000729edd7
Bug identified in https://github.com/mongodb/libmongocrypt/pull/985#discussion_r1985700576. This PR proposes removing the repeated calls to `*_cleanup`.
Callers are expected to always call `*_cleanup`. This is intended to simplify cleanup, e.g. with the `goto fail` pattern:
```c
mc_FLE2EncryptionPlaceholder_t out;
mc_FLE2EncryptionPlaceholder_init (&out);
if (!mc_FLE2EncryptionPlaceholder_parse(&out, in, status)) {
goto fail;
}
// ... use `out` ...
fail: …
```

MONGOCRYPT-794 fix possible double free on parse error

---

.evergreen/linker-tests.sh
.evergreen/prep_c_driver_source.sh
CHANGELOG.md
cmake/FetchMongoC.cmake
etc/cyclonedx.sbom.json
etc/libbson-remove-GCC-diagnostic-in-functions.patch
etc/libbson-remove-GCC-diagnostic-pragma.patch
etc/purls.txt

Update downloaded libbson version from 1.28.1 to 1.30.3.
Verified with this patch build: https://spruce.mongodb.com/version/67f51fcc5e1706000725b5ab
See MONGOCRYPT-797. Intended to include CDRIVER-5967 fix Homebrew install of libmongocrypt.
libbson is updated to 1.30 instead of 2.0 to avoid disrupting package releases. The Fedora package [builds with a system install of libbson](https://src.fedoraproject.org/rpms/libmongocrypt/blob/rawhide/f/libmongocrypt.spec#_75) and does not-yet appear to have a libbson package for 2.0 to depend on.

MONGOCRYPT-797 bump libbson to 1.30.3

---

doc/releasing.md
etc/cyclonedx.sbom.json

- Regenerate SBOM serial number.
- Tweak release process steps related to SBOM serial number generation.
Tweaks to the SBOM serial number generation are intended to apply this behavior:
- After a patch release (`x.y.z`) regenerate the serial number on the release branch `rx.y` (for the next patch release).
- After a non-patch release (`x.y.0`), regenerate serial number on the release branch `rx.y` (for the next patch release) and the master branch (for the next non-patch release).

Bump SBOM serial number post 1.13.2

---

CODEOWNERS

To meet requirement of DRIVERS-3098.
This PR is intends to keep `dbx-python` ownership over `bindings/python`, and use `dbx-c-cxx` for the rest. Quoting https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file:
> the last matching pattern takes the most precedence.

add CODEOWNERS for all source

---

.github/workflows/codeql-actions.yml
.github/workflows/release-python.yml

Test run: https://github.com/mongodb/libmongocrypt/actions/runs/14640361406 (test pypy failure is unrelated).

PYTHON-5348 Run GitHub Actions Scan as Part of Python Release

---

etc/calc_release_version.py
etc/calc_release_version_selftest.sh

Pulls in changes from https://github.com/mongodb/mongo-c-driver/commit/2bf9d591d63dfc079ce7319d570dcbf0b4bdbac4 to address [task failure](https://spruce.mongodb.com/task/libmongocrypt_rhel_80_64_bit_build_and_test_and_upload_681217cd53af330007ca1970_25_04_30_12_30_05/logs?execution=0) on RHEL 8.0:
```
Traceback (most recent call last):
File "/data/mci/aec0510e232c633d6643661229e23039/libmongocrypt/etc/calc_release_version.py", line 43, in <module>
from packaging.version import Version as Version
ModuleNotFoundError: No module named 'packaging'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/data/mci/aec0510e232c633d6643661229e23039/libmongocrypt/etc/calc_release_version.py", line 48, in <module>
from …
```

Define Version in `calc_release_version.py`

---

src/mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-encrypt.c

Add missing transition to `MONGOCRYPT_CTX_ERROR` on failure in `mongocrypt_ctx_finalize`.
Observed reviewing libmongocrypt code during Skunkworks for possible missing state transitions.
On an error for the `mongocrypt_ctx_t` functions, libmongocrypt is expected to both return an error status and set the context state to `MONGOCRYPT_CTX_ERROR`.

MONGOCRYPT-807 Add missing error state transition

---

.evergreen/config.yml
CHANGELOG.md

Drop test task building libmongocrypt with Visual Studio 2015.
Dropping support for building libmongocrypt with Visual Studio 2015 is expected to have low impact. (Most drivers provide binaries for libmongocrypt, and PHP [does not use VS 2015](https://jira.mongodb.org/browse/MONGOCRYPT-779?focusedCommentId=7104496&focusedId=7104496&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-7104496)).

MONGOCRYPT-779 drop support Visual Studio 2015

---

README.md

I tested that aarch64/arm64 RPM packages would install by spawning an Amazon 2023 Evergreen host and following the steps, substituting `aarch64` in place of `x86_64` in the repository URL. No additional note/documentation is required for installation of Debian packages, since the repo URLs do not require the user to specify the hardware architecture (the system detects the hardware architecture and constructs the appropriate URL automatically). No updates are required to the Windows or macOS sections.

MONGOCRYPT-751 document installation of packages on arm64/aarch64

---

Earthfile

Trust Debian 10 and 11 signing keys in the Debian 9 task. Intended to fix failing Debian 9 tasks ([example](https://spruce.mongodb.com/task/libmongocrypt_debian9_arm64_earthly_build_deb_packages_with_earthly_467c6bf1538aafe43c1af4db1d085e5b25b93624_25_05_27_15_39_57/logs?execution=0)):
```
W: GPG error: http://archive.debian.org/debian stretch Release: The following signatures were invalid: EXPKEYSIG 04EE7237B7D453EC Debian Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org> EXPKEYSIG EF0F382A1A7B6500 Debian Stable Release Key (9/stretch) <debian-release@lists.debian.org> The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9
[...]
E: There were unauthenticated packages and -y was used …
```

MONGOCRYPT-815 trust newer Debian signing keys in Debian 9

---

.evergreen/config.yml
src/mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-encrypt.c

Bypasses `serverStatus` from query analysis instead of erroring.
As a drive-by fix, reduces the `exec_timeout_secs` in `release-python-linux` to fix an error observed by `evergreen validate`:
```
ERROR: task 'release-python-linux' exec timeout (216000) is too high and will be set to maximum limit (180000)
```
libmongocrypt errors if trying to auto-encrypt a command [not explicitly listed](https://github.com/mongodb/libmongocrypt/blob/0840a84aa78578b50ef586ebbb12e5318108db9b/src/mongocrypt-ctx-encrypt.c#L2207). This is intended to err towards safety: if libmongocrypt is unsure if the command might have values to encrypt reject it rather than risk sending plaintext that should be encrypted. [serverStatus](https://www.mongodb.com/docs/manual/reference/command/serverStatus/) is not expected …

MONGOCRYPT-820 bypass `serverStatus` from auto-encryption

---

src/mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-encrypt.c

The server [accepts either](https://github.com/10gen/mongo/blob/aec8c2f2dafa198ea8284885771778f1951d34f5/src/mongo/db/commands/buildinfo_common.idl#L56-L57) "buildInfo" or "buildinfo". libmongocrypt only recognizes "buildInfo". This PR adds "buildinfo".

MONGOCRYPT-822 bypass "buildinfo" command

---

CHANGELOG.md
doc/releasing.md
etc/cyclonedx.sbom.json

- Update CHANGELOG.md for 1.15.0.
- Update SBOM with new serial number.
- Refer to newer DOCSP ticket as an example in release steps.

Apply post-1.15.0 release steps

---

src/mongocrypt-ctx-encrypt.c
test/test-mongocrypt-ctx-setopt.c

Follow-up to https://github.com/mongodb/libmongocrypt/pull/1037:
- Improve error if text algorithm is set and text options are unset.
- Error (do not default) if text algorithm is set and contention factor is unset.
Verified with this patch build: https://spruce.mongodb.com/version/689201dabf203b0007a3782b
Improves the following error when setting the `textPreview` algorithm but not setting text options (via  `mongocrypt_ctx_setopt_algorithm_text`). Before:
> Error parsing FLE2TextSearchInsertSpec: must be an iterator to a document
After:
> text opts are required for textPreview algorithm
Checks the `contention` option is set. libmongocrypt currently [applies a default of 0](https://github.com/mongodb/libmongocrypt/blob/bfc1ebdd08e2a7f17bc0bd91c298d8b3cac97a58/src/mongocrypt-ctx-encrypt.c# …

MONGOCRYPT-828 improve checks for text required options

---

.evergreen/linker_tests_deps/app/CMakeLists.txt
CHANGELOG.md
CMakeLists.txt
cmake/MongoC-Warnings.cmake
kms-message/CMakeLists.txt

Resolves MONGOCRYPT-839. Prompted by the following CMake configuration error (among various other CMake compatibility warnings) on MacOS 14 arm64 (with [CMake 4.1.0](https://github.com/mongodb/mongo-cxx-driver/blob/939c33683944e0a8b3b78d1f4db13cb148392e59/.evergreen/scripts/install-c-driver.sh#L58) -> [libmongocrypt 1.13.0](https://github.com/mongodb/libmongocrypt/blob/1cf03f1fdd8fa439d43b8548b546c00ce71d1bc1/cmake/FetchMongoC.cmake#L5) -> [mongo-c-driver 1.28.1](https://github.com/mongodb/mongo-c-driver/blob/97f166d8d784d6096d48ba288f98b48028cdfe8b/src/libbson/CMakeLists.txt#L37)):
```
CMake Error at cmake-build/_deps/embedded_mcd-src/src/libbson/CMakeLists.txt:37 (cmake_policy):
Policy CMP0042 may not be set to OLD behavior because this version of CMake
no longer supports it.  The …
```

MONGOCRYPT-839 set CMake minimum required version to 3.15...4.0

---

kms-message/src/kms_b64.c
kms-message/src/kms_crypto_libcrypto.c
kms-message/src/kms_crypto_windows.c
kms-message/src/kms_gcp_request.c
kms-message/src/kms_kmip_reader_writer.c
kms-message/src/kms_kmip_request.c
kms-message/src/kms_kmip_response.c
kms-message/src/kms_kmip_response_parser.c
kms-message/test/test_kms_azure_online.c
kms-message/test/test_kms_gcp_online.c
kms-message/test/test_kms_request.c

The `kms_message` library has many unchecked calls to `malloc`/`calloc`. This PR adds missing `KMS_ASSERT` statements on the results of these calls, as well as some `ASSERT`'s in `test_kms`.

MONGOCRYPT-577 Assert non-NULL returns from malloc()-family function

---

src/mongocrypt-marking.c
src/mongocrypt-opts-private.h
src/mongocrypt-opts.c
test/test-mongocrypt-ctx-encrypt.c

Currently, libmongocrypt chooses a random value if a FLE2 field has a contention factor max greater than zero. This PR introduces a callback `contention_factor_fn` in `crypt->opts` which can be set by the internal `_mongocrypt_opts_set_contention_factor_fn`.
An additional test in `test-monongocrypt-ctx-encrypt` shows how this functionality can be used to deterministically select a contention factor.

MONGOCRYPT-824 Allow setting deterministic contention factor during FLE2 field encryption

---

.evergreen/create-packages-and-repos.sh
etc/debian/control

See description of #1083 for details.

[r1.16] use lower debhelper compat level on obsolete Debian/Ubuntu releases

---

.evergreen/create-packages-and-repos.sh
etc/debian/control

This change fixes tasks running on older Debian and Ubuntu versions. The tasks were broken by the 1.16.0-1 Debian package, which made some packaging-specific changes that resulted in the breakage.

use lower debhelper compat level on obsolete Debian/Ubuntu releases
