- bindings/python/.evergreen/test.sh
- bindings/python/pymongocrypt/binary.py
- bindings/python/pymongocrypt/binding.py
- bindings/python/pymongocrypt/crypto.py
- bindings/python/pymongocrypt/mongocrypt.py
- bindings/python/setup.py
Jira: https://jira.mongodb.org/browse/PYTHON-1925
Patch: https://evergreen.mongodb.com/version/5d4cb6062a60ed12e5dd77f6
> PYTHON-1925 Add libmongocrypt cypto hooks

- bindings/node/lib/mongocryptdManager.js
Remove connecting to mongocryptd on /tmp/mongocryptd.sock until
SERVER-41029 is resolved
> NODE: remove connecting on linux socket

- bindings/python/pymongocrypt/binding.py
Patch: https://evergreen.mongodb.com/version/5d52e4512a60ed3566194f29
Confirmed this fixes the pymongo issue because the error is delayed until the library is used:
```
$  mongo-python-driver git:(master) python
Python 3.6.1 (dab365a465140aa79a5f3ba4db784c4af4d5c195, Feb 18 2019, 10:54:17)
[PyPy 7.0.0-alpha0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
/Users/shane/git/mongo-python-driver/venvpypy3/lib-python/3/site.py:675: UserWarning: readline.read_init_file() not implemented
readline.read_init_file()
And now for something completely different: ``running tests is essential for
developing pypy -- uh? did I break the test? (fijal)''
>>>> from pymongo import encryption_options
>>>> client …
```
> PYTHON-1958 Delay OSError until the library is used

- bindings/node/lib/stateMachine.js
- bindings/node/src/mongocrypt.cc
- Corrects an error message in the bindings
- Replaces a function with a Map.
Fixes NODE-2009
> NODE: format: minor formatting changes

- bindings/node/package.json
- bindings/node/src/mongocrypt.cc
Note: based off of #53 
Fixes the Nan and v8 calls to be forwards compatible with Node 12.
Allows us to use prebuild --all which also winds up building electron
Fixes NODE-2097
>  NODE: feat(node12): add node 12 and election support

- bindings/node/README.md
- bindings/node/lib/autoEncrypter.js
- bindings/node/lib/clientEncryption.js
- bindings/node/lib/common.js
- bindings/node/lib/mongocryptdManager.js
- bindings/node/lib/stateMachine.js
Documents the public API, as well as most of the private API
of the node bindings.
Fixes NODE-2055
> NODE: docs: document the public API of the node bindings

- bindings/python/README.rst
- bindings/python/pymongocrypt/version.py
- bindings/python/setup.py
[PYTHON-1984](https://jira.mongodb.org/browse/PYTHON-1984)
> PYTHON-1984 Mention that pip 19 is required for manylinux2010

- integrating.md
Related CR for spec: https://github.com/mongodb/specifications/pull/678
> clarify endpoint format

- bindings/node/README.md
- bindings/node/index.js
- bindings/node/lib/autoEncrypter.js
- bindings/node/lib/clientEncryption.js
Updates the documentation to correct a few items, and to
set up types so that they can be leveraged by the main
driver docs
Part of NODE-2298
> NODE-2298: update documentation to synergize with driver docs

- bindings/node/lib/autoEncrypter.js
s/mongocryptURI/mongocryptdURI/
> NODE: minor documentation fix

- bindings/node/lib/mongocryptdManager.js
- bindings/node/test/mongocryptdManager.test.js
> NODE-2315: make --idleShutdownTimeoutSecs work

- .evergreen/config.yml
- bindings/node/.evergreen/setup_environment.sh
- bindings/node/binding.gyp
- bindings/node/etc/build-static.sh
This patch includes changes to our binding definitions and the build-static.sh script in order to build the addon for windows users.
NODE-2338
> feat: support building addon for windows

- bindings/java/mongocrypt/build.gradle.kts
Updated the java build to include the bnd plugin
and configured so the pom produces a META-INF/MANIFEST.MF
JAVA-3575
https://evergreen.mongodb.com/version/5e1dd218d6d80a6b51b895aa
```
$ cat META-INF/MANIFEST.MF
Manifest-Version: 1.0
Automatic-Module-Name: com.mongodb.crypt.capi
Bnd-LastModified: 1579015065704
Build-Version: 1.0.0-beta3-235-g9f6fd7c-dirty
Bundle-ManifestVersion: 2
Bundle-Name: MongoCrypt
Bundle-SymbolicName: com.mongodb.crypt.capi
Bundle-Version: 1.0.0.beta3-235-g9f6fd7c-dirty
Created-By: 11.0.5 (Private Build)
Export-Package: com.mongodb.crypt.capi;uses:="org.bson";version="1.0.0
.beta3-235-g9f6fd7c-dirty"
Import-Package: org.bson;version="[3.10,5.0)",org.bson.assertions;vers
ion="[3.10,5.0)",org.bson.codecs;version="[3.10,5.0)",org.bson.codecs …
```
> Java: Added OSGI support

- src/mongocrypt-traverse-util.c
https://jira.mongodb.org/browse/MONGOCRYPT-255
> MONGOCRYPT-255 add missing braces around struct initializer

- kms-message/test/test_kms_online_util.c
- src/mongocrypt-key-broker-private.h
- src/mongocrypt-key-broker.c
- src/mongocrypt-key-private.h
- src/mongocrypt-key.c
- src/mongocrypt-kms-ctx-private.h
- src/mongocrypt-kms-ctx.c
- test/test-mongocrypt-crypto-hooks.c
- test/test-mongocrypt-key.c
> MONGOCRYPT-274 support GCP auto/explicit en/decrypt

- test/data/key-document-azure.json
- test/data/key-document-gcp.json
- test/data/kms-tests.json
- test/test-mongocrypt-kms-responses.c
- test/test-mongocrypt.c
- test/test-mongocrypt.h
- test/util/util.c
Adds a couple small tests of mock error responses for GCP and Azure oauth.
> MONGOCRYPT-275 mock test oauth requests

- .evergreen/config.yml
Per the email "Evergreen SUSE/SLES 12 Distro update to SP5" (I just forwarded it to you), this updates the distro.
> Update suse12-test to suse12-sp5-small

- bindings/python/CHANGELOG.rst
- bindings/python/pymongocrypt/binding.py
- bindings/python/pymongocrypt/version.py
- bindings/python/release.sh
- bindings/python/test/test_binding.py
I think the error message needs to be improved and ideally, I'd like to do this without `distutils.Version.LooseVersion`.
> PYTHON-2400 Add libmongocrypt version check

- bindings/node/src/mongocrypt.cc
Fixes intermittent crashes on Node.js 14.x and above
when `Buffer::New()` happens to be called with a pointer that
has already used for another `Buffer::New()` call and the object
returned by the first call has not been garbage-collected yet.
NODE-2964
> fix: copy output buffers to libmongocrypt in Node.js bindings

- .evergreen/build_all.sh
[MONGOCRYPT-301](https://jira.mongodb.org/browse/MONGOCRYPT-301)
> fix: include bson-static-1.0.lib in Windows prebuilts

- bindings/cs/MongoDB.Libmongocrypt/MongoDB.Libmongocrypt.csproj
- bindings/cs/MongoDB.Libmongocrypt/MongoDB.Libmongocrypt.targets
EG: https://evergreen.mongodb.com/version/601895681e2d17667250abc7
> MONGOCRYPT-305: Always copy mongocrypt library to consumers.

- CODEOWNERS
Just to help get the right attention on PRs
> chore: Add a CODEOWNERS file

- bindings/node/package.json
See [NODE-3108](https://jira.mongodb.org/browse/NODE-3108).
> fix: loosen peerDependencies requirement on mongodb

- bindings/python/setup.py
- bindings/python/test-requirements.txt
https://jira.mongodb.org/browse/PYTHON-2581
> PYTHON-2581 Remove version cap on cryptography

- bindings/node/package-lock.json
- bindings/node/package.json
> chore: update prebuild-install to latest

- bindings/node/.gitignore
- bindings/node/package-lock.json
- bindings/node/package.json
- bindings/node/test/release.test.js
- Add test to ensure package contains exactly the files listed in an allow list
> fix(NODE-3326): binding.gyp missing from files list in package.json

- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptImpl.java
- bindings/java/mongocrypt/src/test/java/com/mongodb/crypt/capi/MongoCryptTest.java
> Ensure Java bindings handle multiple calls MongoCrypt#close

- bindings/cs/MongoDB.Libmongocrypt.Example/MongoDB.Libmongocrypt.Example.csproj
- bindings/cs/MongoDB.Libmongocrypt.Test/BasicTests.cs
- bindings/cs/MongoDB.Libmongocrypt.Test/CipherCallbacksTests.cs
- bindings/cs/MongoDB.Libmongocrypt.Test/HashCallbackTests.cs
- bindings/cs/MongoDB.Libmongocrypt.Test/HmacShaCallbacksTests.cs
- bindings/cs/MongoDB.Libmongocrypt.Test/MongoDB.Libmongocrypt.Test.csproj
- bindings/cs/MongoDB.Libmongocrypt.Test32/MongoDB.Libmongocrypt.Test32.csproj
- bindings/cs/MongoDB.Libmongocrypt/BinarySafeHandle.cs
- bindings/cs/MongoDB.Libmongocrypt/CipherCallbacks.cs
- bindings/cs/MongoDB.Libmongocrypt/ContextSafeHandle.cs
- bindings/cs/MongoDB.Libmongocrypt/HashCallback.cs
- bindings/cs/MongoDB.Libmongocrypt/HmacShaCallbacks.cs
- bindings/cs/MongoDB.Libmongocrypt/LibraryLoader.cs
- bindings/cs/MongoDB.Libmongocrypt/MongoCryptSafeHandle.cs
- bindings/cs/MongoDB.Libmongocrypt/MongoDB.Libmongocrypt.csproj
- bindings/cs/MongoDB.Libmongocrypt/OperatingSystemHelper.cs
- bindings/cs/MongoDB.Libmongocrypt/StatusSafeHandle.cs
- bindings/cs/Scripts/build.cake
> MONGOCRYPT-327: Update minimum .NET & .NET Standard version.

- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CAPI.java
- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoKeyDecryptor.java
- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoKeyDecryptorImpl.java
- bindings/java/mongocrypt/src/test/java/com/mongodb/crypt/capi/MongoCryptTest.java
> New bindings to support KMIP

- bindings/python/CHANGELOG.rst
- bindings/python/pymongocrypt/binding.py
- bindings/python/pymongocrypt/mongocrypt.py
- bindings/python/test/test_mongocrypt.py
Update binding for libmongocrypt 1.3.0.
> PYTHON-3002 Add MongoCryptKmsContext.kms_provider property

- bindings/python/setup.py
- bindings/python/test/test_mongocrypt.py
Test suite now passes with pymongo 3.11, 3.12, and 4.0.
> PYTHON-3006 Support testing with PyMongo 4 and >=3.11

- bindings/node/CHANGELOG.md
- bindings/node/package-lock.json
- bindings/node/package.json
Release commit and tag for the Node beta 1 release.
> chore(release): 2.0.0-beta.1

- .evergreen/build_install_bson.sh
- .evergreen/config.yml
- .evergreen/linker-tests.sh
- .evergreen/pkgconfig-tests.sh
- .evergreen/prep_c_driver_source.sh
- bindings/node/.evergreen/find_cmake.sh
- bindings/node/.evergreen/setup_environment.sh
- etc/packager.py
Full Evergreen patch build: https://spruce.mongodb.com/version/61cca7ea32f4177dc78c10ec/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> MONGOCRYPT-362 build and publish packages on Amazon Linux 2 arm64

- .evergreen/config.yml
- bindings/node/.evergreen/prebuild.sh
- bindings/node/.evergreen/setup_environment.sh
Add the `build-and-test-node` task to macOS M1 config.
> feat: build and test node on m1 NODE-3631

- CMakeLists.txt
- src/mlib/error.h
- src/mlib/path.h
- src/mlib/str.h
- src/mlib/thread.h
- src/mlib/windows-lean.h
> [MONGOCRYPT-390] No global WIN32_LEAN_AND_MEAN required

- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CAPI.java
- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptContext.java
- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptContextImpl.java
- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptImpl.java
- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptOptions.java
- bindings/java/mongocrypt/src/test/java/com/mongodb/crypt/capi/MongoCryptTest.java
> Support on-demand credentials in the Java binding

- CODEOWNERS
Needed some name updates to this file, took the liberty of fixing python's as well, lmk if you want a different list of folks 🙂
> chore: update codeowners file

- bindings/node/lib/autoEncrypter.js
- bindings/node/src/mongocrypt.cc
- bindings/node/src/mongocrypt.h
- bindings/node/test/autoEncrypter.test.js
Node.js driver typings: https://github.com/mongodb/node-mongodb-native/pull/3179
> feat(NODE-4085): add Node.js csfle shared library option support

- .evergreen/config.yml
- bindings/java/mongocrypt/build.gradle.kts
This ensures that the M1 processor is supported
MONGOCRYPT-418
> Download universal MacOS shared library

- README.md
The curl command in the master branch does not follow redirect request , this commit add --location to the curl command in the readme file.
> Add location redirection to curl command

- CHANGELOG.md
- README.md
- bindings/java/mongocrypt/build.gradle.kts
This cherry-picks three commits from the r1.4 branch onto master.
> Post 1.4 cherry-picks

- README.md
- bindings/java/mongocrypt/build.gradle.kts
update release process to note updating this URL
> update release URL in build.gradle.kts

- CMakeLists.txt
- src/csfle-markup.cpp
- src/mlib/str.h
This is a small single-file command-line app that eats a JSON document and feeds it to `csfle`, then spits the result back out. Handy for debugging.
> A csfle-markup utility

- bindings/node/index.d.ts
- bindings/node/lib/clientEncryption.js
- bindings/node/lib/stateMachine.js
- bindings/node/src/mongocrypt.cc
- bindings/node/src/mongocrypt.h
- bindings/node/test/clientEncryption.test.js
spec PR: https://github.com/mongodb/specifications/pull/1213
> feat(NODE-4241): add support for rewrapManyDataKey and keyMaterial

- bindings/node/test/clientEncryption.test.js
FLE2 tests need to use majority write concern.
> test(NODE-4254): use majority write concern

- test/test-mongocrypt-ctx-encrypt.c
Should have merged back before merging #368
> MONGOCRYPT-441: Update use of removed API

- bindings/node/index.d.ts
Marks previous experimental options as beta/Public Technical Preview.
> feat(NODE-4294): mark queryable encryption options beta

- README.md
- Update Linux distro versions before branching
The README should be updated on the master branch.
> Update Linux distro versions before branching

- bindings/node/index.d.ts
- bindings/node/lib/clientEncryption.js
Merged spec PR: https://github.com/mongodb/specifications/pull/1265
> fix(NODE-4342): remove createKey() in favor of createDataKey()

- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/CAPI.java
- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCrypt.java
- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoCryptImpl.java
- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoDataKeyOptions.java
- bindings/java/mongocrypt/src/main/java/com/mongodb/crypt/capi/MongoRewrapManyDataKeyOptions.java
Added RewrapManyDataKey support and MongoRewrapManyDataKeyOptions
JAVA-4433
> JAVA: Key management API

- bindings/java/mongocrypt/build.gradle.kts
This update is required after the change proposed in #409.  Once that PR is merged then I will merge this PR.
> fix Java bindings version

- src/mongocrypt-ctx-rewrap-many-datakey.c
This resolves MONGOCRYPT-464.
When https://github.com/mongodb/libmongocrypt/pull/289 resolved handling multiple rounds of KMS requests during _encryption_, the need to ensure the same behavior during _decryption_ was overlooked. This PR ensures multiple rounds of KMS requests during datakey decryption are handled correctly.
See MONGOCRYPT-464 for more detail.
> MONGOCRYPT-464 Fix datakey decryption requiring multiple rounds of KMS requests

- .evergreen/config.yml
- bindings/java/mongocrypt/build.gradle.kts
> Java: Ensure mac universal libs are published

- bindings/python/pymongocrypt/mongocrypt.py
- bindings/python/pymongocrypt/state_machine.py
- bindings/python/setup.py
- bindings/python/test/__init__.py
- bindings/python/test/test_mongocrypt.py
Reverts mongodb/libmongocrypt#440
Merged the wrong PR
> Revert "PYTHON-3256 Obtain AWS credentials for CSFLE in the same way as for MONGODB-AWS"

- bindings/node/README.md
- bindings/node/index.d.ts
- bindings/node/lib/autoEncrypter.js
- bindings/node/lib/clientEncryption.js
> docs(NODE-4725): Change docs to use "in use encryption" terminology

- bindings/python/pymongocrypt/credentials.py
- bindings/python/pymongocrypt/mongocrypt.py
- bindings/python/test/data/key-document-azure.json
- bindings/python/test/data/kms-reply-azure.txt
- bindings/python/test/test_mongocrypt.py
Will require a corresponding integration test in mongo-python-driver
> PYTHON-3396 Support the Azure VM-assigned Managed Identity for Automatic KMS Credentials

- kms-message/src/kms_crypto.h
- kms-message/src/kms_crypto_apple.c
- kms-message/src/kms_crypto_libcrypto.c
- kms-message/src/kms_crypto_none.c
- kms-message/src/kms_crypto_windows.c
- kms-message/src/kms_request_str.c
- src/crypto/cng.c
- src/crypto/commoncrypto.c
- src/crypto/libcrypto.c
- src/crypto/none.c
- src/mlib/path.h
- src/mongocrypt-crypto-private.h
- src/mongocrypt-key-private.h
- src/mongocrypt-key.c
- src/mongocrypt-util-private.h
- src/mongocrypt-util.c
- src/mongocrypt.c
https://jira.mongodb.org/browse/MONGOCRYPT-496
> MONGOCRYPT-496 use void parameter list in declarations

- bindings/python/pymongocrypt/mongocrypt.py
Fixes https://jira.mongodb.org/browse/PYTHON-3530
> PYTHON-3530 Fix spurious exception traceback at interpreter shutdown

- README.md
The CSFLE guide has been archived.
Reference the installation page instead.
> update release instructions

- README.md
- bindings/java/mongocrypt/README.md
- bindings/python/README.rst
- bindings/python/RELEASE.rst
- remove link from public README
- in release procedure documentation note that auth is required
> Evergreen link updates

- src/mc-fle2-payload-iev.c
Follow up for 55f2ee0382813e454004af29a9d4913170caf4d8
> restore client encrypted value length check

- src/mc-fle2-payload-iev.c
- test/test-mc-fle2-payload-iev.c
- test/test-mongocrypt-crypto.c
Follow up to https://github.com/mongodb/libmongocrypt/commit/55f2ee0382813e454004af29a9d4913170caf4d8 and https://github.com/mongodb/libmongocrypt/commit/10aab29f5bd7faad01ad38ff55181dd8603d02ab.
> MONGOCRYPT-466 MONGOCRYPT-467 MONGOCRYPT-468 remove length check and extra status

- bindings/node/test/clientEncryption.test.js
Remove callback style findOne usage from tests
Driver patch: https://spruce.mongodb.com/version/63ceb9470ae6060436a4eff0/tasks
> test(NODE-4993): migrate create a data key test to promise usage

- bindings/python/CHANGELOG.rst
- bindings/python/pymongocrypt/explicit_encrypter.py
- bindings/python/pymongocrypt/version.py
- bindings/python/release.sh
https://jira.mongodb.org/browse/PYTHON-3574
> PYTHON-3574 Bump min libmongocrypt version to 1.7.0

- bindings/python/CHANGELOG.rst
- bindings/python/pymongocrypt/version.py
- bindings/python/release.sh
PYTHON-3594 Bundle libmongocrypt 1.7.1 in wheels
> pymongocrypt 1.5.1

- CMakeLists.txt
- src/mc-dec128.h
- src/mc-fle2-insert-update-payload-private-v2.h
- src/mc-fle2-insert-update-payload-v2.c
- src/mc-fle2-payload-iev.c
- src/mc-writer.c
- src/mongocrypt-private.h
Lots of copy paste code from v1 code.
> MONGOCRYPT-527 Add parse & serialization of FLE2InsertUpdatePayloadV2

- bindings/node/src/mongocrypt.cc
Enables QE v2 in the Node bindings.
> feat(NODE-5074): enable queryable encryption v2

- bindings/python/CHANGELOG.rst
- bindings/python/release.sh
https://jira.mongodb.org/browse/PYTHON-3654
> PYTHON-3654 Bundle libmongocrypt 1.7.3 in wheels

- bindings/python/setup.py
https://jira.mongodb.org/browse/PYTHON-3663
> PYTHON-3663 Pin cryptography<40 on PyPy <7.3.10

- cmake/IntelDFP.cmake
- etc/mongo-inteldfp-MONGOCRYPT-571.patch
MONGOCRYPT-571
Fix build for MacOS Ventura
Patch missing headers for Intel DFP
> Fix build for MacOS Ventura

- src/mongocrypt-key-broker.c
This is a common error and a small hint will help developers troubleshoot
> MONGOCRYPT-574 Indicate why "not all keys requested were satisfied" was triggered

- src/mongocrypt-ctx-rewrap-many-datakey.c
> cleanup doc before exiting on error

- bindings/python/pymongocrypt/binding.py
https://jira.mongodb.org/browse/PYTHON-3685
> PYTHON-3685 Update binding.py for libmongocrypt 1.8.0-alpha1

- .evergreen/config.yml
- bindings/python/.evergreen/test.sh
- bindings/python/.evergreen/utils.sh
- bindings/python/CHANGELOG.rst
- bindings/python/README.rst
- bindings/python/build-manylinux-wheel.sh
- bindings/python/pymongocrypt/compat.py
- bindings/python/pymongocrypt/mongocrypt.py
- bindings/python/setup.py
- bindings/python/test-requirements.txt
- bindings/python/test/__init__.py
- bindings/python/test/test_mongocrypt.py
https://jira.mongodb.org/browse/PYTHON-3707
> PYTHON-3707 Drop support for Python 2.7, 3.4, 3.5, and 3.6

- .evergreen/earthly.sh
Evergreen patch build: https://spruce.mongodb.com/version/6484d41f3066150a7a5cc6c6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> use latest earthly

- etc/repo_config.yaml
Follow up for 862152a37a8224a82a5d49c9486ca05eb6318fed
> MONGOCRYPT-579 use correct S3 bucket name

- etc/repo_config.yaml
This reverts commit 0eb65c0ac678b9bff882adfd436c4aadbb5874b0.
> Revert "MONGOCRYPT-579 use correct S3 bucket name (#664)"

- src/mongocrypt-marking.c
Intends to resolve Coverity issue with CID 135364.
I expect this issue has little to no impact. Proposed change is consistent with other calls to `_mongocrypt_buffer_concat` and intended to improve handling in the event of a failure to allocate the buffer.
> check return of `_mongocrypt_buffer_concat`

- CMakeLists.txt
- src/crypto/libcrypto.c
- test/test-mongocrypt-traverse-util.c
Evergreen patch build: https://spruce.mongodb.com/version/64f1354be3c3312f15caa880/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> MONGOCRYPT-587 compiler warnings

- bindings/java/mongocrypt/build.gradle.kts
See: https://docs.gradle.org/current/userguide/feature_variants.html
MONGOCRYPT-602
> Use gradles features to make slf4j optional

- bindings/python/.evergreen/test.sh
https://jira.mongodb.org/browse/PYTHON-4091
> PYTHON-4091 Skip perf benchmark when running test suite

- README.md
Follow-up for ef5b0b54adaadf3b8a1a151aa31b91702bf17187
> MONGOCRYPT-580 document steps for installing on Amazon Linux 2023

- CHANGELOG.md
- README.md
And updates release steps post the 1.9.0 release.
> update CHANGELOG.md for 1.9.0

- bindings/python/pymongocrypt/version.py
PYTHON-4221 pymongocrypt 1.9.0.
> PYTHON-4221 pymongocrypt 1.9.0

- .github/workflows/release-python.yml
- bindings/python/CHANGELOG.rst
- bindings/python/pymongocrypt/version.py
- bindings/python/release.sh
[PYTHON-4246](https://jira.mongodb.org/browse/PYTHON-4246)
> PYTHON-4246 Fix release publish task

- .evergreen/create-packages-and-repos.sh
- .evergreen/earthly.sh
follow-up for 3253caa48e58edb0f92ebe7d8a567fe773f962e3
> fix create-packages-and-repos and earthly builds in Evergreen

- bindings/java/mongocrypt/src/main/resources/META-INF/native-image/jni-config.json
- bindings/java/mongocrypt/src/main/resources/META-INF/native-image/reflect-config.json
> Add GraalVM reachability metadata

- CHANGELOG.md
- README.md
- doc/releasing.md
And update links in release instructions.
> Update CHANGELOG and README for 1.10.0

- src/mc-fle2-payload-iev.c
- src/mc-range-edge-generation.c
- src/mc-range-encoding.c
This PR addresses issues reported in an external audit. See [this comment](https://jira.mongodb.org/browse/MONGOCRYPT-686?focusedCommentId=6345493&focusedId=6345493&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6345493) for the (internal) audit report.
The issues reported appear to be false-positives or minor code-cleanup. See individual commits for a description behind the changes.
> MONGOCRYPT-686 address audit issues

- bindings/python/pymongocrypt/binding.py
- bindings/python/pyproject.toml
(cherry picked from commit 7f396b84308ae0428bcdf4f55f9b387ecfe24981)
> PYTHON-4452 [backport] Fix setuptools version metadata

- bindings/cs/Scripts/build.cake
Updating some things in the cake build script that were failing and making the build process frustrating.
> CSHARP-5100: Update Libmongocrypt cake build script

- bindings/java/mongocrypt/build.gradle.kts
We did not do this when releasing 1.8
> Java version to 1.10.0-SNAPSHOT

- CHANGELOG.md
- README.md
- doc/releasing.md
Update CHANGELOG.md and README.md for 1.11.0 release. Apply minor fixes to the release steps.
> Update for 1.11.0 release

- .evergreen/debian_package_build.sh
Single task patch build: https://spruce.mongodb.com/version/66c77fda309a3b0007f35739/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> install python3-packaging in the Debian package build env

- .github/workflows/release-python.yml
> PYTHON-5017 Fix handling of post-publish step

- .github/workflows/release-python.yml
Use the proper GitHub environment.
> PYTHON-5017 Fix handling of post-publish step yet again

- .evergreen/debian_package_build.sh
Evergreen patch build: https://spruce.mongodb.com/version/67803aa81d9d4800071497e0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> mount proc and sys in Debian package build chroot (r1.12)

- .evergreen/debian_package_build.sh
Evergreen patch build: https://spruce.mongodb.com/version/67803945ed23370007a05deb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> mount proc and sys in Debian package build chroot

- CHANGELOG.md
- README.md
- doc/releasing.md
- etc/cyclonedx.sbom.json
- Include updates to CHANGELOG.md, README.md from 1.13.0 release.
- Update SBOM serial number.
- Update release release instructions.
- Add step to update SBOM serial number on `master` branch after release.
> Apply changes from 1.13.0 release

- bindings/python/.evergreen/integ-test.sh
Passing build: https://spruce.mongodb.com/version/67eaf40535c0cd0007d9d787/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-5015 Test with stable pymongo
